namespace ns33
{
	// Token: 0x0200099D RID: 2461
	
	public sealed partial class EditTrigger : global::ns33.CommandForm
	{
		// Token: 0x06003F13 RID: 16147 RVA: 0x00152E34 File Offset: 0x00151034
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06003F14 RID: 16148 RVA: 0x00152E78 File Offset: 0x00151078
		private void InitializeComponent()
		{
			this.icontainer_0 = new global::System.ComponentModel.Container();
			this.vmethod_1(new global::System.Windows.Forms.Label());
			this.vmethod_3(new global::System.Windows.Forms.TextBox());
			this.vmethod_5(new global::System.Windows.Forms.Button());
			this.vmethod_7(new global::System.Windows.Forms.Button());
			this.vmethod_9(new global::System.Windows.Forms.Label());
			this.vmethod_11(new global::System.Windows.Forms.TabPage());
			this.vmethod_15(new global::Command.UnitFilter());
			this.vmethod_13(new global::ns15.Control1());
			this.vmethod_17(new global::System.Windows.Forms.TabPage());
			this.vmethod_45(new global::System.Windows.Forms.NumericUpDown());
			this.vmethod_47(new global::System.Windows.Forms.Label());
			this.vmethod_21(new global::Command.UnitFilter());
			this.vmethod_19(new global::System.Windows.Forms.TabPage());
			this.vmethod_23(new global::System.Windows.Forms.ComboBox());
			this.vmethod_25(new global::System.Windows.Forms.Label());
			this.vmethod_27(new global::System.Windows.Forms.NumericUpDown());
			this.vmethod_29(new global::System.Windows.Forms.ComboBox());
			this.vmethod_31(new global::System.Windows.Forms.Label());
			this.vmethod_33(new global::System.Windows.Forms.Label());
			this.vmethod_35(new global::System.Windows.Forms.TabPage());
			this.vmethod_43(new global::System.Windows.Forms.Button());
			this.vmethod_41(new global::System.Windows.Forms.Label());
			this.vmethod_37(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_39(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_49(new global::System.Windows.Forms.TabPage());
			this.vmethod_55(new global::System.Windows.Forms.GroupBox());
			this.vmethod_67(new global::System.Windows.Forms.Label());
			this.vmethod_69(new global::System.Windows.Forms.Label());
			this.vmethod_71(new global::System.Windows.Forms.TextBox());
			this.vmethod_57(new global::System.Windows.Forms.TextBox());
			this.vmethod_59(new global::System.Windows.Forms.TextBox());
			this.vmethod_61(new global::System.Windows.Forms.Label());
			this.vmethod_63(new global::System.Windows.Forms.TextBox());
			this.vmethod_65(new global::System.Windows.Forms.Label());
			this.vmethod_53(new global::ns33.AreaEditor());
			this.vmethod_51(new global::Command.UnitFilter());
			this.vmethod_73(new global::System.Windows.Forms.TabPage());
			this.vmethod_93(new global::System.Windows.Forms.CheckBox());
			this.vmethod_75(new global::System.Windows.Forms.GroupBox());
			this.vmethod_89(new global::System.Windows.Forms.Button());
			this.vmethod_91(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_97(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_87(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_85(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_77(new global::System.Windows.Forms.Label());
			this.vmethod_79(new global::System.Windows.Forms.Label());
			this.vmethod_81(new global::ns33.AreaEditor());
			this.vmethod_83(new global::Command.UnitFilter());
			this.vmethod_99(new global::System.Windows.Forms.TabPage());
			this.vmethod_101(new global::System.Windows.Forms.Label());
			this.vmethod_103(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_105(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_107(new global::System.Windows.Forms.Label());
			this.vmethod_109(new global::System.Windows.Forms.Button());
			this.vmethod_111(new global::System.Windows.Forms.Label());
			this.vmethod_113(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_115(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_117(new global::System.Windows.Forms.TabPage());
			this.vmethod_125(new global::System.Windows.Forms.ComboBox());
			this.vmethod_127(new global::System.Windows.Forms.Label());
			this.vmethod_121(new global::System.Windows.Forms.ComboBox());
			this.vmethod_123(new global::System.Windows.Forms.Label());
			this.vmethod_119(new global::Command.UnitFilter());
			this.vmethod_129(new global::System.Windows.Forms.TabPage());
			this.vmethod_131(new global::System.Windows.Forms.ComboBox());
			this.vmethod_133(new global::System.Windows.Forms.Label());
			this.vmethod_95(new global::System.Windows.Forms.ToolTip(this.icontainer_0));
			this.vmethod_10().SuspendLayout();
			this.vmethod_12().SuspendLayout();
			this.vmethod_16().SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_44()).BeginInit();
			this.vmethod_18().SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_26()).BeginInit();
			this.vmethod_34().SuspendLayout();
			this.vmethod_48().SuspendLayout();
			this.vmethod_54().SuspendLayout();
			this.vmethod_72().SuspendLayout();
			this.vmethod_74().SuspendLayout();
			this.vmethod_98().SuspendLayout();
			this.vmethod_116().SuspendLayout();
			this.vmethod_128().SuspendLayout();
			base.SuspendLayout();
			this.vmethod_0().AutoSize = true;
			this.vmethod_0().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_0().Location = new global::System.Drawing.Point(4, 10);
			this.vmethod_0().Name = "Label2";
			this.vmethod_0().Size = new global::System.Drawing.Size(75, 13);
			this.vmethod_0().TabIndex = 3;
			this.vmethod_0().Text = "说明:";
			this.vmethod_2().Location = new global::System.Drawing.Point(90, 6);
			this.vmethod_2().Name = "TextBox1";
			this.vmethod_2().Size = new global::System.Drawing.Size(451, 20);
			this.vmethod_2().TabIndex = 4;
			this.vmethod_4().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_4().Location = new global::System.Drawing.Point(2, 402);
			this.vmethod_4().Name = "Button_OK";
			this.vmethod_4().Size = new global::System.Drawing.Size(278, 23);
			this.vmethod_4().TabIndex = 5;
			this.vmethod_4().Text = "确认";
			this.vmethod_4().UseVisualStyleBackColor = true;
			this.vmethod_6().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_6().Location = new global::System.Drawing.Point(466, 402);
			this.vmethod_6().Name = "Button_Cancel";
			this.vmethod_6().Size = new global::System.Drawing.Size(278, 23);
			this.vmethod_6().TabIndex = 6;
			this.vmethod_6().Text = "取消";
			this.vmethod_6().UseVisualStyleBackColor = true;
			this.vmethod_8().AutoSize = true;
			this.vmethod_8().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_8().Location = new global::System.Drawing.Point(1, 43);
			this.vmethod_8().Name = "Label3";
			this.vmethod_8().Size = new global::System.Drawing.Size(112, 13);
			this.vmethod_8().TabIndex = 7;
			this.vmethod_8().Text = "触发器设置";
			this.vmethod_10().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_10().Controls.Add(this.vmethod_14());
			this.vmethod_10().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_10().Name = "TabPage1";
			this.vmethod_10().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_10().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_10().TabIndex = 0;
			this.vmethod_10().Text = "Unit is Destroyed";
			this.vmethod_14().method_0(null);
			this.vmethod_14().Location = new global::System.Drawing.Point(6, 6);
			this.vmethod_14().MinimumSize = new global::System.Drawing.Size(311, 177);
			this.vmethod_14().Name = "UnitFilter_UnitDestroyed";
			this.vmethod_14().Size = new global::System.Drawing.Size(311, 177);
			this.vmethod_14().TabIndex = 0;
			this.vmethod_12().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_12().Controls.Add(this.vmethod_10());
			this.vmethod_12().Controls.Add(this.vmethod_16());
			this.vmethod_12().Controls.Add(this.vmethod_18());
			this.vmethod_12().Controls.Add(this.vmethod_34());
			this.vmethod_12().Controls.Add(this.vmethod_48());
			this.vmethod_12().Controls.Add(this.vmethod_72());
			this.vmethod_12().Controls.Add(this.vmethod_98());
			this.vmethod_12().Controls.Add(this.vmethod_116());
			this.vmethod_12().Controls.Add(this.vmethod_128());
			this.vmethod_12().Location = new global::System.Drawing.Point(2, 59);
			this.vmethod_12().Multiline = true;
			this.vmethod_12().Name = "TC_TriggerOptions";
			this.vmethod_12().SelectedIndex = 0;
			this.vmethod_12().Size = new global::System.Drawing.Size(752, 337);
			this.vmethod_12().TabIndex = 20;
			this.vmethod_16().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_16().Controls.Add(this.vmethod_44());
			this.vmethod_16().Controls.Add(this.vmethod_46());
			this.vmethod_16().Controls.Add(this.vmethod_20());
			this.vmethod_16().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_16().Name = "TabPage2";
			this.vmethod_16().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_16().TabIndex = 1;
			this.vmethod_16().Text = "Unit is Damaged";
			this.vmethod_44().Location = new global::System.Drawing.Point(166, 181);
			this.vmethod_44().Name = "NUD_DamagePercent";
			this.vmethod_44().Size = new global::System.Drawing.Size(74, 20);
			this.vmethod_44().TabIndex = 3;
			this.vmethod_46().Location = new global::System.Drawing.Point(20, 183);
			this.vmethod_46().Name = "Label7";
			this.vmethod_46().Size = new global::System.Drawing.Size(140, 13);
			this.vmethod_46().TabIndex = 2;
			this.vmethod_46().Text = "Damage Percent Threshold:";
			this.vmethod_20().method_0(null);
			this.vmethod_20().Location = new global::System.Drawing.Point(6, 6);
			this.vmethod_20().MinimumSize = new global::System.Drawing.Size(311, 177);
			this.vmethod_20().Name = "UnitFilter_UnitDamaged";
			this.vmethod_20().Size = new global::System.Drawing.Size(311, 177);
			this.vmethod_20().TabIndex = 1;
			this.vmethod_18().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_18().Controls.Add(this.vmethod_22());
			this.vmethod_18().Controls.Add(this.vmethod_24());
			this.vmethod_18().Controls.Add(this.vmethod_26());
			this.vmethod_18().Controls.Add(this.vmethod_28());
			this.vmethod_18().Controls.Add(this.vmethod_30());
			this.vmethod_18().Controls.Add(this.vmethod_32());
			this.vmethod_18().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_18().Name = "TabPage3";
			this.vmethod_18().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_18().TabIndex = 2;
			this.vmethod_18().Text = "Side Points";
			this.vmethod_22().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_22().FormattingEnabled = true;
			this.vmethod_22().Items.AddRange(new object[]
			{
				"超过",
				"刚好达到",
				"低于"
			});
			this.vmethod_22().Location = new global::System.Drawing.Point(153, 126);
			this.vmethod_22().Name = "CB_Points_ReachDirection";
			this.vmethod_22().Size = new global::System.Drawing.Size(121, 21);
			this.vmethod_22().TabIndex = 10;
			this.vmethod_24().Location = new global::System.Drawing.Point(351, 128);
			this.vmethod_24().Name = "Label5";
			this.vmethod_24().Size = new global::System.Drawing.Size(35, 13);
			this.vmethod_24().TabIndex = 9;
			this.vmethod_24().Text = "points";
			this.vmethod_26().Location = new global::System.Drawing.Point(280, 126);
			global::System.Windows.Forms.NumericUpDown numericUpDown = this.vmethod_26();
			int[] array = new int[4];
			array[0] = 999999;
			numericUpDown.Maximum = new decimal(array);
			this.vmethod_26().Minimum = new decimal(new int[]
			{
				999999,
				0,
				0,
				-2147483648
			});
			this.vmethod_26().Name = "NUD_Points";
			this.vmethod_26().Size = new global::System.Drawing.Size(65, 20);
			this.vmethod_26().TabIndex = 8;
			this.vmethod_28().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_28().FormattingEnabled = true;
			this.vmethod_28().Location = new global::System.Drawing.Point(153, 98);
			this.vmethod_28().Name = "CB_Points_Sides";
			this.vmethod_28().Size = new global::System.Drawing.Size(192, 21);
			this.vmethod_28().TabIndex = 7;
			this.vmethod_30().Location = new global::System.Drawing.Point(10, 128);
			this.vmethod_30().Name = "Label4";
			this.vmethod_30().Size = new global::System.Drawing.Size(137, 13);
			this.vmethod_30().TabIndex = 6;
			this.vmethod_30().Text = "Trigger activates when side";
			this.vmethod_32().Location = new global::System.Drawing.Point(116, 101);
			this.vmethod_32().Name = "Label1";
			this.vmethod_32().Size = new global::System.Drawing.Size(31, 13);
			this.vmethod_32().TabIndex = 5;
			this.vmethod_32().Text = "Side:";
			this.vmethod_34().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_34().Controls.Add(this.vmethod_42());
			this.vmethod_34().Controls.Add(this.vmethod_40());
			this.vmethod_34().Controls.Add(this.vmethod_36());
			this.vmethod_34().Controls.Add(this.vmethod_38());
			this.vmethod_34().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_34().Name = "TabPage4";
			this.vmethod_34().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_34().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_34().TabIndex = 3;
			this.vmethod_34().Text = "Time";
			this.vmethod_42().Location = new global::System.Drawing.Point(229, 139);
			this.vmethod_42().Name = "Button_SetTime";
			this.vmethod_42().Size = new global::System.Drawing.Size(75, 23);
			this.vmethod_42().TabIndex = 25;
			this.vmethod_42().Text = "设置时间";
			this.vmethod_42().UseVisualStyleBackColor = true;
			this.vmethod_40().AutoSize = true;
			this.vmethod_40().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_40().Location = new global::System.Drawing.Point(158, 45);
			this.vmethod_40().Name = "Label6";
			this.vmethod_40().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_40().TabIndex = 24;
			this.vmethod_40().Text = "Label6";
			this.vmethod_36().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_36().Location = new global::System.Drawing.Point(161, 113);
			this.vmethod_36().Name = "DTP_StartTime";
			this.vmethod_36().Size = new global::System.Drawing.Size(223, 20);
			this.vmethod_36().TabIndex = 23;
			this.vmethod_36().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_38().Location = new global::System.Drawing.Point(161, 87);
			this.vmethod_38().Name = "DTP_StartDate";
			this.vmethod_38().Size = new global::System.Drawing.Size(223, 20);
			this.vmethod_38().TabIndex = 22;
			this.vmethod_38().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_48().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_48().Controls.Add(this.vmethod_54());
			this.vmethod_48().Controls.Add(this.vmethod_52());
			this.vmethod_48().Controls.Add(this.vmethod_50());
			this.vmethod_48().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_48().Name = "TabPage5";
			this.vmethod_48().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_48().TabIndex = 4;
			this.vmethod_48().Text = "Unit Remains In Area";
			this.vmethod_54().Controls.Add(this.vmethod_66());
			this.vmethod_54().Controls.Add(this.vmethod_68());
			this.vmethod_54().Controls.Add(this.vmethod_70());
			this.vmethod_54().Controls.Add(this.vmethod_56());
			this.vmethod_54().Controls.Add(this.vmethod_58());
			this.vmethod_54().Controls.Add(this.vmethod_60());
			this.vmethod_54().Controls.Add(this.vmethod_62());
			this.vmethod_54().Controls.Add(this.vmethod_64());
			this.vmethod_54().Location = new global::System.Drawing.Point(345, 31);
			this.vmethod_54().Name = "GroupBox1";
			this.vmethod_54().Size = new global::System.Drawing.Size(163, 119);
			this.vmethod_54().TabIndex = 4;
			this.vmethod_54().TabStop = false;
			this.vmethod_54().Text = "Required Time Amount";
			this.vmethod_66().Location = new global::System.Drawing.Point(119, 78);
			this.vmethod_66().Name = "Label12";
			this.vmethod_66().Size = new global::System.Drawing.Size(29, 13);
			this.vmethod_66().TabIndex = 27;
			this.vmethod_66().Text = "secs";
			this.vmethod_68().Location = new global::System.Drawing.Point(43, 78);
			this.vmethod_68().Name = "Label11";
			this.vmethod_68().Size = new global::System.Drawing.Size(28, 13);
			this.vmethod_68().TabIndex = 26;
			this.vmethod_68().Text = "mins";
			this.vmethod_70().Location = new global::System.Drawing.Point(78, 75);
			this.vmethod_70().Name = "TB_Secs";
			this.vmethod_70().Size = new global::System.Drawing.Size(39, 20);
			this.vmethod_70().TabIndex = 25;
			this.vmethod_70().Text = "0";
			this.vmethod_56().Location = new global::System.Drawing.Point(6, 75);
			this.vmethod_56().Name = "TB_Mins";
			this.vmethod_56().Size = new global::System.Drawing.Size(36, 20);
			this.vmethod_56().TabIndex = 24;
			this.vmethod_56().Text = "0";
			this.vmethod_58().Location = new global::System.Drawing.Point(78, 35);
			this.vmethod_58().Name = "TB_Hours";
			this.vmethod_58().Size = new global::System.Drawing.Size(39, 20);
			this.vmethod_58().TabIndex = 22;
			this.vmethod_58().Text = "0";
			this.vmethod_60().Location = new global::System.Drawing.Point(40, 39);
			this.vmethod_60().Name = "Label10";
			this.vmethod_60().Size = new global::System.Drawing.Size(29, 13);
			this.vmethod_60().TabIndex = 19;
			this.vmethod_60().Text = "days";
			this.vmethod_62().Location = new global::System.Drawing.Point(7, 35);
			this.vmethod_62().Name = "TB_Days";
			this.vmethod_62().Size = new global::System.Drawing.Size(35, 20);
			this.vmethod_62().TabIndex = 20;
			this.vmethod_62().Text = "0";
			this.vmethod_64().Location = new global::System.Drawing.Point(119, 39);
			this.vmethod_64().Name = "Label9";
			this.vmethod_64().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_64().TabIndex = 21;
			this.vmethod_64().Text = "hours";
			this.vmethod_52().Location = new global::System.Drawing.Point(175, 183);
			this.vmethod_52().Name = "AreaEditor_UnitInArea";
			this.vmethod_52().Size = new global::System.Drawing.Size(351, 124);
			this.vmethod_52().TabIndex = 3;
			this.vmethod_52().method_0("Area To Be Inside");
			this.vmethod_50().method_0(null);
			this.vmethod_50().Location = new global::System.Drawing.Point(6, 6);
			this.vmethod_50().MinimumSize = new global::System.Drawing.Size(311, 177);
			this.vmethod_50().Name = "UnitFilter_UnitInArea";
			this.vmethod_50().Size = new global::System.Drawing.Size(311, 177);
			this.vmethod_50().TabIndex = 2;
			this.vmethod_72().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_72().Controls.Add(this.vmethod_92());
			this.vmethod_72().Controls.Add(this.vmethod_74());
			this.vmethod_72().Controls.Add(this.vmethod_80());
			this.vmethod_72().Controls.Add(this.vmethod_82());
			this.vmethod_72().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_72().Name = "TabPage6";
			this.vmethod_72().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_72().TabIndex = 5;
			this.vmethod_72().Text = "Unit Enters Area";
			this.vmethod_92().AutoSize = true;
			this.vmethod_92().Location = new global::System.Drawing.Point(41, 234);
			this.vmethod_92().Name = "CB_UnitEntersArea_ModifierNOT";
			this.vmethod_92().Size = new global::System.Drawing.Size(92, 17);
			this.vmethod_92().TabIndex = 8;
			this.vmethod_92().Text = "Modifier: NOT";
			this.vmethod_94().SetToolTip(this.vmethod_92(), "\"When checked, the trigger fires if an eligible unit is NOT in the specified area within the specified time frame");
			this.vmethod_92().UseVisualStyleBackColor = true;
			this.vmethod_74().Controls.Add(this.vmethod_88());
			this.vmethod_74().Controls.Add(this.vmethod_90());
			this.vmethod_74().Controls.Add(this.vmethod_96());
			this.vmethod_74().Controls.Add(this.vmethod_86());
			this.vmethod_74().Controls.Add(this.vmethod_84());
			this.vmethod_74().Controls.Add(this.vmethod_76());
			this.vmethod_74().Controls.Add(this.vmethod_78());
			this.vmethod_74().Location = new global::System.Drawing.Point(323, 6);
			this.vmethod_74().Name = "GroupBox2";
			this.vmethod_74().Size = new global::System.Drawing.Size(203, 177);
			this.vmethod_74().TabIndex = 7;
			this.vmethod_74().TabStop = false;
			this.vmethod_74().Text = "Earliest + Latest Time";
			this.vmethod_88().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_88().Location = new global::System.Drawing.Point(63, 153);
			this.vmethod_88().Name = "Button_UnitEntersArea";
			this.vmethod_88().Size = new global::System.Drawing.Size(75, 22);
			this.vmethod_88().TabIndex = 32;
			this.vmethod_88().Text = "SET TIMES";
			this.vmethod_88().UseVisualStyleBackColor = true;
			this.vmethod_90().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_90().Location = new global::System.Drawing.Point(104, 128);
			this.vmethod_90().Name = "DTP_EnterArea_LTOA_Time";
			this.vmethod_90().Size = new global::System.Drawing.Size(93, 20);
			this.vmethod_90().TabIndex = 31;
			this.vmethod_90().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_96().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_96().Location = new global::System.Drawing.Point(104, 63);
			this.vmethod_96().Name = "DTP_EnterArea_ETOA_Time";
			this.vmethod_96().Size = new global::System.Drawing.Size(93, 20);
			this.vmethod_96().TabIndex = 30;
			this.vmethod_96().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_86().Location = new global::System.Drawing.Point(6, 102);
			this.vmethod_86().Name = "DTP_EnterArea_LTOA_Date";
			this.vmethod_86().Size = new global::System.Drawing.Size(191, 20);
			this.vmethod_86().TabIndex = 29;
			this.vmethod_86().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_84().Location = new global::System.Drawing.Point(6, 37);
			this.vmethod_84().Name = "DTP_EnterArea_ETOA_Date";
			this.vmethod_84().Size = new global::System.Drawing.Size(191, 20);
			this.vmethod_84().TabIndex = 28;
			this.vmethod_84().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_76().Location = new global::System.Drawing.Point(3, 86);
			this.vmethod_76().Name = "Label_UnitEntersArea_Latest";
			this.vmethod_76().Size = new global::System.Drawing.Size(39, 13);
			this.vmethod_76().TabIndex = 27;
			this.vmethod_76().Text = "Latest:";
			this.vmethod_78().Location = new global::System.Drawing.Point(3, 21);
			this.vmethod_78().Name = "Label_UnitEntersArea_Earliest";
			this.vmethod_78().Size = new global::System.Drawing.Size(44, 13);
			this.vmethod_78().TabIndex = 26;
			this.vmethod_78().Text = "Earliest:";
			this.vmethod_80().Location = new global::System.Drawing.Point(175, 184);
			this.vmethod_80().Name = "AreaEditor_UnitEntersArea";
			this.vmethod_80().Size = new global::System.Drawing.Size(351, 125);
			this.vmethod_80().TabIndex = 6;
			this.vmethod_80().method_0("Area To Be Inside");
			this.vmethod_82().method_0(null);
			this.vmethod_82().Location = new global::System.Drawing.Point(6, 6);
			this.vmethod_82().MinimumSize = new global::System.Drawing.Size(311, 177);
			this.vmethod_82().Name = "UnitFilter_UnitEntersArea";
			this.vmethod_82().Size = new global::System.Drawing.Size(311, 177);
			this.vmethod_82().TabIndex = 5;
			this.vmethod_98().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_98().Controls.Add(this.vmethod_100());
			this.vmethod_98().Controls.Add(this.vmethod_102());
			this.vmethod_98().Controls.Add(this.vmethod_104());
			this.vmethod_98().Controls.Add(this.vmethod_106());
			this.vmethod_98().Controls.Add(this.vmethod_108());
			this.vmethod_98().Controls.Add(this.vmethod_110());
			this.vmethod_98().Controls.Add(this.vmethod_112());
			this.vmethod_98().Controls.Add(this.vmethod_114());
			this.vmethod_98().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_98().Name = "TabPage7";
			this.vmethod_98().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_98().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_98().TabIndex = 6;
			this.vmethod_98().Text = "Random Time";
			this.vmethod_100().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_100().Location = new global::System.Drawing.Point(169, 154);
			this.vmethod_100().Name = "Label14";
			this.vmethod_100().Size = new global::System.Drawing.Size(46, 13);
			this.vmethod_100().TabIndex = 33;
			this.vmethod_100().Text = "Latest:";
			this.vmethod_102().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_102().Location = new global::System.Drawing.Point(172, 196);
			this.vmethod_102().Name = "DTP_LatestTime";
			this.vmethod_102().Size = new global::System.Drawing.Size(223, 20);
			this.vmethod_102().TabIndex = 32;
			this.vmethod_102().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_104().Location = new global::System.Drawing.Point(172, 170);
			this.vmethod_104().Name = "DTP_LatestDate";
			this.vmethod_104().Size = new global::System.Drawing.Size(223, 20);
			this.vmethod_104().TabIndex = 31;
			this.vmethod_104().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_106().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_106().Location = new global::System.Drawing.Point(169, 77);
			this.vmethod_106().Name = "Label13";
			this.vmethod_106().Size = new global::System.Drawing.Size(53, 13);
			this.vmethod_106().TabIndex = 30;
			this.vmethod_106().Text = "Earliest:";
			this.vmethod_108().Location = new global::System.Drawing.Point(230, 231);
			this.vmethod_108().Name = "Button1";
			this.vmethod_108().Size = new global::System.Drawing.Size(100, 23);
			this.vmethod_108().TabIndex = 29;
			this.vmethod_108().Text = "Set Random Time";
			this.vmethod_108().UseVisualStyleBackColor = true;
			this.vmethod_110().AutoSize = true;
			this.vmethod_110().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_110().Location = new global::System.Drawing.Point(170, 23);
			this.vmethod_110().Name = "Label8";
			this.vmethod_110().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_110().TabIndex = 28;
			this.vmethod_110().Text = "Label8";
			this.vmethod_112().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_112().Location = new global::System.Drawing.Point(172, 119);
			this.vmethod_112().Name = "DTP_EarliestTime";
			this.vmethod_112().Size = new global::System.Drawing.Size(223, 20);
			this.vmethod_112().TabIndex = 27;
			this.vmethod_112().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_114().Location = new global::System.Drawing.Point(172, 93);
			this.vmethod_114().Name = "DTP_EarliestDate";
			this.vmethod_114().Size = new global::System.Drawing.Size(223, 20);
			this.vmethod_114().TabIndex = 26;
			this.vmethod_114().Value = new global::System.DateTime(1950, 5, 9, 23, 38, 0, 0);
			this.vmethod_116().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_116().Controls.Add(this.vmethod_124());
			this.vmethod_116().Controls.Add(this.vmethod_126());
			this.vmethod_116().Controls.Add(this.vmethod_120());
			this.vmethod_116().Controls.Add(this.vmethod_122());
			this.vmethod_116().Controls.Add(this.vmethod_118());
			this.vmethod_116().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_116().Name = "TabPage8";
			this.vmethod_116().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_116().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_116().TabIndex = 7;
			this.vmethod_116().Text = "Unit is Detected";
			this.vmethod_124().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_124().FormattingEnabled = true;
			this.vmethod_124().Items.AddRange(new object[]
			{
				"不明",
				"知道领域 (比如. 舰艇, 飞机)",
				"知道类型 (比如. 护卫舰, 轰炸机)",
				"知道型号 (比如. F-16, Nimitz级)",
				"具体ID (比如. Air Force One, USS Nimitz)"
			});
			this.vmethod_124().Location = new global::System.Drawing.Point(477, 110);
			this.vmethod_124().Name = "CB_MCL";
			this.vmethod_124().Size = new global::System.Drawing.Size(146, 21);
			this.vmethod_124().TabIndex = 11;
			this.vmethod_126().Location = new global::System.Drawing.Point(332, 113);
			this.vmethod_126().Name = "Label16";
			this.vmethod_126().Size = new global::System.Drawing.Size(139, 13);
			this.vmethod_126().TabIndex = 10;
			this.vmethod_126().Text = "Minimum classification level:";
			this.vmethod_120().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_120().FormattingEnabled = true;
			this.vmethod_120().Location = new global::System.Drawing.Point(431, 83);
			this.vmethod_120().Name = "CB_UnitDetected_Sides";
			this.vmethod_120().Size = new global::System.Drawing.Size(192, 21);
			this.vmethod_120().TabIndex = 9;
			this.vmethod_122().Location = new global::System.Drawing.Point(350, 86);
			this.vmethod_122().Name = "Label15";
			this.vmethod_122().Size = new global::System.Drawing.Size(75, 13);
			this.vmethod_122().TabIndex = 8;
			this.vmethod_122().Text = "Detector Side:";
			this.vmethod_118().method_0(null);
			this.vmethod_118().Location = new global::System.Drawing.Point(6, 6);
			this.vmethod_118().MinimumSize = new global::System.Drawing.Size(311, 177);
			this.vmethod_118().Name = "UnitFilter_UnitDetected";
			this.vmethod_118().Size = new global::System.Drawing.Size(311, 177);
			this.vmethod_118().TabIndex = 6;
			this.vmethod_128().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_128().Controls.Add(this.vmethod_130());
			this.vmethod_128().Controls.Add(this.vmethod_132());
			this.vmethod_128().Location = new global::System.Drawing.Point(4, 23);
			this.vmethod_128().Name = "TabPage9";
			this.vmethod_128().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_128().Size = new global::System.Drawing.Size(744, 310);
			this.vmethod_128().TabIndex = 8;
			this.vmethod_128().Text = "Regular Time";
			this.vmethod_130().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_130().FormattingEnabled = true;
			this.vmethod_130().Items.AddRange(new object[]
			{
				"1秒",
				"5秒",
				"15秒",
				"30秒",
				"1分钟",
				"5分钟",
				"15分钟",
				"30分钟",
				"1小时"
			});
			this.vmethod_130().Location = new global::System.Drawing.Point(227, 98);
			this.vmethod_130().Name = "CB_RegularTimeInterval";
			this.vmethod_130().Size = new global::System.Drawing.Size(155, 21);
			this.vmethod_130().TabIndex = 1;
			this.vmethod_132().Location = new global::System.Drawing.Point(115, 101);
			this.vmethod_132().Name = "Label17";
			this.vmethod_132().Size = new global::System.Drawing.Size(106, 13);
			this.vmethod_132().TabIndex = 0;
			this.vmethod_132().Text = "Trigger will fire every:";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(747, 428);
			base.Controls.Add(this.vmethod_12());
			base.Controls.Add(this.vmethod_8());
			base.Controls.Add(this.vmethod_6());
			base.Controls.Add(this.vmethod_4());
			base.Controls.Add(this.vmethod_2());
			base.Controls.Add(this.vmethod_0());
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "EditTrigger";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "编辑事件触发器";
			this.vmethod_10().ResumeLayout(false);
			this.vmethod_12().ResumeLayout(false);
			this.vmethod_16().ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_44()).EndInit();
			this.vmethod_18().ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_26()).EndInit();
			this.vmethod_34().ResumeLayout(false);
			this.vmethod_34().PerformLayout();
			this.vmethod_48().ResumeLayout(false);
			this.vmethod_54().ResumeLayout(false);
			this.vmethod_54().PerformLayout();
			this.vmethod_72().ResumeLayout(false);
			this.vmethod_72().PerformLayout();
			this.vmethod_74().ResumeLayout(false);
			this.vmethod_98().ResumeLayout(false);
			this.vmethod_98().PerformLayout();
			this.vmethod_116().ResumeLayout(false);
			this.vmethod_128().ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04001D01 RID: 7425
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
