namespace ns33
{
	// Token: 0x02000A27 RID: 2599
	
	public sealed partial class FlightPlanEditor : global::ns33.CommandForm
	{
		// Token: 0x060050F8 RID: 20728 RVA: 0x0020EB38 File Offset: 0x0020CD38
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060050F9 RID: 20729 RVA: 0x0020EB7C File Offset: 0x0020CD7C
		private void InitializeComponent()
		{
			this.SetTabControl_Aircraft(new global::System.Windows.Forms.TabControl());
			this.vmethod_3(new global::System.Windows.Forms.TabPage());
			this.vmethod_49(new global::ns32.FlightPlanWaypoints());
			this.vmethod_5(new global::System.Windows.Forms.TabPage());
			this.vmethod_53(new global::ns32.FlightPlanWaypoints());
			this.vmethod_7(new global::System.Windows.Forms.TabPage());
			this.vmethod_55(new global::ns32.FlightPlanWaypoints());
			this.vmethod_9(new global::System.Windows.Forms.TabPage());
			this.vmethod_57(new global::ns32.FlightPlanWaypoints());
			this.vmethod_11(new global::System.Windows.Forms.TabPage());
			this.vmethod_59(new global::ns32.FlightPlanWaypoints());
			this.vmethod_13(new global::System.Windows.Forms.TabPage());
			this.vmethod_61(new global::ns32.FlightPlanWaypoints());
			this.vmethod_15(new global::System.Windows.Forms.Label());
			this.vmethod_17(new global::System.Windows.Forms.Label());
			this.vmethod_19(new global::System.Windows.Forms.Label());
			this.vmethod_21(new global::System.Windows.Forms.Label());
			this.SetCombo_CurrentPackage(new global::System.Windows.Forms.ComboBox());
			this.SetCombo_CurrentFlightPlan(new global::System.Windows.Forms.ComboBox());
			this.SetCombo_FlightTask(new global::System.Windows.Forms.ComboBox());
			this.SetTextBox_FlightCallsign(new global::System.Windows.Forms.TextBox());
			this.SetButton_CreateCopy(new global::System.Windows.Forms.Button());
			this.SetButton_Reset(new global::System.Windows.Forms.Button());
			this.vmethod_35(new global::System.Windows.Forms.Label());
			this.vmethod_37(new global::System.Windows.Forms.CheckBox());
			this.vmethod_39(new global::System.Windows.Forms.CheckBox());
			this.vmethod_41(new global::System.Windows.Forms.ComboBox());
			this.vmethod_43(new global::System.Windows.Forms.Label());
			this.vmethod_45(new global::System.Windows.Forms.ComboBox());
			this.vmethod_47(new global::System.Windows.Forms.Label());
			this.vmethod_51(new global::System.Windows.Forms.Label());
			this.GetTabControl_Aircraft().SuspendLayout();
			this.GetTabPage1().SuspendLayout();
			this.GetTabPage2().SuspendLayout();
			this.GetTabPage3().SuspendLayout();
			this.GetTabPage4().SuspendLayout();
			this.GetTabPage5().SuspendLayout();
			this.GetTabPage6().SuspendLayout();
			base.SuspendLayout();
			this.GetTabControl_Aircraft().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetTabControl_Aircraft().Controls.Add(this.GetTabPage1());
			this.GetTabControl_Aircraft().Controls.Add(this.GetTabPage2());
			this.GetTabControl_Aircraft().Controls.Add(this.GetTabPage3());
			this.GetTabControl_Aircraft().Controls.Add(this.GetTabPage4());
			this.GetTabControl_Aircraft().Controls.Add(this.GetTabPage5());
			this.GetTabControl_Aircraft().Controls.Add(this.GetTabPage6());
			this.GetTabControl_Aircraft().Location = new global::System.Drawing.Point(0, 189);
			this.GetTabControl_Aircraft().Name = "TabControl_Aircraft";
			this.GetTabControl_Aircraft().SelectedIndex = 0;
			this.GetTabControl_Aircraft().Size = new global::System.Drawing.Size(500, 502);
			this.GetTabControl_Aircraft().TabIndex = 10;
			this.GetTabPage1().Controls.Add(this.GetFlightPlanWaypoints1());
			this.GetTabPage1().Location = new global::System.Drawing.Point(4, 22);
			this.GetTabPage1().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetTabPage1().Name = "TabPage1";
			this.GetTabPage1().Size = new global::System.Drawing.Size(492, 476);
			this.GetTabPage1().TabIndex = 0;
			this.GetTabPage1().Text = "飞机 #1";
			this.GetTabPage1().UseVisualStyleBackColor = true;
			this.GetFlightPlanWaypoints1().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetFlightPlanWaypoints1().Location = new global::System.Drawing.Point(0, 0);
			this.GetFlightPlanWaypoints1().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlightPlanWaypoints1().Name = "FlightPlanWaypoints1";
			this.GetFlightPlanWaypoints1().Size = new global::System.Drawing.Size(492, 476);
			this.GetFlightPlanWaypoints1().TabIndex = 0;
			this.GetTabPage2().Controls.Add(this.GetFlightPlanWaypoints2());
			this.GetTabPage2().Location = new global::System.Drawing.Point(4, 22);
			this.GetTabPage2().Name = "TabPage2";
			this.GetTabPage2().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTabPage2().Size = new global::System.Drawing.Size(492, 476);
			this.GetTabPage2().TabIndex = 1;
			this.GetTabPage2().Text = "#2";
			this.GetTabPage2().UseVisualStyleBackColor = true;
			this.GetFlightPlanWaypoints2().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetFlightPlanWaypoints2().Location = new global::System.Drawing.Point(3, 3);
			this.GetFlightPlanWaypoints2().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlightPlanWaypoints2().Name = "FlightPlanWaypoints2";
			this.GetFlightPlanWaypoints2().Size = new global::System.Drawing.Size(486, 470);
			this.GetFlightPlanWaypoints2().TabIndex = 1;
			this.GetTabPage3().Controls.Add(this.GetFlightPlanWaypoints3());
			this.GetTabPage3().Location = new global::System.Drawing.Point(4, 22);
			this.GetTabPage3().Name = "TabPage3";
			this.GetTabPage3().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTabPage3().Size = new global::System.Drawing.Size(492, 476);
			this.GetTabPage3().TabIndex = 2;
			this.GetTabPage3().Text = "#3";
			this.GetTabPage3().UseVisualStyleBackColor = true;
			this.GetFlightPlanWaypoints3().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetFlightPlanWaypoints3().Location = new global::System.Drawing.Point(3, 3);
			this.GetFlightPlanWaypoints3().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlightPlanWaypoints3().Name = "FlightPlanWaypoints3";
			this.GetFlightPlanWaypoints3().Size = new global::System.Drawing.Size(486, 470);
			this.GetFlightPlanWaypoints3().TabIndex = 2;
			this.GetTabPage4().Controls.Add(this.GetFlightPlanWaypoints4());
			this.GetTabPage4().Location = new global::System.Drawing.Point(4, 22);
			this.GetTabPage4().Name = "TabPage4";
			this.GetTabPage4().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTabPage4().Size = new global::System.Drawing.Size(492, 476);
			this.GetTabPage4().TabIndex = 3;
			this.GetTabPage4().Text = "#4";
			this.GetTabPage4().UseVisualStyleBackColor = true;
			this.GetFlightPlanWaypoints4().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetFlightPlanWaypoints4().Location = new global::System.Drawing.Point(3, 3);
			this.GetFlightPlanWaypoints4().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlightPlanWaypoints4().Name = "FlightPlanWaypoints4";
			this.GetFlightPlanWaypoints4().Size = new global::System.Drawing.Size(486, 470);
			this.GetFlightPlanWaypoints4().TabIndex = 2;
			this.GetTabPage5().Controls.Add(this.GetFlightPlanWaypoints5());
			this.GetTabPage5().Location = new global::System.Drawing.Point(4, 22);
			this.GetTabPage5().Name = "TabPage5";
			this.GetTabPage5().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTabPage5().Size = new global::System.Drawing.Size(492, 476);
			this.GetTabPage5().TabIndex = 4;
			this.GetTabPage5().Text = "#5";
			this.GetTabPage5().UseVisualStyleBackColor = true;
			this.GetFlightPlanWaypoints5().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetFlightPlanWaypoints5().Location = new global::System.Drawing.Point(3, 3);
			this.GetFlightPlanWaypoints5().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlightPlanWaypoints5().Name = "FlightPlanWaypoints5";
			this.GetFlightPlanWaypoints5().Size = new global::System.Drawing.Size(486, 470);
			this.GetFlightPlanWaypoints5().TabIndex = 2;
			this.GetTabPage6().Controls.Add(this.GetFlightPlanWaypoints6());
			this.GetTabPage6().Location = new global::System.Drawing.Point(4, 22);
			this.GetTabPage6().Name = "TabPage6";
			this.GetTabPage6().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTabPage6().Size = new global::System.Drawing.Size(492, 476);
			this.GetTabPage6().TabIndex = 5;
			this.GetTabPage6().Text = "#6";
			this.GetTabPage6().UseVisualStyleBackColor = true;
			this.GetFlightPlanWaypoints6().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetFlightPlanWaypoints6().Location = new global::System.Drawing.Point(3, 3);
			this.GetFlightPlanWaypoints6().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlightPlanWaypoints6().Name = "FlightPlanWaypoints6";
			this.GetFlightPlanWaypoints6().Size = new global::System.Drawing.Size(486, 470);
			this.GetFlightPlanWaypoints6().TabIndex = 2;
			this.vmethod_14().AutoSize = true;
			this.vmethod_14().Location = new global::System.Drawing.Point(14, 20);
			this.vmethod_14().Name = "Label1";
			this.vmethod_14().Size = new global::System.Drawing.Size(53, 13);
			this.vmethod_14().TabIndex = 11;
			this.vmethod_14().Text = "任务（Task）包:";
			this.vmethod_16().AutoSize = true;
			this.vmethod_16().Location = new global::System.Drawing.Point(14, 45);
			this.vmethod_16().Name = "Label2";
			this.vmethod_16().Size = new global::System.Drawing.Size(35, 13);
			this.vmethod_16().TabIndex = 11;
			this.vmethod_16().Text = "航线:";
			this.vmethod_18().AutoSize = true;
			this.vmethod_18().Location = new global::System.Drawing.Point(14, 68);
			this.vmethod_18().Name = "Label3";
			this.vmethod_18().Size = new global::System.Drawing.Size(46, 13);
			this.vmethod_18().TabIndex = 11;
			this.vmethod_18().Text = "呼号:";
			this.vmethod_20().AutoSize = true;
			this.vmethod_20().Location = new global::System.Drawing.Point(14, 95);
			this.vmethod_20().Name = "Label4";
			this.vmethod_20().Size = new global::System.Drawing.Size(34, 13);
			this.vmethod_20().TabIndex = 11;
			this.vmethod_20().Text = "任务:";
			this.GetCombo_CurrentPackage().FormattingEnabled = true;
			this.GetCombo_CurrentPackage().Location = new global::System.Drawing.Point(106, 20);
			this.GetCombo_CurrentPackage().Name = "Combo_CurrentPackage";
			this.GetCombo_CurrentPackage().Size = new global::System.Drawing.Size(121, 21);
			this.GetCombo_CurrentPackage().TabIndex = 12;
			this.GetCombo_CurrentFlightPlan().FormattingEnabled = true;
			this.GetCombo_CurrentFlightPlan().Location = new global::System.Drawing.Point(106, 45);
			this.GetCombo_CurrentFlightPlan().Name = "Combo_CurrentFlightPlan";
			this.GetCombo_CurrentFlightPlan().Size = new global::System.Drawing.Size(121, 21);
			this.GetCombo_CurrentFlightPlan().TabIndex = 12;
			this.GetCombo_FlightTask().FormattingEnabled = true;
			this.GetCombo_FlightTask().Location = new global::System.Drawing.Point(106, 93);
			this.GetCombo_FlightTask().Name = "Combo_FlightTask";
			this.GetCombo_FlightTask().Size = new global::System.Drawing.Size(121, 21);
			this.GetCombo_FlightTask().TabIndex = 12;
			this.GetTextBox_FlightCallsign().Location = new global::System.Drawing.Point(107, 71);
			this.GetTextBox_FlightCallsign().Name = "TextBox_FlightCallsign";
			this.GetTextBox_FlightCallsign().Size = new global::System.Drawing.Size(100, 20);
			this.GetTextBox_FlightCallsign().TabIndex = 13;
			this.GetButton_CreateCopy().Location = new global::System.Drawing.Point(333, 25);
			this.GetButton_CreateCopy().Name = "Button_CreateCopy";
			this.GetButton_CreateCopy().Size = new global::System.Drawing.Size(129, 21);
			this.GetButton_CreateCopy().TabIndex = 14;
			this.GetButton_CreateCopy().Text = "创建副本";
			this.GetButton_CreateCopy().UseVisualStyleBackColor = true;
			this.GetButton_Reset().Location = new global::System.Drawing.Point(333, 52);
			this.GetButton_Reset().Name = "Button_Reset";
			this.GetButton_Reset().Size = new global::System.Drawing.Size(129, 21);
			this.GetButton_Reset().TabIndex = 15;
			this.GetButton_Reset().Text = "重置";
			this.GetButton_Reset().UseVisualStyleBackColor = true;
			this.GetLabel_FlightDate().AutoSize = true;
			this.GetLabel_FlightDate().Location = new global::System.Drawing.Point(287, 128);
			this.GetLabel_FlightDate().Name = "Label_FlightDate";
			this.GetLabel_FlightDate().Size = new global::System.Drawing.Size(95, 13);
			this.GetLabel_FlightDate().TabIndex = 16;
			this.GetLabel_FlightDate().Text = "日期: <Whatever>";
			this.GetCheckBox_OneTimeOnly().AutoSize = true;
			this.GetCheckBox_OneTimeOnly().Location = new global::System.Drawing.Point(240, 56);
			this.GetCheckBox_OneTimeOnly().Name = "CheckBox_OneTimeOnly";
			this.GetCheckBox_OneTimeOnly().Size = new global::System.Drawing.Size(96, 17);
			this.GetCheckBox_OneTimeOnly().TabIndex = 17;
			this.GetCheckBox_OneTimeOnly().Text = "仅执行一次";
			this.GetCheckBox_OneTimeOnly().UseVisualStyleBackColor = true;
			this.GetCheckBox_TimeBound().AutoSize = true;
			this.GetCheckBox_TimeBound().Location = new global::System.Drawing.Point(240, 33);
			this.GetCheckBox_TimeBound().Name = "CheckBox_TimeBound";
			this.GetCheckBox_TimeBound().Size = new global::System.Drawing.Size(83, 17);
			this.GetCheckBox_TimeBound().TabIndex = 18;
			this.GetCheckBox_TimeBound().Text = "时限";
			this.GetCheckBox_TimeBound().UseVisualStyleBackColor = true;
			this.GetCombo_AircraftType().FormattingEnabled = true;
			this.GetCombo_AircraftType().Location = new global::System.Drawing.Point(106, 120);
			this.GetCombo_AircraftType().Name = "Combo_AircraftType";
			this.GetCombo_AircraftType().Size = new global::System.Drawing.Size(121, 21);
			this.GetCombo_AircraftType().TabIndex = 20;
			this.vmethod_42().AutoSize = true;
			this.vmethod_42().Location = new global::System.Drawing.Point(14, 122);
			this.vmethod_42().Name = "Label6";
			this.vmethod_42().Size = new global::System.Drawing.Size(43, 13);
			this.vmethod_42().TabIndex = 19;
			this.vmethod_42().Text = "飞机:";
			this.GetComboBox_Loadout().FormattingEnabled = true;
			this.GetComboBox_Loadout().Location = new global::System.Drawing.Point(106, 147);
			this.GetComboBox_Loadout().Name = "ComboBox_Loadout";
			this.GetComboBox_Loadout().Size = new global::System.Drawing.Size(121, 21);
			this.GetComboBox_Loadout().TabIndex = 22;
			this.vmethod_46().AutoSize = true;
			this.vmethod_46().Location = new global::System.Drawing.Point(14, 149);
			this.vmethod_46().Name = "Label7";
			this.vmethod_46().Size = new global::System.Drawing.Size(49, 13);
			this.vmethod_46().TabIndex = 21;
			this.vmethod_46().Text = "挂载:";
			this.vmethod_50().AutoSize = true;
			this.vmethod_50().Location = new global::System.Drawing.Point(253, 128);
			this.vmethod_50().Name = "Label5";
			this.vmethod_50().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_50().TabIndex = 23;
			this.vmethod_50().Text = "日期:";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(499, 691);
			base.Controls.Add(this.vmethod_50());
			base.Controls.Add(this.GetComboBox_Loadout());
			base.Controls.Add(this.vmethod_46());
			base.Controls.Add(this.GetCombo_AircraftType());
			base.Controls.Add(this.vmethod_42());
			base.Controls.Add(this.GetCheckBox_TimeBound());
			base.Controls.Add(this.GetCheckBox_OneTimeOnly());
			base.Controls.Add(this.GetLabel_FlightDate());
			base.Controls.Add(this.GetButton_Reset());
			base.Controls.Add(this.GetButton_CreateCopy());
			base.Controls.Add(this.GetTextBox_FlightCallsign());
			base.Controls.Add(this.GetCombo_FlightTask());
			base.Controls.Add(this.GetCombo_CurrentFlightPlan());
			base.Controls.Add(this.GetCombo_CurrentPackage());
			base.Controls.Add(this.vmethod_20());
			base.Controls.Add(this.vmethod_18());
			base.Controls.Add(this.vmethod_16());
			base.Controls.Add(this.vmethod_14());
			base.Controls.Add(this.GetTabControl_Aircraft());
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "FlightPlanEditor";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "飞行计划编辑器";
			this.GetTabControl_Aircraft().ResumeLayout(false);
			this.GetTabPage1().ResumeLayout(false);
			this.GetTabPage2().ResumeLayout(false);
			this.GetTabPage3().ResumeLayout(false);
			this.GetTabPage4().ResumeLayout(false);
			this.GetTabPage5().ResumeLayout(false);
			this.GetTabPage6().ResumeLayout(false);
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x04002611 RID: 9745
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
