namespace Command
{
	// Token: 0x02000AEA RID: 2794

	public sealed partial class AttackTarget : global::ns33.CommandForm
	{
		// Token: 0x060059A4 RID: 22948 RVA: 0x0027AB18 File Offset: 0x00278D18
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool flag)
		{
			try
			{
				if (flag && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(flag);
			}
		}

		// Token: 0x060059A5 RID: 22949 RVA: 0x0027AB5C File Offset: 0x00278D5C
		private void InitializeComponent()
		{
			this.icontainer_0 = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Command.AttackTarget));
			this.vmethod_17(new global::System.Windows.Forms.Timer(this.icontainer_0));
			this.vmethod_61(new global::System.Windows.Forms.TableLayoutPanel());
			this.vmethod_63(new global::System.Windows.Forms.Panel());
			this.SetButton_RemoveAttacker(new global::System.Windows.Forms.Button());
			this.vmethod_31(new global::System.Windows.Forms.Label());
			this.vmethod_33(new global::System.Windows.Forms.ListBox());
			this.vmethod_45(new global::System.Windows.Forms.Button());
			this.vmethod_47(new global::System.Windows.Forms.Button());
			this.vmethod_65(new global::System.Windows.Forms.Panel());
			this.vmethod_75(new global::System.Windows.Forms.CheckBox());
			this.vmethod_73(new global::System.Windows.Forms.CheckBox());
			this.SetButton_AllocateSalvo(new global::System.Windows.Forms.Button());
			this.vmethod_41(new global::System.Windows.Forms.Button());
			this.vmethod_35(new global::System.Windows.Forms.Label());
			this.vmethod_39(new global::System.Windows.Forms.Button());
			this.vmethod_43(new global::System.Windows.Forms.NumericUpDown());
			this.SetTV_AvailableWeapons(new global::System.Windows.Forms.TreeView());
			this.vmethod_67(new global::System.Windows.Forms.Panel());
			this.vmethod_77(new global::System.Windows.Forms.Button());
			this.vmethod_79(new global::System.Windows.Forms.Button());
			this.SetButton_RemoveWeapons_Attacker(new global::System.Windows.Forms.Button());
			this.vmethod_21(new global::System.Windows.Forms.TabControl());
			this.vmethod_23(new global::System.Windows.Forms.TabPage());
			this.vmethod_25(new global::System.Windows.Forms.TreeView());
			this.vmethod_27(new global::System.Windows.Forms.TabPage());
			this.vmethod_29(new global::System.Windows.Forms.TreeView());
			this.vmethod_19(new global::System.Windows.Forms.Label());
			this.vmethod_69(new global::System.Windows.Forms.Panel());
			this.vmethod_81(new global::System.Windows.Forms.Button());
			this.SetButton_RemoveWeapons_Target(new global::System.Windows.Forms.Button());
			this.SetButton_PlotCourse_Target(new global::System.Windows.Forms.Button());
			this.vmethod_5(new global::System.Windows.Forms.TabControl());
			this.vmethod_7(new global::System.Windows.Forms.TabPage());
			this.SetTV_Allocations_ByAttackersOnly(new global::System.Windows.Forms.TreeView());
			this.vmethod_9(new global::System.Windows.Forms.TabPage());
			this.SetTV_Allocations_ByAnyone(new global::System.Windows.Forms.TreeView());
			this.vmethod_3(new global::System.Windows.Forms.Label());
			this.vmethod_71(new global::System.Windows.Forms.Panel());
			this.vmethod_53(new global::System.Windows.Forms.Button());
			this.vmethod_49(new global::System.Windows.Forms.Button());
			this.vmethod_11(new global::System.Windows.Forms.ListBox());
			this.vmethod_1(new global::System.Windows.Forms.Label());
			this.vmethod_85(new global::System.Windows.Forms.ContextMenuStrip(this.icontainer_0));
			this.SetTSMI_HighAltitudeDetonation(new global::System.Windows.Forms.ToolStripMenuItem());
			this.vmethod_60().SuspendLayout();
			this.vmethod_62().SuspendLayout();
			this.vmethod_64().SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GetNUD_NumberOfWeapons()).BeginInit();
			this.vmethod_66().SuspendLayout();
			this.vmethod_20().SuspendLayout();
			this.GetTab_Attacker_ToSelectedOnly().SuspendLayout();
			this.GetTab_Attacker_ToAnyone().SuspendLayout();
			this.vmethod_68().SuspendLayout();
			this.vmethod_4().SuspendLayout();
			this.GetTab_Target_BySelected().SuspendLayout();
			this.GetTab_Target_ByAnyone().SuspendLayout();
			this.vmethod_70().SuspendLayout();
			this.vmethod_84().SuspendLayout();
			base.SuspendLayout();
			this.vmethod_60().ColumnCount = 3;
			this.vmethod_60().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 32f));
			this.vmethod_60().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 36f));
			this.vmethod_60().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 32f));
			this.vmethod_60().Controls.Add(this.vmethod_62(), 0, 0);
			this.vmethod_60().Controls.Add(this.vmethod_64(), 1, 0);
			this.vmethod_60().Controls.Add(this.vmethod_66(), 2, 0);
			this.vmethod_60().Controls.Add(this.vmethod_68(), 2, 1);
			this.vmethod_60().Controls.Add(this.vmethod_70(), 0, 1);
			this.vmethod_60().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_60().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_60().Name = "TableLayoutPanel1";
			this.vmethod_60().RowCount = 2;
			this.vmethod_60().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.vmethod_60().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.vmethod_60().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 20f));
			this.vmethod_60().Size = new global::System.Drawing.Size(1008, 661);
			this.vmethod_60().TabIndex = 17;
			this.vmethod_62().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_62().Controls.Add(this.GetButton_RemoveAttacker());
			this.vmethod_62().Controls.Add(this.vmethod_30());
			this.vmethod_62().Controls.Add(this.vmethod_32());
			this.vmethod_62().Controls.Add(this.GetButton_UnitWRA());
			this.vmethod_62().Controls.Add(this.GetButton_AddAttacker());
			this.vmethod_62().Location = new global::System.Drawing.Point(3, 3);
			this.vmethod_62().Name = "Panel1";
			this.vmethod_62().Size = new global::System.Drawing.Size(316, 324);
			this.vmethod_62().TabIndex = 0;
			this.GetButton_RemoveAttacker().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_RemoveAttacker().Location = new global::System.Drawing.Point(-1, 302);
			this.GetButton_RemoveAttacker().Name = "Button_RemoveAttacker";
			this.GetButton_RemoveAttacker().Size = new global::System.Drawing.Size(317, 23);
			this.GetButton_RemoveAttacker().TabIndex = 11;
			this.GetButton_RemoveAttacker().Text = "从列表中删除所选单元";
			this.GetButton_RemoveAttacker().UseVisualStyleBackColor = true;
			this.vmethod_30().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_30().AutoSize = true;
			this.vmethod_30().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.vmethod_30().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_30().Name = "Label1";
			this.vmethod_30().Size = new global::System.Drawing.Size(124, 20);
			this.vmethod_30().TabIndex = 1;
			this.vmethod_30().Text = "打击平台";
			this.vmethod_32().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_32().DisplayMember = "Text";
			this.vmethod_32().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.vmethod_32().FormattingEnabled = true;
			this.vmethod_32().IntegralHeight = false;
			this.vmethod_32().ItemHeight = 15;
			this.vmethod_32().Location = new global::System.Drawing.Point(0, 25);
			this.vmethod_32().Name = "LB_Attackers";
			this.vmethod_32().SelectionMode = global::System.Windows.Forms.SelectionMode.MultiExtended;
			this.vmethod_32().Size = new global::System.Drawing.Size(315, 230);
			this.vmethod_32().TabIndex = 2;
			this.GetButton_UnitWRA().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_UnitWRA().Location = new global::System.Drawing.Point(-1, 256);
			this.GetButton_UnitWRA().Name = "Button_UnitWRA";
			this.GetButton_UnitWRA().Size = new global::System.Drawing.Size(317, 23);
			this.GetButton_UnitWRA().TabIndex = 8;
			this.GetButton_UnitWRA().Text = "武器使用规则";
			this.GetButton_UnitWRA().UseVisualStyleBackColor = true;
			this.GetButton_AddAttacker().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_AddAttacker().Location = new global::System.Drawing.Point(-1, 279);
			this.GetButton_AddAttacker().Name = "Button_AddAttacker";
			this.GetButton_AddAttacker().Size = new global::System.Drawing.Size(317, 23);
			this.GetButton_AddAttacker().TabIndex = 9;
			this.GetButton_AddAttacker().Text = "从战术地图添加所选单元";
			this.GetButton_AddAttacker().UseVisualStyleBackColor = true;
			this.vmethod_64().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_64().Controls.Add(this.GetCB_ShowAutomaticFireInfo());
			this.vmethod_64().Controls.Add(this.GetCB_AllowTimeout());
			this.vmethod_64().Controls.Add(this.GetButton_AllocateSalvo());
			this.vmethod_64().Controls.Add(this.GetButton_AllocateAllWeapons());
			this.vmethod_64().Controls.Add(this.vmethod_34());
			this.vmethod_64().Controls.Add(this.GetButton_Allocate());
			this.vmethod_64().Controls.Add(this.GetNUD_NumberOfWeapons());
			this.vmethod_64().Controls.Add(this.GetTV_AvailableWeapons());
			this.vmethod_64().Location = new global::System.Drawing.Point(325, 3);
			this.vmethod_64().Name = "Panel2";
			this.vmethod_60().SetRowSpan(this.vmethod_64(), 2);
			this.vmethod_64().Size = new global::System.Drawing.Size(356, 655);
			this.vmethod_64().TabIndex = 1;
			this.GetCB_ShowAutomaticFireInfo().AutoSize = true;
			this.GetCB_ShowAutomaticFireInfo().Location = new global::System.Drawing.Point(175, 8);
			this.GetCB_ShowAutomaticFireInfo().Name = "CB_ShowAutomaticFireInfo";
			this.GetCB_ShowAutomaticFireInfo().Size = new global::System.Drawing.Size(178, 17);
			this.GetCB_ShowAutomaticFireInfo().TabIndex = 15;
			this.GetCB_ShowAutomaticFireInfo().Text = "显示自动开火信息";
			this.GetCB_ShowAutomaticFireInfo().UseVisualStyleBackColor = true;
			this.GetCB_AllowTimeout().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetCB_AllowTimeout().AutoSize = true;
			this.GetCB_AllowTimeout().Location = new global::System.Drawing.Point(4, 581);
			this.GetCB_AllowTimeout().MaximumSize = new global::System.Drawing.Size(400, 0);
			this.GetCB_AllowTimeout().MinimumSize = new global::System.Drawing.Size(0, 80);
			this.GetCB_AllowTimeout().Name = "CB_AllowTimeout";
			this.GetCB_AllowTimeout().Size = new global::System.Drawing.Size(400, 80);
			this.GetCB_AllowTimeout().TabIndex = 14;
			this.GetCB_AllowTimeout().Text = componentResourceManager.GetString("CB_AllowTimeout.Text");
			this.GetCB_AllowTimeout().TextAlign = global::System.Drawing.ContentAlignment.TopLeft;
			this.GetCB_AllowTimeout().UseVisualStyleBackColor = true;
			this.GetButton_AllocateSalvo().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_AllocateSalvo().Location = new global::System.Drawing.Point(-1, 531);
			this.GetButton_AllocateSalvo().Name = "Button_AllocateSalvo";
			this.GetButton_AllocateSalvo().Size = new global::System.Drawing.Size(357, 23);
			this.GetButton_AllocateSalvo().TabIndex = 13;
			this.GetButton_AllocateSalvo().Text = "为所选目标分配一次齐射";
			this.GetButton_AllocateSalvo().UseVisualStyleBackColor = true;
			this.GetButton_AllocateAllWeapons().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_AllocateAllWeapons().Location = new global::System.Drawing.Point(-1, 554);
			this.GetButton_AllocateAllWeapons().Name = "Button_AllocateAllWeapons";
			this.GetButton_AllocateAllWeapons().Size = new global::System.Drawing.Size(357, 23);
			this.GetButton_AllocateAllWeapons().TabIndex = 6;
			this.GetButton_AllocateAllWeapons().Text = "分配本类型所有武器";
			this.GetButton_AllocateAllWeapons().UseVisualStyleBackColor = true;
			this.vmethod_34().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_34().AutoSize = true;
			this.vmethod_34().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.vmethod_34().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_34().Name = "Label5";
			this.vmethod_34().Size = new global::System.Drawing.Size(135, 20);
			this.vmethod_34().TabIndex = 3;
			this.vmethod_34().Text = "可用武器清单";
			this.GetButton_Allocate().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_Allocate().Location = new global::System.Drawing.Point(-1, 508);
			this.GetButton_Allocate().Name = "Button_Allocate";
			this.GetButton_Allocate().Size = new global::System.Drawing.Size(279, 23);
			this.GetButton_Allocate().TabIndex = 5;
			this.GetButton_Allocate().Text = "为所选目标分配武器:";
			this.GetButton_Allocate().UseVisualStyleBackColor = true;
			this.GetNUD_NumberOfWeapons().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetNUD_NumberOfWeapons().Location = new global::System.Drawing.Point(280, 510);
			this.GetNUD_NumberOfWeapons().Name = "NUD_NumberOfWeapons";
			this.GetNUD_NumberOfWeapons().Size = new global::System.Drawing.Size(75, 20);
			this.GetNUD_NumberOfWeapons().TabIndex = 7;
			this.GetTV_AvailableWeapons().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetTV_AvailableWeapons().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.GetTV_AvailableWeapons().Location = new global::System.Drawing.Point(0, 25);
			this.GetTV_AvailableWeapons().Name = "TV_AvailableWeapons";
			this.GetTV_AvailableWeapons().Size = new global::System.Drawing.Size(355, 482);
			this.GetTV_AvailableWeapons().TabIndex = 4;
			this.vmethod_66().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_66().Controls.Add(this.GetButton_ClearCourse_Attacker());
			this.vmethod_66().Controls.Add(this.GetButton_PlotCourse_Attacker());
			this.vmethod_66().Controls.Add(this.GetButton_RemoveWeapons_Attacker());
			this.vmethod_66().Controls.Add(this.vmethod_20());
			this.vmethod_66().Controls.Add(this.vmethod_18());
			this.vmethod_66().Location = new global::System.Drawing.Point(687, 3);
			this.vmethod_66().Name = "Panel3";
			this.vmethod_66().Size = new global::System.Drawing.Size(318, 324);
			this.vmethod_66().TabIndex = 2;
			this.GetButton_ClearCourse_Attacker().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ClearCourse_Attacker().Location = new global::System.Drawing.Point(83, 302);
			this.GetButton_ClearCourse_Attacker().Name = "Button_ClearCourse_Attacker";
			this.GetButton_ClearCourse_Attacker().Size = new global::System.Drawing.Size(76, 23);
			this.GetButton_ClearCourse_Attacker().TabIndex = 17;
			this.GetButton_ClearCourse_Attacker().Text = "清除航线";
			this.GetButton_ClearCourse_Attacker().UseVisualStyleBackColor = true;
			this.GetButton_PlotCourse_Attacker().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_PlotCourse_Attacker().Location = new global::System.Drawing.Point(4, 302);
			this.GetButton_PlotCourse_Attacker().Name = "Button_PlotCourse_Attacker";
			this.GetButton_PlotCourse_Attacker().Size = new global::System.Drawing.Size(73, 23);
			this.GetButton_PlotCourse_Attacker().TabIndex = 16;
			this.GetButton_PlotCourse_Attacker().Text = "绘制航线";
			this.GetButton_PlotCourse_Attacker().UseVisualStyleBackColor = true;
			this.GetButton_RemoveWeapons_Attacker().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_RemoveWeapons_Attacker().Location = new global::System.Drawing.Point(207, 302);
			this.GetButton_RemoveWeapons_Attacker().Name = "Button_RemoveWeapons_Attacker";
			this.GetButton_RemoveWeapons_Attacker().Size = new global::System.Drawing.Size(112, 23);
			this.GetButton_RemoveWeapons_Attacker().TabIndex = 15;
			this.GetButton_RemoveWeapons_Attacker().Text = "取消所选单元的分配目标";
			this.GetButton_RemoveWeapons_Attacker().UseVisualStyleBackColor = true;
			this.vmethod_20().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_20().Controls.Add(this.GetTab_Attacker_ToSelectedOnly());
			this.vmethod_20().Controls.Add(this.GetTab_Attacker_ToAnyone());
			this.vmethod_20().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.vmethod_20().Location = new global::System.Drawing.Point(0, 25);
			this.vmethod_20().Name = "TabControl2";
			this.vmethod_20().SelectedIndex = 0;
			this.vmethod_20().Size = new global::System.Drawing.Size(318, 276);
			this.vmethod_20().TabIndex = 2;
			this.GetTab_Attacker_ToSelectedOnly().Controls.Add(this.GetTV_Allocations_ToTargetsOnly());
			this.GetTab_Attacker_ToSelectedOnly().Location = new global::System.Drawing.Point(4, 25);
			this.GetTab_Attacker_ToSelectedOnly().Name = "Tab_Attacker_ToSelectedOnly";
			this.GetTab_Attacker_ToSelectedOnly().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTab_Attacker_ToSelectedOnly().Size = new global::System.Drawing.Size(310, 247);
			this.GetTab_Attacker_ToSelectedOnly().TabIndex = 0;
			this.GetTab_Attacker_ToSelectedOnly().Text = "针对所选目标";
			this.GetTab_Attacker_ToSelectedOnly().UseVisualStyleBackColor = true;
			this.GetTV_Allocations_ToTargetsOnly().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetTV_Allocations_ToTargetsOnly().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.GetTV_Allocations_ToTargetsOnly().Location = new global::System.Drawing.Point(3, 3);
			this.GetTV_Allocations_ToTargetsOnly().Name = "TV_Allocations_ToTargetsOnly";
			this.GetTV_Allocations_ToTargetsOnly().Size = new global::System.Drawing.Size(304, 241);
			this.GetTV_Allocations_ToTargetsOnly().TabIndex = 5;
			this.GetTab_Attacker_ToAnyone().Controls.Add(this.GetTV_Allocations_ToAnyone());
			this.GetTab_Attacker_ToAnyone().Location = new global::System.Drawing.Point(4, 25);
			this.GetTab_Attacker_ToAnyone().Name = "Tab_Attacker_ToAnyone";
			this.GetTab_Attacker_ToAnyone().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTab_Attacker_ToAnyone().Size = new global::System.Drawing.Size(310, 247);
			this.GetTab_Attacker_ToAnyone().TabIndex = 1;
			this.GetTab_Attacker_ToAnyone().Text = "针对所有目标";
			this.GetTab_Attacker_ToAnyone().UseVisualStyleBackColor = true;
			this.GetTV_Allocations_ToAnyone().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetTV_Allocations_ToAnyone().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.GetTV_Allocations_ToAnyone().Location = new global::System.Drawing.Point(3, 3);
			this.GetTV_Allocations_ToAnyone().Name = "TV_Allocations_ToAnyone";
			this.GetTV_Allocations_ToAnyone().Size = new global::System.Drawing.Size(304, 241);
			this.GetTV_Allocations_ToAnyone().TabIndex = 6;
			this.vmethod_18().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_18().AutoSize = true;
			this.vmethod_18().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.vmethod_18().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_18().Name = "Label2";
			this.vmethod_18().Size = new global::System.Drawing.Size(309, 20);
			this.vmethod_18().TabIndex = 3;
			this.vmethod_18().Text = "所选打击平台分配的武器";
			this.vmethod_68().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_68().Controls.Add(this.GetButton_ClearCourse_Target());
			this.vmethod_68().Controls.Add(this.GetButton_RemoveWeapons_Target());
			this.vmethod_68().Controls.Add(this.GetButton_PlotCourse_Target());
			this.vmethod_68().Controls.Add(this.vmethod_4());
			this.vmethod_68().Controls.Add(this.vmethod_2());
			this.vmethod_68().Location = new global::System.Drawing.Point(687, 333);
			this.vmethod_68().Name = "Panel4";
			this.vmethod_68().Size = new global::System.Drawing.Size(318, 325);
			this.vmethod_68().TabIndex = 3;
			this.GetButton_ClearCourse_Target().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ClearCourse_Target().Location = new global::System.Drawing.Point(83, 302);
			this.GetButton_ClearCourse_Target().Name = "Button_ClearCourse_Target";
			this.GetButton_ClearCourse_Target().Size = new global::System.Drawing.Size(76, 23);
			this.GetButton_ClearCourse_Target().TabIndex = 19;
			this.GetButton_ClearCourse_Target().Text = "清空航线";
			this.GetButton_ClearCourse_Target().UseVisualStyleBackColor = true;
			this.GetButton_RemoveWeapons_Target().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_RemoveWeapons_Target().Location = new global::System.Drawing.Point(207, 303);
			this.GetButton_RemoveWeapons_Target().Name = "Button_RemoveWeapons_Target";
			this.GetButton_RemoveWeapons_Target().Size = new global::System.Drawing.Size(112, 23);
			this.GetButton_RemoveWeapons_Target().TabIndex = 14;
			this.GetButton_RemoveWeapons_Target().Text = "取消所选单元分配的目标";
			this.GetButton_RemoveWeapons_Target().UseVisualStyleBackColor = true;
			this.GetButton_PlotCourse_Target().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_PlotCourse_Target().Location = new global::System.Drawing.Point(4, 302);
			this.GetButton_PlotCourse_Target().Name = "Button_PlotCourse_Target";
			this.GetButton_PlotCourse_Target().Size = new global::System.Drawing.Size(73, 23);
			this.GetButton_PlotCourse_Target().TabIndex = 18;
			this.GetButton_PlotCourse_Target().Text = "绘制航线";
			this.GetButton_PlotCourse_Target().UseVisualStyleBackColor = true;
			this.vmethod_4().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_4().Controls.Add(this.GetTab_Target_BySelected());
			this.vmethod_4().Controls.Add(this.GetTab_Target_ByAnyone());
			this.vmethod_4().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10f);
			this.vmethod_4().Location = new global::System.Drawing.Point(0, 25);
			this.vmethod_4().Name = "TabControl4";
			this.vmethod_4().SelectedIndex = 0;
			this.vmethod_4().Size = new global::System.Drawing.Size(318, 277);
			this.vmethod_4().TabIndex = 2;
			this.GetTab_Target_BySelected().Controls.Add(this.GetTV_Allocations_ByAttackersOnly());
			this.GetTab_Target_BySelected().Location = new global::System.Drawing.Point(4, 25);
			this.GetTab_Target_BySelected().Name = "Tab_Target_BySelected";
			this.GetTab_Target_BySelected().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTab_Target_BySelected().Size = new global::System.Drawing.Size(310, 248);
			this.GetTab_Target_BySelected().TabIndex = 0;
			this.GetTab_Target_BySelected().Text = "所选打击平台";
			this.GetTab_Target_BySelected().UseVisualStyleBackColor = true;
			this.GetTV_Allocations_ByAttackersOnly().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetTV_Allocations_ByAttackersOnly().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.GetTV_Allocations_ByAttackersOnly().Location = new global::System.Drawing.Point(3, 3);
			this.GetTV_Allocations_ByAttackersOnly().Name = "TV_Allocations_ByAttackersOnly";
			this.GetTV_Allocations_ByAttackersOnly().Size = new global::System.Drawing.Size(304, 242);
			this.GetTV_Allocations_ByAttackersOnly().TabIndex = 6;
			this.GetTab_Target_ByAnyone().Controls.Add(this.GetTV_Allocations_ByAnyone());
			this.GetTab_Target_ByAnyone().Location = new global::System.Drawing.Point(4, 25);
			this.GetTab_Target_ByAnyone().Name = "Tab_Target_ByAnyone";
			this.GetTab_Target_ByAnyone().Padding = new global::System.Windows.Forms.Padding(3);
			this.GetTab_Target_ByAnyone().Size = new global::System.Drawing.Size(310, 248);
			this.GetTab_Target_ByAnyone().TabIndex = 1;
			this.GetTab_Target_ByAnyone().Text = "所有打击平台";
			this.GetTab_Target_ByAnyone().UseVisualStyleBackColor = true;
			this.GetTV_Allocations_ByAnyone().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetTV_Allocations_ByAnyone().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.GetTV_Allocations_ByAnyone().Location = new global::System.Drawing.Point(3, 3);
			this.GetTV_Allocations_ByAnyone().Name = "TV_Allocations_ByAnyone";
			this.GetTV_Allocations_ByAnyone().Size = new global::System.Drawing.Size(304, 242);
			this.GetTV_Allocations_ByAnyone().TabIndex = 7;
			this.vmethod_2().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_2().AutoSize = true;
			this.vmethod_2().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.vmethod_2().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_2().Name = "Label4";
			this.vmethod_2().Size = new global::System.Drawing.Size(273, 20);
			this.vmethod_2().TabIndex = 3;
			this.vmethod_2().Text = "为所选目标分配的武器";
			this.vmethod_70().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_70().Controls.Add(this.GetButton_RemoveTargets());
			this.vmethod_70().Controls.Add(this.GetButton_AddTarget());
			this.vmethod_70().Controls.Add(this.vmethod_10());
			this.vmethod_70().Controls.Add(this.vmethod_0());
			this.vmethod_70().Location = new global::System.Drawing.Point(3, 333);
			this.vmethod_70().Name = "Panel5";
			this.vmethod_70().Size = new global::System.Drawing.Size(316, 325);
			this.vmethod_70().TabIndex = 4;
			this.GetButton_RemoveTargets().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_RemoveTargets().Location = new global::System.Drawing.Point(-1, 303);
			this.GetButton_RemoveTargets().Name = "Button_RemoveTargets";
			this.GetButton_RemoveTargets().Size = new global::System.Drawing.Size(317, 23);
			this.GetButton_RemoveTargets().TabIndex = 12;
			this.GetButton_RemoveTargets().Text = "从列表中删除所选目标";
			this.GetButton_RemoveTargets().UseVisualStyleBackColor = true;
			this.GetButton_AddTarget().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_AddTarget().Location = new global::System.Drawing.Point(-1, 280);
			this.GetButton_AddTarget().Name = "Button_AddTarget";
			this.GetButton_AddTarget().Size = new global::System.Drawing.Size(317, 23);
			this.GetButton_AddTarget().TabIndex = 10;
			this.GetButton_AddTarget().Text = "添加地图上所选目标";
			this.GetButton_AddTarget().UseVisualStyleBackColor = true;
			this.vmethod_10().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_10().DisplayMember = "Text";
			this.vmethod_10().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9f);
			this.vmethod_10().FormattingEnabled = true;
			this.vmethod_10().IntegralHeight = false;
			this.vmethod_10().ItemHeight = 15;
			this.vmethod_10().Location = new global::System.Drawing.Point(0, 25);
			this.vmethod_10().Name = "LB_Targets";
			this.vmethod_10().SelectionMode = global::System.Windows.Forms.SelectionMode.MultiExtended;
			this.vmethod_10().Size = new global::System.Drawing.Size(315, 254);
			this.vmethod_10().TabIndex = 4;
			this.vmethod_0().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_0().AutoSize = true;
			this.vmethod_0().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 12f);
			this.vmethod_0().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_0().Name = "Label3";
			this.vmethod_0().Size = new global::System.Drawing.Size(148, 20);
			this.vmethod_0().TabIndex = 3;
			this.vmethod_0().Text = "备选目标清单";
			this.vmethod_84().Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.GetTSMI_HighAltitudeDetonation()
			});
			this.vmethod_84().Name = "ContextMenuStrip1";
			this.vmethod_84().Size = new global::System.Drawing.Size(251, 26);
			this.GetTSMI_HighAltitudeDetonation().Name = "TSMI_HighAltitudeDetonation";
			this.GetTSMI_HighAltitudeDetonation().Size = new global::System.Drawing.Size(250, 22);
			this.GetTSMI_HighAltitudeDetonation().Text = "特殊: 高空爆炸";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(1008, 661);
			base.Controls.Add(this.vmethod_60());
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "AttackTarget";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "武器分配";
			this.vmethod_60().ResumeLayout(false);
			this.vmethod_62().ResumeLayout(false);
			this.vmethod_62().PerformLayout();
			this.vmethod_64().ResumeLayout(false);
			this.vmethod_64().PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.GetNUD_NumberOfWeapons()).EndInit();
			this.vmethod_66().ResumeLayout(false);
			this.vmethod_66().PerformLayout();
			this.vmethod_20().ResumeLayout(false);
			this.GetTab_Attacker_ToSelectedOnly().ResumeLayout(false);
			this.GetTab_Attacker_ToAnyone().ResumeLayout(false);
			this.vmethod_68().ResumeLayout(false);
			this.vmethod_68().PerformLayout();
			this.vmethod_4().ResumeLayout(false);
			this.GetTab_Target_BySelected().ResumeLayout(false);
			this.GetTab_Target_ByAnyone().ResumeLayout(false);
			this.vmethod_70().ResumeLayout(false);
			this.vmethod_70().PerformLayout();
			this.vmethod_84().ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04002CBC RID: 11452
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
