namespace Command
{
	// Token: 0x02000B50 RID: 2896

	public sealed partial class DoctrineForm : global::ns33.CommandForm
	{
		// Token: 0x06005D6A RID: 23914 RVA: 0x002B4DC0 File Offset: 0x002B2FC0
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06005D6B RID: 23915 RVA: 0x002B4E04 File Offset: 0x002B3004
		private void InitializeComponent()
		{
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.SetTGV_WRA(new global::AdvancedDataGridView.TreeGridView());
			this.vmethod_1(new global::System.Windows.Forms.TabControl());
			this.vmethod_3(new global::System.Windows.Forms.TabPage());
			this.vmethod_123(new global::System.Windows.Forms.Button());
			this.vmethod_119(new global::System.Windows.Forms.Button());
			this.vmethod_121(new global::System.Windows.Forms.Button());
			this.vmethod_27(new global::System.Windows.Forms.TableLayoutPanel());
			this.vmethod_55(new global::System.Windows.Forms.ComboBox());
			this.vmethod_57(new global::System.Windows.Forms.ComboBox());
			this.vmethod_59(new global::System.Windows.Forms.Label());
			this.vmethod_61(new global::System.Windows.Forms.ComboBox());
			this.vmethod_107(new global::System.Windows.Forms.Label());
			this.vmethod_109(new global::System.Windows.Forms.Label());
			this.vmethod_41(new global::System.Windows.Forms.Label());
			this.vmethod_117(new global::System.Windows.Forms.Label());
			this.vmethod_31(new global::System.Windows.Forms.Label());
			this.vmethod_35(new global::System.Windows.Forms.Label());
			this.vmethod_79(new global::System.Windows.Forms.ComboBox());
			this.vmethod_135(new global::System.Windows.Forms.Label());
			this.vmethod_137(new global::System.Windows.Forms.ComboBox());
			this.vmethod_45(new global::System.Windows.Forms.Label());
			this.vmethod_141(new global::System.Windows.Forms.Label());
			this.vmethod_143(new global::System.Windows.Forms.Label());
			this.vmethod_145(new global::System.Windows.Forms.Label());
			this.vmethod_153(new global::System.Windows.Forms.ComboBox());
			this.vmethod_155(new global::System.Windows.Forms.ComboBox());
			this.vmethod_157(new global::System.Windows.Forms.ComboBox());
			this.vmethod_49(new global::System.Windows.Forms.CheckBox());
			this.vmethod_149(new global::System.Windows.Forms.CheckBox());
			this.vmethod_47(new global::System.Windows.Forms.CheckBox());
			this.vmethod_147(new global::System.Windows.Forms.CheckBox());
			this.vmethod_151(new global::System.Windows.Forms.CheckBox());
			this.vmethod_139(new global::System.Windows.Forms.CheckBox());
			this.vmethod_63(new global::System.Windows.Forms.CheckBox());
			this.vmethod_81(new global::System.Windows.Forms.CheckBox());
			this.vmethod_89(new global::System.Windows.Forms.CheckBox());
			this.vmethod_113(new global::System.Windows.Forms.Label());
			this.vmethod_101(new global::System.Windows.Forms.Label());
			this.vmethod_91(new global::System.Windows.Forms.Label());
			this.vmethod_105(new global::System.Windows.Forms.CheckBox());
			this.vmethod_97(new global::System.Windows.Forms.CheckBox());
			this.vmethod_165(new global::System.Windows.Forms.Label());
			this.vmethod_87(new global::System.Windows.Forms.ComboBox());
			this.vmethod_103(new global::System.Windows.Forms.ComboBox());
			this.vmethod_93(new global::System.Windows.Forms.ComboBox());
			this.vmethod_115(new global::System.Windows.Forms.Label());
			this.vmethod_95(new global::System.Windows.Forms.ComboBox());
			this.vmethod_29(new global::System.Windows.Forms.Label());
			this.vmethod_65(new global::System.Windows.Forms.Label());
			this.vmethod_37(new global::System.Windows.Forms.Label());
			this.vmethod_67(new global::System.Windows.Forms.ComboBox());
			this.vmethod_75(new global::System.Windows.Forms.ComboBox());
			this.vmethod_99(new global::System.Windows.Forms.CheckBox());
			this.vmethod_69(new global::System.Windows.Forms.CheckBox());
			this.vmethod_77(new global::System.Windows.Forms.CheckBox());
			this.vmethod_169(new global::System.Windows.Forms.Label());
			this.vmethod_171(new global::System.Windows.Forms.ComboBox());
			this.vmethod_175(new global::System.Windows.Forms.CheckBox());
			this.vmethod_71(new global::System.Windows.Forms.ComboBox());
			this.vmethod_39(new global::System.Windows.Forms.Label());
			this.vmethod_33(new global::System.Windows.Forms.Label());
			this.vmethod_83(new global::System.Windows.Forms.ComboBox());
			this.vmethod_73(new global::System.Windows.Forms.CheckBox());
			this.vmethod_85(new global::System.Windows.Forms.CheckBox());
			this.vmethod_111(new global::System.Windows.Forms.Label());
			this.vmethod_159(new global::System.Windows.Forms.Label());
			this.vmethod_163(new global::System.Windows.Forms.ComboBox());
			this.vmethod_161(new global::System.Windows.Forms.CheckBox());
			this.vmethod_51(new global::System.Windows.Forms.Label());
			this.vmethod_53(new global::System.Windows.Forms.ComboBox());
			this.vmethod_43(new global::System.Windows.Forms.CheckBox());
			this.vmethod_167(new global::System.Windows.Forms.Label());
			this.vmethod_173(new global::System.Windows.Forms.ComboBox());
			this.vmethod_177(new global::System.Windows.Forms.CheckBox());
			this.vmethod_179(new global::System.Windows.Forms.ComboBox());
			this.vmethod_181(new global::System.Windows.Forms.Label());
			this.vmethod_183(new global::System.Windows.Forms.CheckBox());
			this.vmethod_185(new global::System.Windows.Forms.CheckBox());
			this.vmethod_187(new global::System.Windows.Forms.ComboBox());
			this.vmethod_189(new global::System.Windows.Forms.Label());
			this.vmethod_195(new global::System.Windows.Forms.Label());
			this.vmethod_199(new global::System.Windows.Forms.Label());
			this.vmethod_201(new global::System.Windows.Forms.ComboBox());
			this.vmethod_203(new global::System.Windows.Forms.Label());
			this.vmethod_205(new global::System.Windows.Forms.ComboBox());
			this.vmethod_207(new global::System.Windows.Forms.CheckBox());
			this.vmethod_209(new global::System.Windows.Forms.CheckBox());
			this.vmethod_211(new global::System.Windows.Forms.Label());
			this.vmethod_213(new global::System.Windows.Forms.ComboBox());
			this.vmethod_215(new global::System.Windows.Forms.CheckBox());
			this.vmethod_217(new global::System.Windows.Forms.Label());
			this.vmethod_219(new global::System.Windows.Forms.ComboBox());
			this.vmethod_221(new global::System.Windows.Forms.CheckBox());
			this.vmethod_223(new global::System.Windows.Forms.Label());
			this.vmethod_225(new global::System.Windows.Forms.ComboBox());
			this.vmethod_227(new global::System.Windows.Forms.CheckBox());
			this.vmethod_229(new global::System.Windows.Forms.Label());
			this.vmethod_231(new global::System.Windows.Forms.ComboBox());
			this.vmethod_233(new global::System.Windows.Forms.CheckBox());
			this.vmethod_193(new global::System.Windows.Forms.ComboBox());
			this.vmethod_197(new global::System.Windows.Forms.CheckBox());
			this.vmethod_191(new global::System.Windows.Forms.Label());
			this.vmethod_283(new global::System.Windows.Forms.Label());
			this.vmethod_285(new global::System.Windows.Forms.CheckBox());
			this.vmethod_287(new global::System.Windows.Forms.ComboBox());
			this.vmethod_5(new global::System.Windows.Forms.TabPage());
			this.vmethod_129(new global::System.Windows.Forms.Button());
			this.vmethod_131(new global::System.Windows.Forms.Button());
			this.vmethod_133(new global::System.Windows.Forms.Button());
			this.vmethod_17(new global::System.Windows.Forms.ComboBox());
			this.vmethod_19(new global::System.Windows.Forms.Label());
			this.vmethod_13(new global::System.Windows.Forms.ComboBox());
			this.vmethod_15(new global::System.Windows.Forms.Label());
			this.vmethod_11(new global::System.Windows.Forms.CheckBox());
			this.vmethod_7(new global::System.Windows.Forms.ComboBox());
			this.vmethod_9(new global::System.Windows.Forms.Label());
			this.vmethod_21(new global::System.Windows.Forms.TabPage());
			this.vmethod_125(new global::System.Windows.Forms.Button());
			this.vmethod_127(new global::System.Windows.Forms.Button());
			this.vmethod_25(new global::System.Windows.Forms.Button());
			this.vmethod_235(new global::System.Windows.Forms.TabPage());
			this.vmethod_255(new global::System.Windows.Forms.ComboBox());
			this.vmethod_257(new global::System.Windows.Forms.ComboBox());
			this.vmethod_259(new global::System.Windows.Forms.ComboBox());
			this.vmethod_261(new global::System.Windows.Forms.Label());
			this.vmethod_263(new global::System.Windows.Forms.Label());
			this.vmethod_265(new global::System.Windows.Forms.Label());
			this.vmethod_267(new global::System.Windows.Forms.Label());
			this.vmethod_269(new global::System.Windows.Forms.ComboBox());
			this.vmethod_271(new global::System.Windows.Forms.Label());
			this.vmethod_237(new global::System.Windows.Forms.ComboBox());
			this.vmethod_239(new global::System.Windows.Forms.ComboBox());
			this.vmethod_241(new global::System.Windows.Forms.ComboBox());
			this.vmethod_243(new global::System.Windows.Forms.Label());
			this.vmethod_245(new global::System.Windows.Forms.Label());
			this.vmethod_247(new global::System.Windows.Forms.Label());
			this.vmethod_249(new global::System.Windows.Forms.Label());
			this.vmethod_251(new global::System.Windows.Forms.ComboBox());
			this.vmethod_253(new global::System.Windows.Forms.Label());
			this.vmethod_273(new global::ns29.TreeGridViewTextBoxColumn());
			this.SetWeaponsPerSalvo(new global::System.Windows.Forms.DataGridViewComboBoxColumn());
			this.vmethod_277(new global::System.Windows.Forms.DataGridViewComboBoxColumn());
			this.vmethod_279(new global::System.Windows.Forms.DataGridViewComboBoxColumn());
			this.vmethod_281(new global::System.Windows.Forms.DataGridViewComboBoxColumn());
			((global::System.ComponentModel.ISupportInitialize)this.GetTGV_WRA()).BeginInit();
			this.vmethod_0().SuspendLayout();
			this.vmethod_2().SuspendLayout();
			this.vmethod_26().SuspendLayout();
			this.vmethod_4().SuspendLayout();
			this.vmethod_20().SuspendLayout();
			this.vmethod_234().SuspendLayout();
			base.SuspendLayout();
			this.GetTGV_WRA().AllowUserToAddRows = false;
			this.GetTGV_WRA().AllowUserToDeleteRows = false;
			this.GetTGV_WRA().AllowUserToOrderColumns = true;
			this.GetTGV_WRA().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetTGV_WRA().AutoSizeColumnsMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
			this.GetTGV_WRA().AutoSizeRowsMode = global::System.Windows.Forms.DataGridViewAutoSizeRowsMode.DisplayedCells;
			this.GetTGV_WRA().CellBorderStyle = global::System.Windows.Forms.DataGridViewCellBorderStyle.None;
			this.GetTGV_WRA().Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.GetTargetType(),
				this.GetWeaponsPerSalvo(),
				this.GetShootersPerSalvo(),
				this.GetFiringRange(),
				this.GetSelfDefenceRange()
			});
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Tahoma", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.GetTGV_WRA().DefaultCellStyle = dataGridViewCellStyle;
			this.GetTGV_WRA().EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.GetTGV_WRA().method_8(null);
			this.GetTGV_WRA().Location = new global::System.Drawing.Point(0, 0);
			this.GetTGV_WRA().MultiSelect = false;
			this.GetTGV_WRA().Name = "TGV_WRA";
			this.GetTGV_WRA().RowHeadersVisible = false;
			this.GetTGV_WRA().RowHeadersWidth = 20;
			this.GetTGV_WRA().SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.GetTGV_WRA().method_6(false);
			this.GetTGV_WRA().Size = new global::System.Drawing.Size(1000, 642);
			this.GetTGV_WRA().TabIndex = 8;
			this.vmethod_0().Controls.Add(this.vmethod_2());
			this.vmethod_0().Controls.Add(this.vmethod_4());
			this.vmethod_0().Controls.Add(this.vmethod_20());
			this.vmethod_0().Controls.Add(this.vmethod_234());
			this.vmethod_0().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_0().Location = new global::System.Drawing.Point(0, 0);
			this.vmethod_0().Name = "TabControl1A";
			this.vmethod_0().SelectedIndex = 0;
			this.vmethod_0().Size = new global::System.Drawing.Size(1008, 691);
			this.vmethod_0().TabIndex = 0;
			this.vmethod_2().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_2().Controls.Add(this.vmethod_122());
			this.vmethod_2().Controls.Add(this.vmethod_118());
			this.vmethod_2().Controls.Add(this.vmethod_120());
			this.vmethod_2().Controls.Add(this.vmethod_26());
			this.vmethod_2().Location = new global::System.Drawing.Point(4, 22);
			this.vmethod_2().Name = "TabPage1";
			this.vmethod_2().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_2().Size = new global::System.Drawing.Size(1000, 665);
			this.vmethod_2().TabIndex = 0;
			this.vmethod_2().Text = "总体";
			this.vmethod_122().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.vmethod_122().Location = new global::System.Drawing.Point(-1, 643);
			this.vmethod_122().Name = "Button_ResetCurrent_Doctrine";
			this.vmethod_122().Size = new global::System.Drawing.Size(265, 23);
			this.vmethod_122().TabIndex = 0;
			this.vmethod_122().Text = "重置作战条令";
			this.vmethod_122().UseVisualStyleBackColor = true;
			this.vmethod_118().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.vmethod_118().Location = new global::System.Drawing.Point(531, 643);
			this.vmethod_118().Name = "Button_ResetAffectedMissions_Doctrine";
			this.vmethod_118().Size = new global::System.Drawing.Size(265, 23);
			this.vmethod_118().TabIndex = 2;
			this.vmethod_118().Text = "重置关联的使命任务";
			this.vmethod_118().UseVisualStyleBackColor = true;
			this.vmethod_120().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.vmethod_120().Location = new global::System.Drawing.Point(265, 643);
			this.vmethod_120().Name = "Button_ResetAffectedUnits_Doctrine";
			this.vmethod_120().Size = new global::System.Drawing.Size(265, 23);
			this.vmethod_120().TabIndex = 1;
			this.vmethod_120().Text = "重置关联的作战单元";
			this.vmethod_120().UseVisualStyleBackColor = true;
			this.vmethod_26().ColumnCount = 6;
			this.vmethod_26().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle());
			this.vmethod_26().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.vmethod_26().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Absolute, 30f));
			this.vmethod_26().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle());
			this.vmethod_26().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.vmethod_26().ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Absolute, 23f));
			this.vmethod_26().Controls.Add(this.vmethod_54(), 1, 3);
			this.vmethod_26().Controls.Add(this.vmethod_56(), 1, 1);
			this.vmethod_26().Controls.Add(this.vmethod_58(), 0, 8);
			this.vmethod_26().Controls.Add(this.GetCombo_BehaviorTowardsAmbigousTarget(), 1, 8);
			this.vmethod_26().Controls.Add(this.vmethod_106(), 0, 0);
			this.vmethod_26().Controls.Add(this.vmethod_108(), 0, 2);
			this.vmethod_26().Controls.Add(this.vmethod_40(), 0, 1);
			this.vmethod_26().Controls.Add(this.vmethod_116(), 0, 10);
			this.vmethod_26().Controls.Add(this.vmethod_30(), 0, 11);
			this.vmethod_26().Controls.Add(this.vmethod_34(), 0, 9);
			this.vmethod_26().Controls.Add(this.vmethod_78(), 1, 9);
			this.vmethod_26().Controls.Add(this.vmethod_134(), 0, 7);
			this.vmethod_26().Controls.Add(this.vmethod_136(), 1, 7);
			this.vmethod_26().Controls.Add(this.vmethod_44(), 0, 3);
			this.vmethod_26().Controls.Add(this.vmethod_140(), 0, 4);
			this.vmethod_26().Controls.Add(this.vmethod_142(), 0, 5);
			this.vmethod_26().Controls.Add(this.vmethod_144(), 0, 6);
			this.vmethod_26().Controls.Add(this.vmethod_152(), 1, 4);
			this.vmethod_26().Controls.Add(this.vmethod_154(), 1, 5);
			this.vmethod_26().Controls.Add(this.vmethod_156(), 1, 6);
			this.vmethod_26().Controls.Add(this.vmethod_48(), 2, 1);
			this.vmethod_26().Controls.Add(this.vmethod_148(), 2, 5);
			this.vmethod_26().Controls.Add(this.vmethod_46(), 2, 3);
			this.vmethod_26().Controls.Add(this.vmethod_146(), 2, 4);
			this.vmethod_26().Controls.Add(this.vmethod_150(), 2, 6);
			this.vmethod_26().Controls.Add(this.vmethod_138(), 2, 7);
			this.vmethod_26().Controls.Add(this.vmethod_62(), 2, 8);
			this.vmethod_26().Controls.Add(this.vmethod_80(), 2, 9);
			this.vmethod_26().Controls.Add(this.vmethod_88(), 2, 11);
			this.vmethod_26().Controls.Add(this.vmethod_112(), 3, 0);
			this.vmethod_26().Controls.Add(this.vmethod_100(), 3, 1);
			this.vmethod_26().Controls.Add(this.vmethod_90(), 3, 2);
			this.vmethod_26().Controls.Add(this.vmethod_104(), 5, 1);
			this.vmethod_26().Controls.Add(this.vmethod_96(), 5, 2);
			this.vmethod_26().Controls.Add(this.vmethod_164(), 3, 3);
			this.vmethod_26().Controls.Add(this.vmethod_86(), 1, 11);
			this.vmethod_26().Controls.Add(this.vmethod_102(), 4, 1);
			this.vmethod_26().Controls.Add(this.vmethod_92(), 4, 2);
			this.vmethod_26().Controls.Add(this.vmethod_114(), 0, 12);
			this.vmethod_26().Controls.Add(this.vmethod_94(), 1, 13);
			this.vmethod_26().Controls.Add(this.vmethod_28(), 0, 13);
			this.vmethod_26().Controls.Add(this.vmethod_64(), 0, 14);
			this.vmethod_26().Controls.Add(this.vmethod_36(), 0, 15);
			this.vmethod_26().Controls.Add(this.vmethod_66(), 1, 14);
			this.vmethod_26().Controls.Add(this.vmethod_74(), 1, 15);
			this.vmethod_26().Controls.Add(this.vmethod_98(), 2, 13);
			this.vmethod_26().Controls.Add(this.vmethod_68(), 2, 14);
			this.vmethod_26().Controls.Add(this.vmethod_76(), 2, 15);
			this.vmethod_26().Controls.Add(this.vmethod_168(), 1, 0);
			this.vmethod_26().Controls.Add(this.vmethod_170(), 4, 3);
			this.vmethod_26().Controls.Add(this.vmethod_174(), 5, 3);
			this.vmethod_26().Controls.Add(this.vmethod_70(), 4, 11);
			this.vmethod_26().Controls.Add(this.vmethod_38(), 3, 11);
			this.vmethod_26().Controls.Add(this.vmethod_32(), 3, 10);
			this.vmethod_26().Controls.Add(this.vmethod_82(), 4, 10);
			this.vmethod_26().Controls.Add(this.vmethod_72(), 5, 11);
			this.vmethod_26().Controls.Add(this.vmethod_84(), 5, 10);
			this.vmethod_26().Controls.Add(this.vmethod_110(), 3, 9);
			this.vmethod_26().Controls.Add(this.vmethod_158(), 3, 7);
			this.vmethod_26().Controls.Add(this.vmethod_162(), 4, 7);
			this.vmethod_26().Controls.Add(this.vmethod_160(), 5, 7);
			this.vmethod_26().Controls.Add(this.vmethod_50(), 3, 6);
			this.vmethod_26().Controls.Add(this.vmethod_52(), 4, 6);
			this.vmethod_26().Controls.Add(this.vmethod_42(), 5, 6);
			this.vmethod_26().Controls.Add(this.vmethod_166(), 3, 5);
			this.vmethod_26().Controls.Add(this.vmethod_172(), 4, 5);
			this.vmethod_26().Controls.Add(this.vmethod_176(), 5, 5);
			this.vmethod_26().Controls.Add(this.vmethod_178(), 4, 8);
			this.vmethod_26().Controls.Add(this.vmethod_180(), 3, 8);
			this.vmethod_26().Controls.Add(this.vmethod_182(), 5, 8);
			this.vmethod_26().Controls.Add(this.vmethod_184(), 5, 4);
			this.vmethod_26().Controls.Add(this.vmethod_186(), 4, 4);
			this.vmethod_26().Controls.Add(this.vmethod_188(), 3, 4);
			this.vmethod_26().Controls.Add(this.vmethod_194(), 3, 12);
			this.vmethod_26().Controls.Add(this.vmethod_198(), 3, 13);
			this.vmethod_26().Controls.Add(this.vmethod_200(), 4, 13);
			this.vmethod_26().Controls.Add(this.vmethod_202(), 3, 14);
			this.vmethod_26().Controls.Add(this.vmethod_204(), 4, 14);
			this.vmethod_26().Controls.Add(this.vmethod_206(), 5, 13);
			this.vmethod_26().Controls.Add(this.vmethod_208(), 5, 14);
			this.vmethod_26().Controls.Add(this.vmethod_210(), 3, 15);
			this.vmethod_26().Controls.Add(this.vmethod_212(), 4, 15);
			this.vmethod_26().Controls.Add(this.vmethod_214(), 5, 15);
			this.vmethod_26().Controls.Add(this.vmethod_216(), 3, 16);
			this.vmethod_26().Controls.Add(this.vmethod_218(), 4, 16);
			this.vmethod_26().Controls.Add(this.vmethod_220(), 5, 16);
			this.vmethod_26().Controls.Add(this.vmethod_222(), 3, 17);
			this.vmethod_26().Controls.Add(this.vmethod_224(), 4, 17);
			this.vmethod_26().Controls.Add(this.vmethod_226(), 5, 17);
			this.vmethod_26().Controls.Add(this.vmethod_228(), 3, 18);
			this.vmethod_26().Controls.Add(this.vmethod_230(), 4, 18);
			this.vmethod_26().Controls.Add(this.vmethod_232(), 5, 18);
			this.vmethod_26().Controls.Add(this.vmethod_192(), 1, 17);
			this.vmethod_26().Controls.Add(this.vmethod_196(), 2, 17);
			this.vmethod_26().Controls.Add(this.vmethod_190(), 0, 17);
			this.vmethod_26().Controls.Add(this.vmethod_282(), 0, 16);
			this.vmethod_26().Controls.Add(this.vmethod_284(), 2, 16);
			this.vmethod_26().Controls.Add(this.vmethod_286(), 1, 16);
			this.vmethod_26().Dock = global::System.Windows.Forms.DockStyle.Top;
			this.vmethod_26().Location = new global::System.Drawing.Point(3, 3);
			this.vmethod_26().Name = "TableLayoutPanel1";
			this.vmethod_26().RowCount = 25;
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Absolute, 25f));
			this.vmethod_26().Size = new global::System.Drawing.Size(994, 495);
			this.vmethod_26().TabIndex = 7;
			this.vmethod_54().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_54().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_54().DropDownWidth = 450;
			this.vmethod_54().FormattingEnabled = true;
			this.vmethod_54().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_54().Location = new global::System.Drawing.Point(215, 78);
			this.vmethod_54().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_54().Name = "Combo_WeaponControlStatus_Air";
			this.vmethod_54().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_54().TabIndex = 1;
			this.vmethod_56().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_56().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_56().DropDownWidth = 450;
			this.vmethod_56().FormattingEnabled = true;
			this.vmethod_56().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_56().Location = new global::System.Drawing.Point(215, 28);
			this.vmethod_56().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_56().Name = "Combo_UseNukes";
			this.vmethod_56().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_56().TabIndex = 0;
			this.vmethod_58().Location = new global::System.Drawing.Point(0, 206);
			this.vmethod_58().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_58().Name = "Label5";
			this.vmethod_58().Size = new global::System.Drawing.Size(136, 13);
			this.vmethod_58().TabIndex = 5;
			this.vmethod_58().Text = "接战模糊位置目标:";
			this.GetCombo_BehaviorTowardsAmbigousTarget().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GetCombo_BehaviorTowardsAmbigousTarget().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_BehaviorTowardsAmbigousTarget().FormattingEnabled = true;
			this.GetCombo_BehaviorTowardsAmbigousTarget().Items.AddRange(new object[]
			{
				"忽略模糊性",
				"乐观决策",
				"悲观决策",
				"与上级一致"
			});
			this.GetCombo_BehaviorTowardsAmbigousTarget().Location = new global::System.Drawing.Point(215, 203);
			this.GetCombo_BehaviorTowardsAmbigousTarget().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.GetCombo_BehaviorTowardsAmbigousTarget().Name = "Combo_BehaviorTowardsAmbigousTarget";
			this.GetCombo_BehaviorTowardsAmbigousTarget().Size = new global::System.Drawing.Size(253, 21);
			this.GetCombo_BehaviorTowardsAmbigousTarget().TabIndex = 6;
			this.vmethod_106().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_106().Location = new global::System.Drawing.Point(0, 9);
			this.vmethod_106().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_106().Name = "Label19";
			this.vmethod_106().Size = new global::System.Drawing.Size(150, 16);
			this.vmethod_106().TabIndex = 28;
			this.vmethod_106().Text = "战略武器运用";
			this.vmethod_108().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_108().Location = new global::System.Drawing.Point(0, 59);
			this.vmethod_108().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_108().Name = "Label20";
			this.vmethod_108().Size = new global::System.Drawing.Size(150, 16);
			this.vmethod_108().TabIndex = 29;
			this.vmethod_108().Text = "交战规则";
			this.vmethod_40().Location = new global::System.Drawing.Point(0, 31);
			this.vmethod_40().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_40().Name = "Label12";
			this.vmethod_40().Size = new global::System.Drawing.Size(113, 13);
			this.vmethod_40().TabIndex = 4;
			this.vmethod_40().Text = "使用核武器:";
			this.vmethod_116().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_116().Location = new global::System.Drawing.Point(0, 259);
			this.vmethod_116().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_116().Name = "Label25";
			this.vmethod_116().Size = new global::System.Drawing.Size(192, 16);
			this.vmethod_116().TabIndex = 34;
			this.vmethod_116().Text = "电磁管控";
			this.vmethod_30().Location = new global::System.Drawing.Point(0, 281);
			this.vmethod_30().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_30().Name = "Label15";
			this.vmethod_30().Size = new global::System.Drawing.Size(172, 13);
			this.vmethod_30().TabIndex = 25;
			this.vmethod_30().Text = "受攻击时忽略电磁管控:";
			this.vmethod_34().Location = new global::System.Drawing.Point(0, 231);
			this.vmethod_34().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_34().Name = "Label11";
			this.vmethod_34().Size = new global::System.Drawing.Size(137, 13);
			this.vmethod_34().TabIndex = 19;
			this.vmethod_34().Text = "接战临机出现目标:";
			this.vmethod_78().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_78().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_78().FormattingEnabled = true;
			this.vmethod_78().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_78().Location = new global::System.Drawing.Point(215, 228);
			this.vmethod_78().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_78().Name = "Combo_ShootTourists";
			this.vmethod_78().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_78().TabIndex = 7;
			this.vmethod_134().Location = new global::System.Drawing.Point(0, 181);
			this.vmethod_134().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_134().Name = "Label1";
			this.vmethod_134().Size = new global::System.Drawing.Size(186, 13);
			this.vmethod_134().TabIndex = 35;
			this.vmethod_134().Text = "受到攻击时忽略计划航线:";
			this.vmethod_136().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_136().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_136().FormattingEnabled = true;
			this.vmethod_136().Location = new global::System.Drawing.Point(215, 178);
			this.vmethod_136().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_136().Name = "Combo_IgnorePlottedCourse";
			this.vmethod_136().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_136().TabIndex = 5;
			this.vmethod_44().Location = new global::System.Drawing.Point(0, 81);
			this.vmethod_44().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_44().Name = "Label13";
			this.vmethod_44().Size = new global::System.Drawing.Size(171, 13);
			this.vmethod_44().TabIndex = 5;
			this.vmethod_44().Text = "武器控制状态, 对空:";
			this.vmethod_140().Location = new global::System.Drawing.Point(0, 106);
			this.vmethod_140().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_140().Name = "Label2";
			this.vmethod_140().Size = new global::System.Drawing.Size(195, 13);
			this.vmethod_140().TabIndex = 5;
			this.vmethod_140().Text = "武器控制状态, 对海:";
			this.vmethod_142().Location = new global::System.Drawing.Point(0, 131);
			this.vmethod_142().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_142().Name = "Label23";
			this.vmethod_142().Size = new global::System.Drawing.Size(215, 13);
			this.vmethod_142().TabIndex = 5;
			this.vmethod_142().Text = "武器控制状态, 对潜:";
			this.vmethod_144().Location = new global::System.Drawing.Point(0, 156);
			this.vmethod_144().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_144().Name = "Label26";
			this.vmethod_144().Size = new global::System.Drawing.Size(180, 13);
			this.vmethod_144().TabIndex = 5;
			this.vmethod_144().Text = "武器控制状态, 对地:";
			this.vmethod_152().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_152().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_152().DropDownWidth = 450;
			this.vmethod_152().FormattingEnabled = true;
			this.vmethod_152().Location = new global::System.Drawing.Point(215, 103);
			this.vmethod_152().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_152().Name = "Combo_WeaponControlStatus_Surface";
			this.vmethod_152().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_152().TabIndex = 2;
			this.vmethod_154().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_154().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_154().DropDownWidth = 450;
			this.vmethod_154().FormattingEnabled = true;
			this.vmethod_154().Location = new global::System.Drawing.Point(215, 128);
			this.vmethod_154().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_154().Name = "Combo_WeaponControlStatus_Submarine";
			this.vmethod_154().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_154().TabIndex = 3;
			this.vmethod_156().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_156().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_156().DropDownWidth = 450;
			this.vmethod_156().FormattingEnabled = true;
			this.vmethod_156().Location = new global::System.Drawing.Point(215, 153);
			this.vmethod_156().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_156().Name = "Combo_WeaponControlStatus_Land";
			this.vmethod_156().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_156().TabIndex = 4;
			this.vmethod_48().Location = new global::System.Drawing.Point(471, 31);
			this.vmethod_48().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_48().Name = "CB_UseNukes_PlayerEditable";
			this.vmethod_48().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_48().TabIndex = 29;
			this.vmethod_48().UseVisualStyleBackColor = true;
			this.vmethod_148().Location = new global::System.Drawing.Point(471, 131);
			this.vmethod_148().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_148().Name = "CB_WeaponControlStatus_Submarine_PlayerEditable";
			this.vmethod_148().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_148().TabIndex = 32;
			this.vmethod_148().UseVisualStyleBackColor = true;
			this.vmethod_46().Location = new global::System.Drawing.Point(471, 81);
			this.vmethod_46().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_46().Name = "CB_WeaponControlStatus_Air_PlayerEditable";
			this.vmethod_46().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_46().TabIndex = 30;
			this.vmethod_46().UseVisualStyleBackColor = true;
			this.vmethod_146().Location = new global::System.Drawing.Point(471, 106);
			this.vmethod_146().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_146().Name = "CB_WeaponControlStatus_Surface_PlayerEditable";
			this.vmethod_146().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_146().TabIndex = 31;
			this.vmethod_146().UseVisualStyleBackColor = true;
			this.vmethod_150().Location = new global::System.Drawing.Point(471, 156);
			this.vmethod_150().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_150().Name = "CB_WeaponControlStatus_Land_PlayerEditable";
			this.vmethod_150().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_150().TabIndex = 33;
			this.vmethod_150().UseVisualStyleBackColor = true;
			this.vmethod_138().Location = new global::System.Drawing.Point(471, 181);
			this.vmethod_138().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_138().Name = "CB_IgnorePlottedCourse_PlayerEditable";
			this.vmethod_138().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_138().TabIndex = 34;
			this.vmethod_138().UseVisualStyleBackColor = true;
			this.vmethod_62().Location = new global::System.Drawing.Point(471, 206);
			this.vmethod_62().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_62().Name = "CB_BehaviorTowardsAmbigousTarget_PlayerEditable";
			this.vmethod_62().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_62().TabIndex = 35;
			this.vmethod_62().UseVisualStyleBackColor = true;
			this.vmethod_80().Location = new global::System.Drawing.Point(471, 231);
			this.vmethod_80().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_80().Name = "CB_ShootTourists_PlayerEditable";
			this.vmethod_80().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_80().TabIndex = 36;
			this.vmethod_80().UseVisualStyleBackColor = true;
			this.vmethod_88().Location = new global::System.Drawing.Point(471, 281);
			this.vmethod_88().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_88().Name = "CB_IgnoreEMCONunderAttack_PlayerEditable";
			this.vmethod_88().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_88().TabIndex = 37;
			this.vmethod_88().UseVisualStyleBackColor = true;
			this.vmethod_26().SetColumnSpan(this.vmethod_112(), 2);
			this.vmethod_112().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_112().Location = new global::System.Drawing.Point(498, 9);
			this.vmethod_112().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_112().Name = "Label22";
			this.vmethod_112().Size = new global::System.Drawing.Size(172, 16);
			this.vmethod_112().TabIndex = 31;
			this.vmethod_112().Text = "空中作战行动";
			this.vmethod_100().Location = new global::System.Drawing.Point(498, 31);
			this.vmethod_100().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_100().Name = "Label18";
			this.vmethod_100().Size = new global::System.Drawing.Size(112, 13);
			this.vmethod_100().TabIndex = 27;
			this.vmethod_100().Text = "空战节奏:";
			this.vmethod_90().Location = new global::System.Drawing.Point(498, 56);
			this.vmethod_90().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_90().Name = "Label17";
			this.vmethod_90().Size = new global::System.Drawing.Size(92, 13);
			this.vmethod_90().TabIndex = 27;
			this.vmethod_90().Text = "快速出动:";
			this.vmethod_104().Location = new global::System.Drawing.Point(974, 31);
			this.vmethod_104().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_104().Name = "CB_AirOpsTempo_PlayerEditable";
			this.vmethod_104().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_104().TabIndex = 42;
			this.vmethod_104().Text = "允许用户编辑";
			this.vmethod_104().UseVisualStyleBackColor = true;
			this.vmethod_96().Location = new global::System.Drawing.Point(974, 56);
			this.vmethod_96().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_96().Name = "CB_QuickTurnAroundForAicraft_PlayerEditable";
			this.vmethod_96().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_96().TabIndex = 43;
			this.vmethod_96().Text = "允许用户编辑";
			this.vmethod_96().UseVisualStyleBackColor = true;
			this.vmethod_164().Location = new global::System.Drawing.Point(498, 81);
			this.vmethod_164().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_164().Name = "Label28";
			this.vmethod_164().Size = new global::System.Drawing.Size(122, 13);
			this.vmethod_164().TabIndex = 5;
			this.vmethod_164().Text = "燃油状态，预先规划:";
			this.vmethod_86().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_86().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_86().FormattingEnabled = true;
			this.vmethod_86().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_86().Location = new global::System.Drawing.Point(215, 278);
			this.vmethod_86().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_86().Name = "Combo_IgnoreEMCONunderAttack";
			this.vmethod_86().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_86().TabIndex = 8;
			this.vmethod_102().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_102().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_102().FormattingEnabled = true;
			this.vmethod_102().Items.AddRange(new object[]
			{
				"高强度作战",
				"持续作战"
			});
			this.vmethod_102().Location = new global::System.Drawing.Point(718, 28);
			this.vmethod_102().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_102().Name = "Combo_AirOpsTempo";
			this.vmethod_102().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_102().TabIndex = 13;
			this.vmethod_92().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_92().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_92().FormattingEnabled = true;
			this.vmethod_92().Items.AddRange(new object[]
			{
				"Yes",
				"Fighters & ASW",
				"No",
				"Inherit"
			});
			this.vmethod_92().Location = new global::System.Drawing.Point(718, 53);
			this.vmethod_92().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_92().Name = "Combo_QuickTurnAroundForAicraft";
			this.vmethod_92().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_92().TabIndex = 14;
			this.vmethod_114().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_114().Location = new global::System.Drawing.Point(0, 309);
			this.vmethod_114().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_114().Name = "Label24";
			this.vmethod_114().Size = new global::System.Drawing.Size(40, 16);
			this.vmethod_114().TabIndex = 33;
			this.vmethod_114().Text = "杂项";
			this.vmethod_94().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_94().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_94().FormattingEnabled = true;
			this.vmethod_94().Items.AddRange(new object[]
			{
				"自动与手动开火",
				"仅手动开火",
				"无",
				"与上级保持一致"
			});
			this.vmethod_94().Location = new global::System.Drawing.Point(215, 328);
			this.vmethod_94().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_94().Name = "Combo_UseKinematicRangeForTorpedoes";
			this.vmethod_94().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_94().TabIndex = 9;
			this.vmethod_28().Location = new global::System.Drawing.Point(0, 331);
			this.vmethod_28().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_28().Name = "Label16";
			this.vmethod_28().Size = new global::System.Drawing.Size(151, 13);
			this.vmethod_28().TabIndex = 26;
			this.vmethod_28().Text = "鱼雷使用动力航程:";
			this.vmethod_64().Location = new global::System.Drawing.Point(0, 356);
			this.vmethod_64().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_64().Name = "Label7";
			this.vmethod_64().Size = new global::System.Drawing.Size(97, 13);
			this.vmethod_64().TabIndex = 7;
			this.vmethod_64().Text = "自动规避:";
			this.vmethod_36().Location = new global::System.Drawing.Point(0, 381);
			this.vmethod_36().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_36().Name = "Label10";
			this.vmethod_36().Size = new global::System.Drawing.Size(84, 13);
			this.vmethod_36().TabIndex = 15;
			this.vmethod_36().Text = "加油/补给:";
			this.vmethod_66().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_66().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_66().FormattingEnabled = true;
			this.vmethod_66().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_66().Location = new global::System.Drawing.Point(215, 353);
			this.vmethod_66().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_66().Name = "Combo_AutoEvade";
			this.vmethod_66().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_66().TabIndex = 10;
			this.vmethod_74().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_74().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_74().DropDownWidth = 450;
			this.vmethod_74().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_74().FormattingEnabled = true;
			this.vmethod_74().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_74().Location = new global::System.Drawing.Point(215, 378);
			this.vmethod_74().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_74().Name = "Combo_UseRefuel";
			this.vmethod_74().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_74().TabIndex = 11;
			this.vmethod_98().Location = new global::System.Drawing.Point(471, 331);
			this.vmethod_98().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_98().Name = "CB_UseKinematicRangeForTorpedoes_PlayerEditable";
			this.vmethod_98().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_98().TabIndex = 38;
			this.vmethod_98().UseVisualStyleBackColor = true;
			this.vmethod_68().Location = new global::System.Drawing.Point(471, 356);
			this.vmethod_68().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_68().Name = "CB_AutoEvade_PlayerEditable";
			this.vmethod_68().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_68().TabIndex = 39;
			this.vmethod_68().UseVisualStyleBackColor = true;
			this.vmethod_76().Location = new global::System.Drawing.Point(471, 381);
			this.vmethod_76().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_76().Name = "CB_UseRefuel_PlayerEditable";
			this.vmethod_76().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_76().TabIndex = 40;
			this.vmethod_76().UseVisualStyleBackColor = true;
			this.vmethod_168().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_26().SetColumnSpan(this.vmethod_168(), 2);
			this.vmethod_168().Location = new global::System.Drawing.Point(215, 6);
			this.vmethod_168().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_168().Name = "Label30";
			this.vmethod_168().RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.vmethod_168().Size = new global::System.Drawing.Size(283, 19);
			this.vmethod_168().TabIndex = 58;
			this.vmethod_168().Text = "提示: 使用检查盒设置条令是否允许用户编辑:";
			this.vmethod_170().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_170().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_170().DropDownWidth = 550;
			this.vmethod_170().FormattingEnabled = true;
			this.vmethod_170().Location = new global::System.Drawing.Point(718, 78);
			this.vmethod_170().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_170().Name = "Combo_FuelState";
			this.vmethod_170().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_170().TabIndex = 15;
			this.vmethod_174().Location = new global::System.Drawing.Point(974, 81);
			this.vmethod_174().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_174().Name = "CB_FuelState_PlayerEditable";
			this.vmethod_174().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_174().TabIndex = 44;
			this.vmethod_174().Text = "允许用户编辑";
			this.vmethod_174().UseVisualStyleBackColor = true;
			this.vmethod_70().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_70().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_70().FormattingEnabled = true;
			this.vmethod_70().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_70().Location = new global::System.Drawing.Point(718, 278);
			this.vmethod_70().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_70().Name = "Combo_Standoff";
			this.vmethod_70().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_70().TabIndex = 22;
			this.vmethod_38().Location = new global::System.Drawing.Point(498, 281);
			this.vmethod_38().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_38().Name = "Label6";
			this.vmethod_38().Size = new global::System.Drawing.Size(133, 13);
			this.vmethod_38().TabIndex = 11;
			this.vmethod_38().Text = "与目标保持距离:";
			this.vmethod_32().Location = new global::System.Drawing.Point(498, 256);
			this.vmethod_32().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_32().Name = "Label14";
			this.vmethod_32().Size = new global::System.Drawing.Size(150, 13);
			this.vmethod_32().TabIndex = 21;
			this.vmethod_32().Text = "以反舰模式使用舰空导弹:";
			this.vmethod_82().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_82().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_82().FormattingEnabled = true;
			this.vmethod_82().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_82().Location = new global::System.Drawing.Point(718, 253);
			this.vmethod_82().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_82().Name = "Combo_UseSAMsOnASuW";
			this.vmethod_82().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_82().TabIndex = 21;
			this.vmethod_72().Location = new global::System.Drawing.Point(974, 281);
			this.vmethod_72().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_72().Name = "CB_Standoff_PlayerEditable";
			this.vmethod_72().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_72().TabIndex = 51;
			this.vmethod_72().Text = "允许用户编辑";
			this.vmethod_72().UseVisualStyleBackColor = true;
			this.vmethod_84().Location = new global::System.Drawing.Point(974, 256);
			this.vmethod_84().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_84().Name = "CB_UseSAMsOnASuW_PlayerEditable";
			this.vmethod_84().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_84().TabIndex = 50;
			this.vmethod_84().Text = "允许用户编辑";
			this.vmethod_84().UseVisualStyleBackColor = true;
			this.vmethod_26().SetColumnSpan(this.vmethod_110(), 2);
			this.vmethod_110().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_110().Location = new global::System.Drawing.Point(498, 234);
			this.vmethod_110().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_110().Name = "Label21";
			this.vmethod_110().Size = new global::System.Drawing.Size(207, 16);
			this.vmethod_110().TabIndex = 30;
			this.vmethod_110().Text = "反舰作战行动";
			this.vmethod_158().Location = new global::System.Drawing.Point(498, 181);
			this.vmethod_158().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_158().Name = "Label27";
			this.vmethod_158().Size = new global::System.Drawing.Size(150, 13);
			this.vmethod_158().TabIndex = 5;
			this.vmethod_158().Text = "空对地扫射(航炮):";
			this.vmethod_162().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_162().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_162().FormattingEnabled = true;
			this.vmethod_162().Location = new global::System.Drawing.Point(718, 178);
			this.vmethod_162().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_162().Name = "Combo_GunStrafing";
			this.vmethod_162().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_162().TabIndex = 19;
			this.vmethod_160().Location = new global::System.Drawing.Point(974, 181);
			this.vmethod_160().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_160().Name = "CB_GunStrafing_PlayerEditable";
			this.vmethod_160().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_160().TabIndex = 48;
			this.vmethod_160().Text = "允许用户编辑";
			this.vmethod_160().UseVisualStyleBackColor = true;
			this.vmethod_50().Location = new global::System.Drawing.Point(498, 156);
			this.vmethod_50().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_50().Name = "Label4";
			this.vmethod_50().Size = new global::System.Drawing.Size(104, 13);
			this.vmethod_50().TabIndex = 5;
			this.vmethod_50().Text = "武器状态-返航:";
			this.vmethod_52().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_52().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_52().DropDownWidth = 550;
			this.vmethod_52().FormattingEnabled = true;
			this.vmethod_52().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_52().Location = new global::System.Drawing.Point(718, 153);
			this.vmethod_52().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_52().Name = "Combo_WeaponStateRTB";
			this.vmethod_52().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_52().TabIndex = 18;
			this.vmethod_42().Location = new global::System.Drawing.Point(974, 156);
			this.vmethod_42().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_42().Name = "CB_WeaponStateRTB_PlayerEditable";
			this.vmethod_42().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_42().TabIndex = 47;
			this.vmethod_42().Text = "允许用户编辑";
			this.vmethod_42().UseVisualStyleBackColor = true;
			this.vmethod_166().Location = new global::System.Drawing.Point(498, 131);
			this.vmethod_166().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_166().Name = "Label29";
			this.vmethod_166().Size = new global::System.Drawing.Size(143, 13);
			this.vmethod_166().TabIndex = 5;
			this.vmethod_166().Text = "武器状态, 预先规划:";
			this.vmethod_172().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_172().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_172().DropDownWidth = 750;
			this.vmethod_172().FormattingEnabled = true;
			this.vmethod_172().Location = new global::System.Drawing.Point(718, 128);
			this.vmethod_172().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_172().Name = "Combo_WeaponState";
			this.vmethod_172().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_172().TabIndex = 17;
			this.vmethod_176().Location = new global::System.Drawing.Point(974, 131);
			this.vmethod_176().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_176().Name = "CB_WeaponState_PlayerEditable";
			this.vmethod_176().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_176().TabIndex = 46;
			this.vmethod_176().Text = "允许用户编辑";
			this.vmethod_176().UseVisualStyleBackColor = true;
			this.vmethod_178().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_178().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_178().FormattingEnabled = true;
			this.vmethod_178().Location = new global::System.Drawing.Point(718, 203);
			this.vmethod_178().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_178().Name = "Combo_Jettison";
			this.vmethod_178().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_178().TabIndex = 20;
			this.vmethod_180().Location = new global::System.Drawing.Point(498, 206);
			this.vmethod_180().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_180().Name = "Label31";
			this.vmethod_180().Size = new global::System.Drawing.Size(96, 13);
			this.vmethod_180().TabIndex = 5;
			this.vmethod_180().Text = "抛弃弹药:";
			this.vmethod_182().Location = new global::System.Drawing.Point(974, 206);
			this.vmethod_182().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_182().Name = "CB_JettisonOrdnance_PlayerEditable";
			this.vmethod_182().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_182().TabIndex = 49;
			this.vmethod_182().Text = "允许用户编辑";
			this.vmethod_182().UseVisualStyleBackColor = true;
			this.vmethod_184().Location = new global::System.Drawing.Point(974, 106);
			this.vmethod_184().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_184().Name = "CB_FuelStateRTB_PlayerEditable";
			this.vmethod_184().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_184().TabIndex = 45;
			this.vmethod_184().Text = "允许用户编辑";
			this.vmethod_184().UseVisualStyleBackColor = true;
			this.vmethod_186().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_186().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_186().DropDownWidth = 550;
			this.vmethod_186().FormattingEnabled = true;
			this.vmethod_186().Location = new global::System.Drawing.Point(718, 103);
			this.vmethod_186().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_186().Name = "Combo_FuelStateRTB";
			this.vmethod_186().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_186().TabIndex = 16;
			this.vmethod_188().Location = new global::System.Drawing.Point(498, 106);
			this.vmethod_188().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_188().Name = "Label32";
			this.vmethod_188().Size = new global::System.Drawing.Size(100, 13);
			this.vmethod_188().TabIndex = 5;
			this.vmethod_188().Text = "燃油状态—返航:";
			this.vmethod_194().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f, global::System.Drawing.FontStyle.Bold);
			this.vmethod_194().Location = new global::System.Drawing.Point(498, 309);
			this.vmethod_194().Margin = new global::System.Windows.Forms.Padding(0, 9, 0, 0);
			this.vmethod_194().Name = "Label34";
			this.vmethod_194().Size = new global::System.Drawing.Size(220, 16);
			this.vmethod_194().TabIndex = 30;
			this.vmethod_194().Text = "反潜作战行动";
			this.vmethod_198().Location = new global::System.Drawing.Point(498, 331);
			this.vmethod_198().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_198().Name = "Label35";
			this.vmethod_198().Size = new global::System.Drawing.Size(76, 13);
			this.vmethod_198().TabIndex = 11;
			this.vmethod_198().Text = "规避搜索:";
			this.vmethod_200().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_200().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_200().FormattingEnabled = true;
			this.vmethod_200().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_200().Location = new global::System.Drawing.Point(718, 328);
			this.vmethod_200().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_200().Name = "Combo_AvoidContact";
			this.vmethod_200().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_200().TabIndex = 23;
			this.vmethod_202().Location = new global::System.Drawing.Point(498, 356);
			this.vmethod_202().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_202().Name = "Label36";
			this.vmethod_202().Size = new global::System.Drawing.Size(146, 13);
			this.vmethod_202().TabIndex = 11;
			this.vmethod_202().Text = "探测到威胁进行下潜:";
			this.vmethod_204().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_204().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_204().DropDownWidth = 450;
			this.vmethod_204().FormattingEnabled = true;
			this.vmethod_204().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_204().Location = new global::System.Drawing.Point(718, 353);
			this.vmethod_204().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_204().Name = "Combo_DiveWhenThreatsDetected";
			this.vmethod_204().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_204().TabIndex = 24;
			this.vmethod_206().Location = new global::System.Drawing.Point(974, 331);
			this.vmethod_206().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_206().Name = "CB_AvoidContact_PlayerEditable";
			this.vmethod_206().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_206().TabIndex = 52;
			this.vmethod_206().Text = "允许用户编辑";
			this.vmethod_206().UseVisualStyleBackColor = true;
			this.vmethod_208().Location = new global::System.Drawing.Point(974, 356);
			this.vmethod_208().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_208().Name = "CB_DiveWhenThreatsDetected_PlayerEditable";
			this.vmethod_208().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_208().TabIndex = 53;
			this.vmethod_208().Text = "允许用户编辑";
			this.vmethod_208().UseVisualStyleBackColor = true;
			this.vmethod_210().Location = new global::System.Drawing.Point(498, 381);
			this.vmethod_210().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_210().Name = "Label37";
			this.vmethod_210().Size = new global::System.Drawing.Size(179, 13);
			this.vmethod_210().TabIndex = 11;
			this.vmethod_210().Text = "电池充电 %, 出航/阵位:";
			this.vmethod_212().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_212().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_212().FormattingEnabled = true;
			this.vmethod_212().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_212().Location = new global::System.Drawing.Point(718, 378);
			this.vmethod_212().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_212().Name = "Combo_BatteryRechargePatrol";
			this.vmethod_212().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_212().TabIndex = 25;
			this.vmethod_214().Location = new global::System.Drawing.Point(974, 381);
			this.vmethod_214().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_214().Name = "CB_BatteryRechargePatrol_PlayerEditable";
			this.vmethod_214().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_214().TabIndex = 54;
			this.vmethod_214().Text = "允许用户编辑";
			this.vmethod_214().UseVisualStyleBackColor = true;
			this.vmethod_216().Location = new global::System.Drawing.Point(498, 406);
			this.vmethod_216().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_216().Name = "Label38";
			this.vmethod_216().Size = new global::System.Drawing.Size(209, 13);
			this.vmethod_216().TabIndex = 11;
			this.vmethod_216().Text = "电池充电%, 进攻/防御:";
			this.vmethod_218().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_218().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_218().FormattingEnabled = true;
			this.vmethod_218().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_218().Location = new global::System.Drawing.Point(718, 403);
			this.vmethod_218().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_218().Name = "Combo_BatteryRechargeAttack";
			this.vmethod_218().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_218().TabIndex = 26;
			this.vmethod_220().Location = new global::System.Drawing.Point(974, 406);
			this.vmethod_220().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_220().Name = "CB_BatteryRechargeAttack_PlayerEditable";
			this.vmethod_220().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_220().TabIndex = 55;
			this.vmethod_220().Text = "允许用户编辑";
			this.vmethod_220().UseVisualStyleBackColor = true;
			this.vmethod_222().Location = new global::System.Drawing.Point(498, 431);
			this.vmethod_222().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_222().Name = "Label39";
			this.vmethod_222().Size = new global::System.Drawing.Size(195, 13);
			this.vmethod_222().TabIndex = 11;
			this.vmethod_222().Text = "使用AIP推进技术:";
			this.vmethod_224().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_224().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_224().DropDownWidth = 450;
			this.vmethod_224().FormattingEnabled = true;
			this.vmethod_224().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_224().Location = new global::System.Drawing.Point(718, 428);
			this.vmethod_224().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_224().Name = "Combo_AIP_Usage";
			this.vmethod_224().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_224().TabIndex = 27;
			this.vmethod_226().Location = new global::System.Drawing.Point(974, 431);
			this.vmethod_226().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_226().Name = "CB_AIP_Usage_PlayerEditable";
			this.vmethod_226().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_226().TabIndex = 56;
			this.vmethod_226().Text = "允许用户编辑";
			this.vmethod_226().UseVisualStyleBackColor = true;
			this.vmethod_228().Location = new global::System.Drawing.Point(498, 456);
			this.vmethod_228().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_228().Name = "Label40";
			this.vmethod_228().Size = new global::System.Drawing.Size(75, 13);
			this.vmethod_228().TabIndex = 11;
			this.vmethod_228().Text = "吊放声纳:";
			this.vmethod_230().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_230().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_230().DropDownWidth = 450;
			this.vmethod_230().FormattingEnabled = true;
			this.vmethod_230().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_230().Location = new global::System.Drawing.Point(718, 453);
			this.vmethod_230().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_230().Name = "Combo_DippingSonar";
			this.vmethod_230().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_230().TabIndex = 28;
			this.vmethod_232().Location = new global::System.Drawing.Point(974, 456);
			this.vmethod_232().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_232().Name = "CB_DippingSonar_PlayerEditable";
			this.vmethod_232().Size = new global::System.Drawing.Size(17, 16);
			this.vmethod_232().TabIndex = 57;
			this.vmethod_232().Text = "允许用户编辑";
			this.vmethod_232().UseVisualStyleBackColor = true;
			this.vmethod_192().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_192().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_192().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_192().FormattingEnabled = true;
			this.vmethod_192().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_192().Location = new global::System.Drawing.Point(215, 428);
			this.vmethod_192().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_192().Name = "Combo_RefuelAllies";
			this.vmethod_192().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_192().TabIndex = 12;
			this.vmethod_196().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_196().Location = new global::System.Drawing.Point(471, 431);
			this.vmethod_196().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_196().Name = "CB_RefuelAllies_PlayerEditable";
			this.vmethod_196().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_196().TabIndex = 41;
			this.vmethod_196().UseVisualStyleBackColor = true;
			this.vmethod_190().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.vmethod_190().Location = new global::System.Drawing.Point(0, 431);
			this.vmethod_190().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_190().Name = "Label33";
			this.vmethod_190().Size = new global::System.Drawing.Size(150, 15);
			this.vmethod_190().TabIndex = 15;
			this.vmethod_190().Text = "对盟军单元进行加油/补给:";
			this.vmethod_282().AutoSize = true;
			this.vmethod_282().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.vmethod_282().Location = new global::System.Drawing.Point(0, 406);
			this.vmethod_282().Margin = new global::System.Windows.Forms.Padding(0, 6, 0, 0);
			this.vmethod_282().Name = "Label51";
			this.vmethod_282().Size = new global::System.Drawing.Size(150, 15);
			this.vmethod_282().TabIndex = 15;
			this.vmethod_282().Text = "对所选单元进行加油/补给:";
			this.vmethod_284().AutoSize = true;
			this.vmethod_284().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_284().Location = new global::System.Drawing.Point(471, 406);
			this.vmethod_284().Margin = new global::System.Windows.Forms.Padding(3, 6, 3, 3);
			this.vmethod_284().Name = "CB_RefuelSelection_PlayerEditable";
			this.vmethod_284().Size = new global::System.Drawing.Size(15, 14);
			this.vmethod_284().TabIndex = 40;
			this.vmethod_284().UseVisualStyleBackColor = true;
			this.vmethod_286().Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.vmethod_286().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_286().DropDownWidth = 450;
			this.vmethod_286().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_286().FormattingEnabled = true;
			this.vmethod_286().Items.AddRange(new object[]
			{
				"Yes",
				"No",
				"Inherit"
			});
			this.vmethod_286().Location = new global::System.Drawing.Point(215, 403);
			this.vmethod_286().Margin = new global::System.Windows.Forms.Padding(0, 3, 0, 3);
			this.vmethod_286().Name = "Combo_RefuelSelection";
			this.vmethod_286().Size = new global::System.Drawing.Size(253, 21);
			this.vmethod_286().TabIndex = 11;
			this.vmethod_4().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_4().Controls.Add(this.GetButton_ResetAffectedMissions_EMCON());
			this.vmethod_4().Controls.Add(this.GetButton_ResetAffectedUnits_EMCON());
			this.vmethod_4().Controls.Add(this.GetButton_ResetCurrent_EMCON());
			this.vmethod_4().Controls.Add(this.GetCB_EMCON_Sonar());
			this.vmethod_4().Controls.Add(this.vmethod_18());
			this.vmethod_4().Controls.Add(this.GetCB_EMCON_OECM());
			this.vmethod_4().Controls.Add(this.vmethod_14());
			this.vmethod_4().Controls.Add(this.GetCB_EMCON_Inherits());
			this.vmethod_4().Controls.Add(this.GetCB_EMCON_Radar());
			this.vmethod_4().Controls.Add(this.vmethod_8());
			this.vmethod_4().Location = new global::System.Drawing.Point(4, 22);
			this.vmethod_4().Name = "TabPage2";
			this.vmethod_4().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_4().Size = new global::System.Drawing.Size(1000, 665);
			this.vmethod_4().TabIndex = 1;
			this.vmethod_4().Text = "电磁管控设置";
			this.GetButton_ResetAffectedMissions_EMCON().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ResetAffectedMissions_EMCON().Location = new global::System.Drawing.Point(531, 631);
			this.GetButton_ResetAffectedMissions_EMCON().Name = "Button_ResetAffectedMissions_EMCON";
			this.GetButton_ResetAffectedMissions_EMCON().Size = new global::System.Drawing.Size(265, 23);
			this.GetButton_ResetAffectedMissions_EMCON().TabIndex = 14;
			this.GetButton_ResetAffectedMissions_EMCON().Text = "重置关联的作战任务(与上级EMCON设置保持一致)";
			this.GetButton_ResetAffectedMissions_EMCON().UseVisualStyleBackColor = true;
			this.GetButton_ResetAffectedUnits_EMCON().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ResetAffectedUnits_EMCON().Location = new global::System.Drawing.Point(265, 631);
			this.GetButton_ResetAffectedUnits_EMCON().Name = "Button_ResetAffectedUnits_EMCON";
			this.GetButton_ResetAffectedUnits_EMCON().Size = new global::System.Drawing.Size(265, 23);
			this.GetButton_ResetAffectedUnits_EMCON().TabIndex = 13;
			this.GetButton_ResetAffectedUnits_EMCON().Text = "重置关联的作战单元(使用上级EMCON设置)";
			this.GetButton_ResetAffectedUnits_EMCON().UseVisualStyleBackColor = true;
			this.GetButton_ResetCurrent_EMCON().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ResetCurrent_EMCON().Location = new global::System.Drawing.Point(-1, 631);
			this.GetButton_ResetCurrent_EMCON().Name = "Button_ResetCurrent_EMCON";
			this.GetButton_ResetCurrent_EMCON().Size = new global::System.Drawing.Size(265, 23);
			this.GetButton_ResetCurrent_EMCON().TabIndex = 12;
			this.GetButton_ResetCurrent_EMCON().Text = "重置电磁管控规则(使用上级设置)";
			this.GetButton_ResetCurrent_EMCON().UseVisualStyleBackColor = true;
			this.GetCB_EMCON_Sonar().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_EMCON_Sonar().FormattingEnabled = true;
			this.GetCB_EMCON_Sonar().Location = new global::System.Drawing.Point(51, 95);
			this.GetCB_EMCON_Sonar().Name = "CB_EMCON_Sonar";
			this.GetCB_EMCON_Sonar().Size = new global::System.Drawing.Size(146, 21);
			this.GetCB_EMCON_Sonar().TabIndex = 6;
			this.vmethod_18().Location = new global::System.Drawing.Point(5, 98);
			this.vmethod_18().Name = "Label9";
			this.vmethod_18().Size = new global::System.Drawing.Size(50, 13);
			this.vmethod_18().TabIndex = 5;
			this.vmethod_18().Text = "声纳:";
			this.GetCB_EMCON_OECM().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_EMCON_OECM().FormattingEnabled = true;
			this.GetCB_EMCON_OECM().Location = new global::System.Drawing.Point(51, 68);
			this.GetCB_EMCON_OECM().Name = "CB_EMCON_OECM";
			this.GetCB_EMCON_OECM().Size = new global::System.Drawing.Size(146, 21);
			this.GetCB_EMCON_OECM().TabIndex = 4;
			this.vmethod_14().Location = new global::System.Drawing.Point(5, 71);
			this.vmethod_14().Name = "Label8";
			this.vmethod_14().Size = new global::System.Drawing.Size(51, 13);
			this.vmethod_14().TabIndex = 3;
			this.vmethod_14().Text = "干扰机:";
			this.GetCB_EMCON_Inherits().Location = new global::System.Drawing.Point(8, 6);
			this.GetCB_EMCON_Inherits().Name = "CB_EMCON_Inherits";
			this.GetCB_EMCON_Inherits().Size = new global::System.Drawing.Size(111, 17);
			this.GetCB_EMCON_Inherits().TabIndex = 2;
			this.GetCB_EMCON_Inherits().Text = "与上级保持一致";
			this.GetCB_EMCON_Inherits().UseVisualStyleBackColor = true;
			this.GetCB_EMCON_Radar().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_EMCON_Radar().FormattingEnabled = true;
			this.GetCB_EMCON_Radar().Location = new global::System.Drawing.Point(51, 41);
			this.GetCB_EMCON_Radar().Name = "CB_EMCON_Radar";
			this.GetCB_EMCON_Radar().Size = new global::System.Drawing.Size(146, 21);
			this.GetCB_EMCON_Radar().TabIndex = 1;
			this.vmethod_8().Location = new global::System.Drawing.Point(5, 44);
			this.vmethod_8().Name = "Label3";
			this.vmethod_8().Size = new global::System.Drawing.Size(50, 13);
			this.vmethod_8().TabIndex = 0;
			this.vmethod_8().Text = "雷达:";
			this.vmethod_20().Controls.Add(this.GetButton_ResetAffectedMissions_WRA());
			this.vmethod_20().Controls.Add(this.GetButton_ResetAffectedUnits_WRA());
			this.vmethod_20().Controls.Add(this.GetButton_ResetCurrent_WRA());
			this.vmethod_20().Controls.Add(this.GetTGV_WRA());
			this.vmethod_20().Location = new global::System.Drawing.Point(4, 22);
			this.vmethod_20().Name = "TabPage3";
			this.vmethod_20().Padding = new global::System.Windows.Forms.Padding(3);
			this.vmethod_20().Size = new global::System.Drawing.Size(1000, 665);
			this.vmethod_20().TabIndex = 2;
			this.vmethod_20().Text = "武器使用规则";
			this.vmethod_20().UseVisualStyleBackColor = true;
			this.GetButton_ResetAffectedMissions_WRA().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ResetAffectedMissions_WRA().Location = new global::System.Drawing.Point(531, 643);
			this.GetButton_ResetAffectedMissions_WRA().Name = "Button_ResetAffectedMissions_WRA";
			this.GetButton_ResetAffectedMissions_WRA().Size = new global::System.Drawing.Size(265, 23);
			this.GetButton_ResetAffectedMissions_WRA().TabIndex = 11;
			this.GetButton_ResetAffectedMissions_WRA().Text = "重置关联的作战任务(与上级保持一致)";
			this.GetButton_ResetAffectedMissions_WRA().UseVisualStyleBackColor = true;
			this.GetButton_ResetAffectedUnits_WRA().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ResetAffectedUnits_WRA().Location = new global::System.Drawing.Point(265, 643);
			this.GetButton_ResetAffectedUnits_WRA().Name = "Button_ResetAffectedUnits_WRA";
			this.GetButton_ResetAffectedUnits_WRA().Size = new global::System.Drawing.Size(265, 23);
			this.GetButton_ResetAffectedUnits_WRA().TabIndex = 10;
			this.GetButton_ResetAffectedUnits_WRA().Text = "重置关联的作战单元(与上级保持一致)";
			this.GetButton_ResetAffectedUnits_WRA().UseVisualStyleBackColor = true;
			this.GetButton_ResetCurrent_WRA().Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.GetButton_ResetCurrent_WRA().Location = new global::System.Drawing.Point(-1, 643);
			this.GetButton_ResetCurrent_WRA().Name = "Button_ResetCurrent_WRA";
			this.GetButton_ResetCurrent_WRA().Size = new global::System.Drawing.Size(265, 23);
			this.GetButton_ResetCurrent_WRA().TabIndex = 9;
			this.GetButton_ResetCurrent_WRA().Text = "重置武器使用规则(使用继承的设置)";
			this.GetButton_ResetCurrent_WRA().UseVisualStyleBackColor = true;
			this.vmethod_234().BackColor = global::System.Drawing.SystemColors.Control;
			this.vmethod_234().Controls.Add(this.GetCombo_RedeployDefenceThreshold());
			this.vmethod_234().Controls.Add(this.GetCombo_RedeployAttackThreshold());
			this.vmethod_234().Controls.Add(this.GetCombo_RedeployFuelThreshold());
			this.vmethod_234().Controls.Add(this.vmethod_260());
			this.vmethod_234().Controls.Add(this.vmethod_262());
			this.vmethod_234().Controls.Add(this.vmethod_264());
			this.vmethod_234().Controls.Add(this.vmethod_266());
			this.vmethod_234().Controls.Add(this.vmethod_268());
			this.vmethod_234().Controls.Add(this.vmethod_270());
			this.vmethod_234().Controls.Add(this.GetCombo_WithdrawDefenceThreshold());
			this.vmethod_234().Controls.Add(this.GetCombo_WithdrawAttackThreshold());
			this.vmethod_234().Controls.Add(this.GetCombo_WithdrawFuelThreshold());
			this.vmethod_234().Controls.Add(this.vmethod_242());
			this.vmethod_234().Controls.Add(this.vmethod_244());
			this.vmethod_234().Controls.Add(this.vmethod_246());
			this.vmethod_234().Controls.Add(this.vmethod_248());
			this.vmethod_234().Controls.Add(this.GetCombo_WithdrawDamageThreshold());
			this.vmethod_234().Controls.Add(this.vmethod_252());
			this.vmethod_234().Location = new global::System.Drawing.Point(4, 22);
			this.vmethod_234().Name = "TabPage4";
			this.vmethod_234().Size = new global::System.Drawing.Size(1000, 665);
			this.vmethod_234().TabIndex = 3;
			this.vmethod_234().Text = "撤退与重新部署";
			this.GetCombo_RedeployDefenceThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_RedeployDefenceThreshold().FormattingEnabled = true;
			this.GetCombo_RedeployDefenceThreshold().Location = new global::System.Drawing.Point(246, 307);
			this.GetCombo_RedeployDefenceThreshold().Name = "Combo_RedeployDefenceThreshold";
			this.GetCombo_RedeployDefenceThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_RedeployDefenceThreshold().TabIndex = 17;
			this.GetCombo_RedeployAttackThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_RedeployAttackThreshold().FormattingEnabled = true;
			this.GetCombo_RedeployAttackThreshold().Location = new global::System.Drawing.Point(246, 280);
			this.GetCombo_RedeployAttackThreshold().Name = "Combo_RedeployAttackThreshold";
			this.GetCombo_RedeployAttackThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_RedeployAttackThreshold().TabIndex = 16;
			this.GetCombo_RedeployFuelThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_RedeployFuelThreshold().FormattingEnabled = true;
			this.GetCombo_RedeployFuelThreshold().Location = new global::System.Drawing.Point(246, 253);
			this.GetCombo_RedeployFuelThreshold().Name = "Combo_RedeployFuelThreshold";
			this.GetCombo_RedeployFuelThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_RedeployFuelThreshold().TabIndex = 15;
			this.vmethod_260().Location = new global::System.Drawing.Point(10, 310);
			this.vmethod_260().Name = "Label46";
			this.vmethod_260().Size = new global::System.Drawing.Size(229, 13);
			this.vmethod_260().TabIndex = 14;
			this.vmethod_260().Text = "且 主要防御武器至少处于:";
			this.vmethod_262().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 16f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_262().Location = new global::System.Drawing.Point(8, 185);
			this.vmethod_262().Name = "Label47";
			this.vmethod_262().Size = new global::System.Drawing.Size(300, 26);
			this.vmethod_262().TabIndex = 13;
			this.vmethod_262().Text = "满足如下条件时重新部署";
			this.vmethod_264().Location = new global::System.Drawing.Point(10, 283);
			this.vmethod_264().Name = "Label48";
			this.vmethod_264().Size = new global::System.Drawing.Size(220, 13);
			this.vmethod_264().TabIndex = 11;
			this.vmethod_264().Text = "且 主要攻击武器处于:";
			this.vmethod_266().Location = new global::System.Drawing.Point(10, 256);
			this.vmethod_266().Name = "Label49";
			this.vmethod_266().Size = new global::System.Drawing.Size(115, 13);
			this.vmethod_266().TabIndex = 12;
			this.vmethod_266().Text = "且 燃油至少处于:";
			this.vmethod_268().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_268().FormattingEnabled = true;
			this.vmethod_268().Location = new global::System.Drawing.Point(246, 226);
			this.vmethod_268().Name = "Combo_RedeployDamageThreshold";
			this.vmethod_268().Size = new global::System.Drawing.Size(159, 21);
			this.vmethod_268().TabIndex = 10;
			this.vmethod_270().Location = new global::System.Drawing.Point(10, 229);
			this.vmethod_270().Name = "Label50";
			this.vmethod_270().Size = new global::System.Drawing.Size(105, 13);
			this.vmethod_270().TabIndex = 9;
			this.vmethod_270().Text = "毁伤程度小于:";
			this.GetCombo_WithdrawDefenceThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_WithdrawDefenceThreshold().FormattingEnabled = true;
			this.GetCombo_WithdrawDefenceThreshold().Location = new global::System.Drawing.Point(246, 135);
			this.GetCombo_WithdrawDefenceThreshold().Name = "Combo_WithdrawDefenceThreshold";
			this.GetCombo_WithdrawDefenceThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_WithdrawDefenceThreshold().TabIndex = 8;
			this.GetCombo_WithdrawAttackThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_WithdrawAttackThreshold().FormattingEnabled = true;
			this.GetCombo_WithdrawAttackThreshold().Location = new global::System.Drawing.Point(246, 108);
			this.GetCombo_WithdrawAttackThreshold().Name = "Combo_WithdrawAttackThreshold";
			this.GetCombo_WithdrawAttackThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_WithdrawAttackThreshold().TabIndex = 7;
			this.GetCombo_WithdrawFuelThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_WithdrawFuelThreshold().FormattingEnabled = true;
			this.GetCombo_WithdrawFuelThreshold().Location = new global::System.Drawing.Point(246, 81);
			this.GetCombo_WithdrawFuelThreshold().Name = "Combo_WithdrawFuelThreshold";
			this.GetCombo_WithdrawFuelThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_WithdrawFuelThreshold().TabIndex = 6;
			this.vmethod_242().Location = new global::System.Drawing.Point(10, 138);
			this.vmethod_242().Name = "Label45";
			this.vmethod_242().Size = new global::System.Drawing.Size(230, 13);
			this.vmethod_242().TabIndex = 5;
			this.vmethod_242().Text = "或 主要防御武器至少:";
			this.vmethod_244().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 16f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_244().Location = new global::System.Drawing.Point(8, 13);
			this.vmethod_244().Name = "Label43";
			this.vmethod_244().Size = new global::System.Drawing.Size(300, 26);
			this.vmethod_244().TabIndex = 4;
			this.vmethod_244().Text = "满足如下条件时撤退";
			this.vmethod_246().Location = new global::System.Drawing.Point(10, 111);
			this.vmethod_246().Name = "Label44";
			this.vmethod_246().Size = new global::System.Drawing.Size(221, 13);
			this.vmethod_246().TabIndex = 2;
			this.vmethod_246().Text = "或 主要攻击武器至少处于:";
			this.vmethod_248().Location = new global::System.Drawing.Point(10, 84);
			this.vmethod_248().Name = "Label42";
			this.vmethod_248().Size = new global::System.Drawing.Size(104, 13);
			this.vmethod_248().TabIndex = 2;
			this.vmethod_248().Text = "或 燃油少于:";
			this.GetCombo_WithdrawDamageThreshold().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCombo_WithdrawDamageThreshold().FormattingEnabled = true;
			this.GetCombo_WithdrawDamageThreshold().Location = new global::System.Drawing.Point(246, 54);
			this.GetCombo_WithdrawDamageThreshold().Name = "Combo_WithdrawDamageThreshold";
			this.GetCombo_WithdrawDamageThreshold().Size = new global::System.Drawing.Size(159, 21);
			this.GetCombo_WithdrawDamageThreshold().TabIndex = 1;
			this.vmethod_252().Location = new global::System.Drawing.Point(10, 57);
			this.vmethod_252().Name = "Label41";
			this.vmethod_252().Size = new global::System.Drawing.Size(110, 13);
			this.vmethod_252().TabIndex = 0;
			this.vmethod_252().Text = "毁伤程度大于:";
			this.GetTargetType().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.GetTargetType().SetImage(null);
			this.GetTargetType().HeaderText = "武器—目标类型";
			this.GetTargetType().Name = "TargetType";
			this.GetTargetType().Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.GetTargetType().SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.GetWeaponsPerSalvo().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
			this.GetWeaponsPerSalvo().DropDownWidth = 2;
			this.GetWeaponsPerSalvo().FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.GetWeaponsPerSalvo().HeaderText = "齐射武器数";
			this.GetWeaponsPerSalvo().MaxDropDownItems = 20;
			this.GetWeaponsPerSalvo().MinimumWidth = 170;
			this.GetWeaponsPerSalvo().Name = "WeaponsPerSalvo";
			this.GetWeaponsPerSalvo().Width = 170;
			this.GetShootersPerSalvo().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
			this.GetShootersPerSalvo().DropDownWidth = 2;
			this.GetShootersPerSalvo().FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.GetShootersPerSalvo().HeaderText = "齐射发射架数";
			this.GetShootersPerSalvo().MaxDropDownItems = 20;
			this.GetShootersPerSalvo().MinimumWidth = 170;
			this.GetShootersPerSalvo().Name = "ShootersPerSalvo";
			this.GetShootersPerSalvo().Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.GetShootersPerSalvo().Width = 170;
			this.GetFiringRange().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
			this.GetFiringRange().DropDownWidth = 2;
			this.GetFiringRange().FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.GetFiringRange().HeaderText = "自动开火距离";
			this.GetFiringRange().MinimumWidth = 170;
			this.GetFiringRange().Name = "FiringRange";
			this.GetFiringRange().Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.GetFiringRange().Width = 170;
			this.GetSelfDefenceRange().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.None;
			this.GetSelfDefenceRange().DropDownWidth = 2;
			this.GetSelfDefenceRange().FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.GetSelfDefenceRange().HeaderText = "自防御距离";
			this.GetSelfDefenceRange().MaxDropDownItems = 20;
			this.GetSelfDefenceRange().MinimumWidth = 170;
			this.GetSelfDefenceRange().Name = "SelfDefenceRange";
			this.GetSelfDefenceRange().Width = 170;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(1008, 691);
			base.Controls.Add(this.vmethod_0());
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "DoctrineForm";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "作战条令对话框";
			((global::System.ComponentModel.ISupportInitialize)this.GetTGV_WRA()).EndInit();
			this.vmethod_0().ResumeLayout(false);
			this.vmethod_2().ResumeLayout(false);
			this.vmethod_26().ResumeLayout(false);
			this.vmethod_26().PerformLayout();
			this.vmethod_4().ResumeLayout(false);
			this.vmethod_20().ResumeLayout(false);
			this.vmethod_234().ResumeLayout(false);
			base.ResumeLayout(false);
		}

		// Token: 0x04003167 RID: 12647
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
