namespace Command
{
	// Token: 0x02000B6C RID: 2924
	public sealed partial class EditEvent : global::ns33.CommandForm
	{
		// Token: 0x06006057 RID: 24663 RVA: 0x002DD49C File Offset: 0x002DB69C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06006058 RID: 24664 RVA: 0x002DD4E0 File Offset: 0x002DB6E0
		private void InitializeComponent()
		{
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.vmethod_1(new global::System.Windows.Forms.TextBox());
			this.vmethod_3(new global::System.Windows.Forms.Label());
			this.vmethod_5(new global::System.Windows.Forms.Label());
			this.vmethod_7(new global::System.Windows.Forms.DataGridView());
			this.vmethod_9(new global::System.Windows.Forms.DataGridViewTextBoxColumn());
			this.vmethod_11(new global::System.Windows.Forms.DataGridViewTextBoxColumn());
			this.vmethod_13(new global::System.Windows.Forms.DataGridView());
			this.vmethod_15(new global::System.Windows.Forms.DataGridViewTextBoxColumn());
			this.vmethod_17(new global::System.Windows.Forms.DataGridViewTextBoxColumn());
			this.vmethod_19(new global::System.Windows.Forms.Label());
			this.vmethod_21(new global::System.Windows.Forms.DataGridView());
			this.vmethod_23(new global::System.Windows.Forms.DataGridViewTextBoxColumn());
			this.vmethod_25(new global::System.Windows.Forms.DataGridViewTextBoxColumn());
			this.vmethod_27(new global::System.Windows.Forms.Label());
			this.vmethod_29(new global::System.Windows.Forms.Button());
			this.vmethod_31(new global::System.Windows.Forms.ComboBox());
			this.vmethod_33(new global::System.Windows.Forms.Button());
			this.vmethod_35(new global::System.Windows.Forms.Button());
			this.vmethod_37(new global::System.Windows.Forms.ComboBox());
			this.vmethod_39(new global::System.Windows.Forms.Button());
			this.vmethod_41(new global::System.Windows.Forms.Button());
			this.vmethod_43(new global::System.Windows.Forms.ComboBox());
			this.vmethod_45(new global::System.Windows.Forms.Button());
			this.vmethod_47(new global::System.Windows.Forms.Button());
			this.vmethod_49(new global::System.Windows.Forms.Button());
			this.vmethod_51(new global::System.Windows.Forms.CheckBox());
			this.vmethod_53(new global::System.Windows.Forms.CheckBox());
			this.vmethod_55(new global::System.Windows.Forms.Label());
			this.vmethod_57(new global::System.Windows.Forms.NumericUpDown());
			this.vmethod_59(new global::System.Windows.Forms.Button());
			this.vmethod_61(new global::System.Windows.Forms.Button());
			this.vmethod_63(new global::System.Windows.Forms.Button());
			this.vmethod_65(new global::System.Windows.Forms.CheckBox());
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_6()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_12()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_20()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_56()).BeginInit();
			base.SuspendLayout();
			this.vmethod_0().Location = new global::System.Drawing.Point(91, 3);
			this.vmethod_0().Name = "TextBox1";
			this.vmethod_0().Size = new global::System.Drawing.Size(691, 20);
			this.vmethod_0().TabIndex = 8;
			this.vmethod_2().AutoSize = true;
			this.vmethod_2().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_2().Location = new global::System.Drawing.Point(5, 7);
			this.vmethod_2().Name = "Label2";
			this.vmethod_2().Size = new global::System.Drawing.Size(75, 13);
			this.vmethod_2().TabIndex = 7;
			this.vmethod_2().Text = "描述:";
			this.vmethod_4().AutoSize = true;
			this.vmethod_4().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_4().Location = new global::System.Drawing.Point(5, 67);
			this.vmethod_4().Name = "Label1";
			this.vmethod_4().Size = new global::System.Drawing.Size(57, 13);
			this.vmethod_4().TabIndex = 9;
			this.vmethod_4().Text = "触发器:";
			this.vmethod_6().AllowUserToAddRows = false;
			this.vmethod_6().AllowUserToDeleteRows = false;
			this.vmethod_6().BackgroundColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.vmethod_6().ColumnHeadersDefaultCellStyle = dataGridViewCellStyle;
			this.vmethod_6().ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.vmethod_6().Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.vmethod_8(),
				this.vmethod_10()
			});
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.vmethod_6().DefaultCellStyle = dataGridViewCellStyle2;
			this.vmethod_6().EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.vmethod_6().Location = new global::System.Drawing.Point(8, 83);
			this.vmethod_6().MultiSelect = false;
			this.vmethod_6().Name = "DGV_Triggers";
			this.vmethod_6().ReadOnly = true;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.vmethod_6().RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
			this.vmethod_6().SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.vmethod_6().ShowCellToolTips = false;
			this.vmethod_6().ShowEditingIcon = false;
			this.vmethod_6().ShowRowErrors = false;
			this.vmethod_6().Size = new global::System.Drawing.Size(774, 100);
			this.vmethod_6().TabIndex = 10;
			this.vmethod_8().DataPropertyName = "ID";
			this.vmethod_8().HeaderText = "ID";
			this.vmethod_8().Name = "ID";
			this.vmethod_8().ReadOnly = true;
			this.vmethod_8().Visible = false;
			this.vmethod_10().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.vmethod_10().DataPropertyName = "Description";
			this.vmethod_10().HeaderText = "描述";
			this.vmethod_10().Name = "Description";
			this.vmethod_10().ReadOnly = true;
			this.vmethod_12().AllowUserToAddRows = false;
			this.vmethod_12().AllowUserToDeleteRows = false;
			this.vmethod_12().BackgroundColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle4.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle4.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle4.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle4.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle4.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle4.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.vmethod_12().ColumnHeadersDefaultCellStyle = dataGridViewCellStyle4;
			this.vmethod_12().ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.vmethod_12().Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.vmethod_14(),
				this.vmethod_16()
			});
			dataGridViewCellStyle5.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle5.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle5.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle5.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle5.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle5.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.vmethod_12().DefaultCellStyle = dataGridViewCellStyle5;
			this.vmethod_12().EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.vmethod_12().Location = new global::System.Drawing.Point(8, 241);
			this.vmethod_12().MultiSelect = false;
			this.vmethod_12().Name = "DGV_Conditions";
			this.vmethod_12().ReadOnly = true;
			dataGridViewCellStyle6.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle6.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle6.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle6.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle6.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle6.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.vmethod_12().RowHeadersDefaultCellStyle = dataGridViewCellStyle6;
			this.vmethod_12().SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.vmethod_12().ShowCellToolTips = false;
			this.vmethod_12().ShowEditingIcon = false;
			this.vmethod_12().ShowRowErrors = false;
			this.vmethod_12().Size = new global::System.Drawing.Size(774, 100);
			this.vmethod_12().TabIndex = 12;
			this.vmethod_14().DataPropertyName = "ID";
			this.vmethod_14().HeaderText = "ID";
			this.vmethod_14().Name = "DataGridViewTextBoxColumn1";
			this.vmethod_14().ReadOnly = true;
			this.vmethod_14().Visible = false;
			this.vmethod_16().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.vmethod_16().DataPropertyName = "Description";
			this.vmethod_16().HeaderText = "描述";
			this.vmethod_16().Name = "DataGridViewTextBoxColumn2";
			this.vmethod_16().ReadOnly = true;
			this.vmethod_18().AutoSize = true;
			this.vmethod_18().Enabled = false;
			this.vmethod_18().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_18().Location = new global::System.Drawing.Point(5, 225);
			this.vmethod_18().Name = "Label3";
			this.vmethod_18().Size = new global::System.Drawing.Size(70, 13);
			this.vmethod_18().TabIndex = 11;
			this.vmethod_18().Text = "条件:";
			this.vmethod_20().AllowUserToAddRows = false;
			this.vmethod_20().AllowUserToDeleteRows = false;
			this.vmethod_20().BackgroundColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle7.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle7.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle7.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle7.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle7.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle7.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.vmethod_20().ColumnHeadersDefaultCellStyle = dataGridViewCellStyle7;
			this.vmethod_20().ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
			this.vmethod_20().Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.vmethod_22(),
				this.vmethod_24()
			});
			dataGridViewCellStyle8.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle8.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle8.ForeColor = global::System.Drawing.SystemColors.ControlText;
			dataGridViewCellStyle8.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle8.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle8.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.vmethod_20().DefaultCellStyle = dataGridViewCellStyle8;
			this.vmethod_20().EditMode = global::System.Windows.Forms.DataGridViewEditMode.EditProgrammatically;
			this.vmethod_20().Location = new global::System.Drawing.Point(8, 399);
			this.vmethod_20().MultiSelect = false;
			this.vmethod_20().Name = "DGV_Actions";
			this.vmethod_20().ReadOnly = true;
			dataGridViewCellStyle9.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle9.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 161);
			dataGridViewCellStyle9.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle9.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle9.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle9.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.vmethod_20().RowHeadersDefaultCellStyle = dataGridViewCellStyle9;
			this.vmethod_20().SelectionMode = global::System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
			this.vmethod_20().ShowCellToolTips = false;
			this.vmethod_20().ShowEditingIcon = false;
			this.vmethod_20().ShowRowErrors = false;
			this.vmethod_20().Size = new global::System.Drawing.Size(774, 100);
			this.vmethod_20().TabIndex = 14;
			this.vmethod_22().DataPropertyName = "ID";
			this.vmethod_22().HeaderText = "ID";
			this.vmethod_22().Name = "DataGridViewTextBoxColumn3";
			this.vmethod_22().ReadOnly = true;
			this.vmethod_22().Visible = false;
			this.vmethod_24().AutoSizeMode = global::System.Windows.Forms.DataGridViewAutoSizeColumnMode.Fill;
			this.vmethod_24().DataPropertyName = "Description";
			this.vmethod_24().HeaderText = "描述";
			this.vmethod_24().Name = "DataGridViewTextBoxColumn4";
			this.vmethod_24().ReadOnly = true;
			this.vmethod_26().AutoSize = true;
			this.vmethod_26().Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 161);
			this.vmethod_26().Location = new global::System.Drawing.Point(5, 383);
			this.vmethod_26().Name = "Label4";
			this.vmethod_26().Size = new global::System.Drawing.Size(53, 13);
			this.vmethod_26().TabIndex = 13;
			this.vmethod_26().Text = "动作:";
			this.vmethod_28().Location = new global::System.Drawing.Point(8, 189);
			this.vmethod_28().Name = "Button1";
			this.vmethod_28().Size = new global::System.Drawing.Size(93, 23);
			this.vmethod_28().TabIndex = 15;
			this.vmethod_28().Text = "添加触发器:";
			this.vmethod_28().UseVisualStyleBackColor = true;
			this.vmethod_30().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_30().FormattingEnabled = true;
			this.vmethod_30().Location = new global::System.Drawing.Point(107, 190);
			this.vmethod_30().Name = "CB_Triggers";
			this.vmethod_30().Size = new global::System.Drawing.Size(424, 21);
			this.vmethod_30().TabIndex = 16;
			this.vmethod_32().Location = new global::System.Drawing.Point(638, 190);
			this.vmethod_32().Name = "Button2";
			this.vmethod_32().Size = new global::System.Drawing.Size(144, 22);
			this.vmethod_32().TabIndex = 17;
			this.vmethod_32().Text = "删除选定";
			this.vmethod_32().UseVisualStyleBackColor = true;
			this.vmethod_34().Location = new global::System.Drawing.Point(638, 347);
			this.vmethod_34().Name = "Button3";
			this.vmethod_34().Size = new global::System.Drawing.Size(144, 23);
			this.vmethod_34().TabIndex = 20;
			this.vmethod_34().Text = "删除选定";
			this.vmethod_34().UseVisualStyleBackColor = true;
			this.vmethod_36().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_36().FormattingEnabled = true;
			this.vmethod_36().Location = new global::System.Drawing.Point(107, 348);
			this.vmethod_36().Name = "CB_Conditions";
			this.vmethod_36().Size = new global::System.Drawing.Size(424, 21);
			this.vmethod_36().TabIndex = 19;
			this.vmethod_38().Location = new global::System.Drawing.Point(8, 347);
			this.vmethod_38().Name = "Button4";
			this.vmethod_38().Size = new global::System.Drawing.Size(93, 23);
			this.vmethod_38().TabIndex = 18;
			this.vmethod_38().Text = "添加条件:";
			this.vmethod_38().UseVisualStyleBackColor = true;
			this.vmethod_40().Location = new global::System.Drawing.Point(638, 505);
			this.vmethod_40().Name = "Button5";
			this.vmethod_40().Size = new global::System.Drawing.Size(144, 23);
			this.vmethod_40().TabIndex = 23;
			this.vmethod_40().Text = "删除选定";
			this.vmethod_40().UseVisualStyleBackColor = true;
			this.vmethod_42().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.vmethod_42().FormattingEnabled = true;
			this.vmethod_42().Location = new global::System.Drawing.Point(107, 506);
			this.vmethod_42().Name = "CB_Actions";
			this.vmethod_42().Size = new global::System.Drawing.Size(424, 21);
			this.vmethod_42().TabIndex = 22;
			this.vmethod_44().Location = new global::System.Drawing.Point(8, 505);
			this.vmethod_44().Name = "Button6";
			this.vmethod_44().Size = new global::System.Drawing.Size(93, 23);
			this.vmethod_44().TabIndex = 21;
			this.vmethod_44().Text = "添加动作:";
			this.vmethod_44().UseVisualStyleBackColor = true;
			this.vmethod_46().Location = new global::System.Drawing.Point(707, 545);
			this.vmethod_46().Name = "Button7";
			this.vmethod_46().Size = new global::System.Drawing.Size(75, 23);
			this.vmethod_46().TabIndex = 25;
			this.vmethod_46().Text = "取消";
			this.vmethod_46().UseVisualStyleBackColor = true;
			this.vmethod_48().Location = new global::System.Drawing.Point(8, 545);
			this.vmethod_48().Name = "Button8";
			this.vmethod_48().Size = new global::System.Drawing.Size(75, 23);
			this.vmethod_48().TabIndex = 24;
			this.vmethod_48().Text = "确认";
			this.vmethod_48().UseVisualStyleBackColor = true;
			this.vmethod_50().AutoSize = true;
			this.vmethod_50().Location = new global::System.Drawing.Point(8, 39);
			this.vmethod_50().Name = "CheckBox_IsRepeatable";
			this.vmethod_50().Size = new global::System.Drawing.Size(117, 17);
			this.vmethod_50().TabIndex = 26;
			this.vmethod_50().Text = "事件可重复";
			this.vmethod_50().UseVisualStyleBackColor = true;
			this.vmethod_52().AutoSize = true;
			this.vmethod_52().Location = new global::System.Drawing.Point(131, 39);
			this.vmethod_52().Name = "CheckBox_IsActive";
			this.vmethod_52().Size = new global::System.Drawing.Size(96, 17);
			this.vmethod_52().TabIndex = 27;
			this.vmethod_52().Text = "事件启用";
			this.vmethod_52().UseVisualStyleBackColor = true;
			this.vmethod_54().Location = new global::System.Drawing.Point(456, 39);
			this.vmethod_54().Name = "Label5";
			this.vmethod_54().Size = new global::System.Drawing.Size(75, 13);
			this.vmethod_54().TabIndex = 28;
			this.vmethod_54().Text = "发生概率(%):";
			this.vmethod_56().Location = new global::System.Drawing.Point(532, 37);
			this.vmethod_56().Name = "NUD_Probability";
			this.vmethod_56().Size = new global::System.Drawing.Size(53, 20);
			this.vmethod_56().TabIndex = 29;
			this.vmethod_58().Location = new global::System.Drawing.Point(537, 190);
			this.vmethod_58().Name = "Button_EditTriggers";
			this.vmethod_58().Size = new global::System.Drawing.Size(95, 22);
			this.vmethod_58().TabIndex = 30;
			this.vmethod_58().Text = "编辑触发器";
			this.vmethod_58().UseVisualStyleBackColor = true;
			this.vmethod_60().Location = new global::System.Drawing.Point(537, 506);
			this.vmethod_60().Name = "Button_EditActions";
			this.vmethod_60().Size = new global::System.Drawing.Size(95, 22);
			this.vmethod_60().TabIndex = 31;
			this.vmethod_60().Text = "编辑动作";
			this.vmethod_60().UseVisualStyleBackColor = true;
			this.vmethod_62().Location = new global::System.Drawing.Point(537, 347);
			this.vmethod_62().Name = "Button_EditConditions";
			this.vmethod_62().Size = new global::System.Drawing.Size(95, 22);
			this.vmethod_62().TabIndex = 32;
			this.vmethod_62().Text = "编辑条件";
			this.vmethod_62().UseVisualStyleBackColor = true;
			this.vmethod_64().AutoSize = true;
			this.vmethod_64().Location = new global::System.Drawing.Point(233, 39);
			this.vmethod_64().Name = "CheckBox_IsShown";
			this.vmethod_64().Size = new global::System.Drawing.Size(130, 17);
			this.vmethod_64().TabIndex = 33;
			this.vmethod_64().Text = "事件显示于输出区";
			this.vmethod_64().UseVisualStyleBackColor = true;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(786, 580);
			base.Controls.Add(this.vmethod_64());
			base.Controls.Add(this.vmethod_62());
			base.Controls.Add(this.vmethod_60());
			base.Controls.Add(this.vmethod_58());
			base.Controls.Add(this.vmethod_56());
			base.Controls.Add(this.vmethod_54());
			base.Controls.Add(this.vmethod_52());
			base.Controls.Add(this.vmethod_50());
			base.Controls.Add(this.vmethod_46());
			base.Controls.Add(this.vmethod_48());
			base.Controls.Add(this.vmethod_40());
			base.Controls.Add(this.vmethod_42());
			base.Controls.Add(this.vmethod_44());
			base.Controls.Add(this.vmethod_34());
			base.Controls.Add(this.vmethod_36());
			base.Controls.Add(this.vmethod_38());
			base.Controls.Add(this.vmethod_32());
			base.Controls.Add(this.vmethod_30());
			base.Controls.Add(this.vmethod_28());
			base.Controls.Add(this.vmethod_20());
			base.Controls.Add(this.vmethod_26());
			base.Controls.Add(this.vmethod_12());
			base.Controls.Add(this.vmethod_18());
			base.Controls.Add(this.vmethod_6());
			base.Controls.Add(this.vmethod_4());
			base.Controls.Add(this.vmethod_0());
			base.Controls.Add(this.vmethod_2());
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "EditEvent";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "编辑事件";
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_6()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_12()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_20()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_56()).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040033E4 RID: 13284
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
