namespace Command
{
	// Token: 0x020009E3 RID: 2531
	
	public sealed partial class NewMission : global::ns33.CommandForm
	{
		// Token: 0x06004A53 RID: 19027 RVA: 0x001CE0E8 File Offset: 0x001CC2E8
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x06004A54 RID: 19028 RVA: 0x001CE12C File Offset: 0x001CC32C
		private void InitializeComponent()
		{
			this.vmethod_1(new global::System.Windows.Forms.Label());
			this.vmethod_3(new global::System.Windows.Forms.TextBox());
			this.vmethod_5(new global::System.Windows.Forms.ComboBox());
			this.vmethod_7(new global::System.Windows.Forms.Label());
			this.vmethod_9(new global::System.Windows.Forms.Label());
			this.vmethod_11(new global::System.Windows.Forms.ComboBox());
			this.vmethod_13(new global::System.Windows.Forms.Button());
			this.vmethod_15(new global::System.Windows.Forms.Button());
			this.vmethod_17(new global::System.Windows.Forms.CheckBox());
			this.vmethod_19(new global::System.Windows.Forms.ComboBox());
			this.vmethod_21(new global::System.Windows.Forms.Label());
			this.vmethod_23(new global::System.Windows.Forms.Label());
			this.SetCB_Category(new global::System.Windows.Forms.ComboBox());
			this.vmethod_27(new global::System.Windows.Forms.FlowLayoutPanel());
			this.vmethod_29(new global::System.Windows.Forms.GroupBox());
			this.vmethod_31(new global::System.Windows.Forms.Button());
			this.vmethod_33(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_35(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_37(new global::System.Windows.Forms.Label());
			this.vmethod_39(new global::System.Windows.Forms.Label());
			this.vmethod_41(new global::System.Windows.Forms.GroupBox());
			this.vmethod_43(new global::System.Windows.Forms.CheckBox());
			this.vmethod_45(new global::System.Windows.Forms.CheckBox());
			this.vmethod_47(new global::System.Windows.Forms.CheckBox());
			this.vmethod_49(new global::System.Windows.Forms.Button());
			this.vmethod_51(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_53(new global::System.Windows.Forms.Label());
			this.vmethod_55(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_57(new global::System.Windows.Forms.Label());
			this.vmethod_59(new global::System.Windows.Forms.GroupBox());
			this.vmethod_79(new global::System.Windows.Forms.Button());
			this.vmethod_61(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_63(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_65(new global::System.Windows.Forms.Label());
			this.vmethod_67(new global::System.Windows.Forms.Label());
			this.vmethod_69(new global::System.Windows.Forms.GroupBox());
			this.vmethod_81(new global::System.Windows.Forms.Button());
			this.vmethod_71(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_73(new global::System.Windows.Forms.DateTimePicker());
			this.vmethod_75(new global::System.Windows.Forms.Label());
			this.vmethod_77(new global::System.Windows.Forms.Label());
			this.vmethod_83(new global::System.Windows.Forms.ComboBox());
			this.vmethod_85(new global::System.Windows.Forms.Label());
			this.GetFlowLayoutPanel1().SuspendLayout();
			this.vmethod_28().SuspendLayout();
			this.vmethod_40().SuspendLayout();
			this.GetGroupBox_TakeOffTime().SuspendLayout();
			this.GetGroupBox_TimeOnTarget().SuspendLayout();
			base.SuspendLayout();
			this.vmethod_0().Location = new global::System.Drawing.Point(2, 34);
			this.vmethod_0().Name = "Label1";
			this.vmethod_0().Size = new global::System.Drawing.Size(38, 13);
			this.vmethod_0().TabIndex = 0;
			this.vmethod_0().Text = "名称:";
			this.GetTextBox_Name().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetTextBox_Name().Location = new global::System.Drawing.Point(64, 30);
			this.GetTextBox_Name().Name = "TextBox_Name";
			this.GetTextBox_Name().Size = new global::System.Drawing.Size(280, 20);
			this.GetTextBox_Name().TabIndex = 1;
			this.GetCB_MissionClass().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetCB_MissionClass().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_MissionClass().FormattingEnabled = true;
			this.GetCB_MissionClass().Location = new global::System.Drawing.Point(64, 51);
			this.GetCB_MissionClass().Name = "CB_MissionClass";
			this.GetCB_MissionClass().Size = new global::System.Drawing.Size(280, 21);
			this.GetCB_MissionClass().TabIndex = 2;
			this.vmethod_6().AutoSize = true;
			this.vmethod_6().Location = new global::System.Drawing.Point(2, 55);
			this.vmethod_6().Name = "Label_MissionClass";
			this.vmethod_6().Size = new global::System.Drawing.Size(35, 13);
			this.vmethod_6().TabIndex = 3;
			this.vmethod_6().Text = "类型:";
			this.vmethod_8().AutoSize = true;
			this.vmethod_8().Location = new global::System.Drawing.Point(1, 77);
			this.vmethod_8().Name = "Label_MissionType";
			this.vmethod_8().Size = new global::System.Drawing.Size(34, 13);
			this.vmethod_8().TabIndex = 4;
			this.vmethod_8().Text = "分类:";
			this.GetCB_MissionType().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetCB_MissionType().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_MissionType().FormattingEnabled = true;
			this.GetCB_MissionType().Location = new global::System.Drawing.Point(64, 73);
			this.GetCB_MissionType().Name = "CB_MissionType";
			this.GetCB_MissionType().Size = new global::System.Drawing.Size(280, 21);
			this.GetCB_MissionType().TabIndex = 5;
			this.vmethod_12().Location = new global::System.Drawing.Point(5, 200);
			this.vmethod_12().Name = "Button1";
			this.vmethod_12().Size = new global::System.Drawing.Size(75, 23);
			this.vmethod_12().TabIndex = 6;
			this.vmethod_12().Text = "确认";
			this.vmethod_12().UseVisualStyleBackColor = true;
			this.vmethod_14().Location = new global::System.Drawing.Point(461, 202);
			this.vmethod_14().Name = "Button2";
			this.vmethod_14().Size = new global::System.Drawing.Size(75, 23);
			this.vmethod_14().TabIndex = 7;
			this.vmethod_14().Text = "取消";
			this.vmethod_14().UseVisualStyleBackColor = true;
			this.GetCB_OpenMissionEditor().AutoSize = true;
			this.GetCB_OpenMissionEditor().Location = new global::System.Drawing.Point(5, 177);
			this.GetCB_OpenMissionEditor().Name = "CB_OpenMissionEditor";
			this.GetCB_OpenMissionEditor().Size = new global::System.Drawing.Size(159, 17);
			this.GetCB_OpenMissionEditor().TabIndex = 8;
			this.GetCB_OpenMissionEditor().Text = "打开任务编辑器窗口";
			this.GetCB_OpenMissionEditor().UseVisualStyleBackColor = true;
			this.GetCB_MissionStatus().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetCB_MissionStatus().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_MissionStatus().FormattingEnabled = true;
			this.GetCB_MissionStatus().Items.AddRange(new object[]
			{
				"启用",
				"未启"
			});
			this.GetCB_MissionStatus().Location = new global::System.Drawing.Point(64, 95);
			this.GetCB_MissionStatus().Name = "CB_MissionStatus";
			this.GetCB_MissionStatus().Size = new global::System.Drawing.Size(280, 21);
			this.GetCB_MissionStatus().TabIndex = 30;
			this.GetLabel_MissionStatus().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetLabel_MissionStatus().AutoSize = true;
			this.GetLabel_MissionStatus().Location = new global::System.Drawing.Point(1, 99);
			this.GetLabel_MissionStatus().Name = "Label_MissionStatus";
			this.GetLabel_MissionStatus().Size = new global::System.Drawing.Size(40, 13);
			this.GetLabel_MissionStatus().TabIndex = 29;
			this.GetLabel_MissionStatus().Text = "状态:";
			this.GetLabel_Category().AutoSize = true;
			this.GetLabel_Category().Location = new global::System.Drawing.Point(2, 12);
			this.GetLabel_Category().Name = "Label_Category";
			this.GetLabel_Category().Size = new global::System.Drawing.Size(52, 13);
			this.GetLabel_Category().TabIndex = 32;
			this.GetLabel_Category().Text = "类别:";
			this.GetCB_Category().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetCB_Category().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_Category().FormattingEnabled = true;
			this.GetCB_Category().Location = new global::System.Drawing.Point(64, 8);
			this.GetCB_Category().Name = "CB_Category";
			this.GetCB_Category().Size = new global::System.Drawing.Size(280, 21);
			this.GetCB_Category().TabIndex = 31;
			this.GetFlowLayoutPanel1().Controls.Add(this.vmethod_28());
			this.GetFlowLayoutPanel1().Controls.Add(this.vmethod_40());
			this.GetFlowLayoutPanel1().Controls.Add(this.GetGroupBox_TakeOffTime());
			this.GetFlowLayoutPanel1().Controls.Add(this.GetGroupBox_TimeOnTarget());
			this.GetFlowLayoutPanel1().Location = new global::System.Drawing.Point(347, 8);
			this.GetFlowLayoutPanel1().Margin = new global::System.Windows.Forms.Padding(0);
			this.GetFlowLayoutPanel1().Name = "FlowLayoutPanel1";
			this.GetFlowLayoutPanel1().Size = new global::System.Drawing.Size(188, 195);
			this.GetFlowLayoutPanel1().TabIndex = 47;
			this.vmethod_28().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_28().Controls.Add(this.vmethod_30());
			this.vmethod_28().Controls.Add(this.vmethod_32());
			this.vmethod_28().Controls.Add(this.vmethod_34());
			this.vmethod_28().Controls.Add(this.vmethod_36());
			this.vmethod_28().Controls.Add(this.vmethod_38());
			this.vmethod_28().Location = new global::System.Drawing.Point(3, 3);
			this.vmethod_28().Name = "GroupBox_ActivationTime";
			this.vmethod_28().Size = new global::System.Drawing.Size(183, 61);
			this.vmethod_28().TabIndex = 45;
			this.vmethod_28().TabStop = false;
			this.vmethod_28().Text = "开始时间";
			this.vmethod_30().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_30().Location = new global::System.Drawing.Point(118, 14);
			this.vmethod_30().Name = "Button_Clear_ActivationTime";
			this.vmethod_30().Size = new global::System.Drawing.Size(62, 22);
			this.vmethod_30().TabIndex = 43;
			this.vmethod_30().Text = "清空";
			this.vmethod_30().UseVisualStyleBackColor = true;
			this.vmethod_32().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_32().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_32().Location = new global::System.Drawing.Point(39, 36);
			this.vmethod_32().Name = "DateTimePicker_ActivationTime";
			this.vmethod_32().ShowUpDown = true;
			this.vmethod_32().Size = new global::System.Drawing.Size(79, 20);
			this.vmethod_32().TabIndex = 37;
			this.vmethod_34().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_34().Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.vmethod_34().Location = new global::System.Drawing.Point(39, 15);
			this.vmethod_34().Name = "DateTimePicker_ActivationDate";
			this.vmethod_34().Size = new global::System.Drawing.Size(79, 20);
			this.vmethod_34().TabIndex = 36;
			this.vmethod_36().AutoSize = true;
			this.vmethod_36().Location = new global::System.Drawing.Point(4, 19);
			this.vmethod_36().Name = "Label101";
			this.vmethod_36().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_36().TabIndex = 38;
			this.vmethod_36().Text = "日期:";
			this.vmethod_38().AutoSize = true;
			this.vmethod_38().Location = new global::System.Drawing.Point(4, 39);
			this.vmethod_38().Name = "Label102";
			this.vmethod_38().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_38().TabIndex = 38;
			this.vmethod_38().Text = "时间:";
			this.vmethod_40().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_40().Controls.Add(this.GetCheckBox_DeleteMission());
			this.vmethod_40().Controls.Add(this.GetCheckBox_OrderRTB());
			this.vmethod_40().Controls.Add(this.GetCheckBox_UnassignUnits());
			this.vmethod_40().Controls.Add(this.GetButton_Clear_DeactivationTime());
			this.vmethod_40().Controls.Add(this.GetDateTimePicker_DeactivationTime());
			this.vmethod_40().Controls.Add(this.vmethod_52());
			this.vmethod_40().Controls.Add(this.GetDateTimePicker_DeactivationDate());
			this.vmethod_40().Controls.Add(this.vmethod_56());
			this.vmethod_40().Location = new global::System.Drawing.Point(3, 70);
			this.vmethod_40().Name = "GroupBox_DeactivationTime";
			this.vmethod_40().Size = new global::System.Drawing.Size(183, 119);
			this.vmethod_40().TabIndex = 44;
			this.vmethod_40().TabStop = false;
			this.vmethod_40().Text = "结束时间";
			this.GetCheckBox_DeleteMission().AutoSize = true;
			this.GetCheckBox_DeleteMission().Location = new global::System.Drawing.Point(8, 98);
			this.GetCheckBox_DeleteMission().Name = "CheckBox_DeleteMission";
			this.GetCheckBox_DeleteMission().Size = new global::System.Drawing.Size(95, 17);
			this.GetCheckBox_DeleteMission().TabIndex = 46;
			this.GetCheckBox_DeleteMission().Text = "删除任务";
			this.GetCheckBox_DeleteMission().UseVisualStyleBackColor = true;
			this.GetCheckBox_OrderRTB().AutoSize = true;
			this.GetCheckBox_OrderRTB().Location = new global::System.Drawing.Point(8, 79);
			this.GetCheckBox_OrderRTB().Name = "CheckBox_OrderRTB";
			this.GetCheckBox_OrderRTB().Size = new global::System.Drawing.Size(77, 17);
			this.GetCheckBox_OrderRTB().TabIndex = 45;
			this.GetCheckBox_OrderRTB().Text = "命令返航";
			this.GetCheckBox_OrderRTB().UseVisualStyleBackColor = true;
			this.GetCheckBox_UnassignUnits().AutoSize = true;
			this.GetCheckBox_UnassignUnits().Location = new global::System.Drawing.Point(8, 60);
			this.GetCheckBox_UnassignUnits().Name = "CheckBox_UnassignUnits";
			this.GetCheckBox_UnassignUnits().Size = new global::System.Drawing.Size(120, 17);
			this.GetCheckBox_UnassignUnits().TabIndex = 44;
			this.GetCheckBox_UnassignUnits().Text = "取消作战单元分配的任务";
			this.GetCheckBox_UnassignUnits().UseVisualStyleBackColor = true;
			this.GetButton_Clear_DeactivationTime().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_Clear_DeactivationTime().Location = new global::System.Drawing.Point(118, 14);
			this.GetButton_Clear_DeactivationTime().Name = "Button_Clear_DeactivationTime";
			this.GetButton_Clear_DeactivationTime().Size = new global::System.Drawing.Size(60, 22);
			this.GetButton_Clear_DeactivationTime().TabIndex = 43;
			this.GetButton_Clear_DeactivationTime().Text = "清空";
			this.GetButton_Clear_DeactivationTime().UseVisualStyleBackColor = true;
			this.GetDateTimePicker_DeactivationTime().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetDateTimePicker_DeactivationTime().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.GetDateTimePicker_DeactivationTime().Location = new global::System.Drawing.Point(39, 36);
			this.GetDateTimePicker_DeactivationTime().Name = "DateTimePicker_DeactivationTime";
			this.GetDateTimePicker_DeactivationTime().ShowUpDown = true;
			this.GetDateTimePicker_DeactivationTime().Size = new global::System.Drawing.Size(79, 20);
			this.GetDateTimePicker_DeactivationTime().TabIndex = 40;
			this.vmethod_52().AutoSize = true;
			this.vmethod_52().Location = new global::System.Drawing.Point(4, 40);
			this.vmethod_52().Name = "Label112";
			this.vmethod_52().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_52().TabIndex = 41;
			this.vmethod_52().Text = "时间:";
			this.GetDateTimePicker_DeactivationDate().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetDateTimePicker_DeactivationDate().Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.GetDateTimePicker_DeactivationDate().Location = new global::System.Drawing.Point(39, 15);
			this.GetDateTimePicker_DeactivationDate().Name = "DateTimePicker_DeactivationDate";
			this.GetDateTimePicker_DeactivationDate().Size = new global::System.Drawing.Size(79, 20);
			this.GetDateTimePicker_DeactivationDate().TabIndex = 39;
			this.vmethod_56().AutoSize = true;
			this.vmethod_56().Location = new global::System.Drawing.Point(4, 19);
			this.vmethod_56().Name = "Label114";
			this.vmethod_56().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_56().TabIndex = 42;
			this.vmethod_56().Text = "日期:";
			this.GetGroupBox_TakeOffTime().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetGroupBox_TakeOffTime().Controls.Add(this.GetButton_Clear_TakeOffTime());
			this.GetGroupBox_TakeOffTime().Controls.Add(this.GetDateTimePicker_TakeOffTime());
			this.GetGroupBox_TakeOffTime().Controls.Add(this.GetDateTimePicker_TakeOffDate());
			this.GetGroupBox_TakeOffTime().Controls.Add(this.vmethod_64());
			this.GetGroupBox_TakeOffTime().Controls.Add(this.vmethod_66());
			this.GetGroupBox_TakeOffTime().Location = new global::System.Drawing.Point(3, 195);
			this.GetGroupBox_TakeOffTime().Name = "GroupBox_TakeOffTime";
			this.GetGroupBox_TakeOffTime().Size = new global::System.Drawing.Size(183, 61);
			this.GetGroupBox_TakeOffTime().TabIndex = 46;
			this.GetGroupBox_TakeOffTime().TabStop = false;
			this.GetGroupBox_TakeOffTime().Text = "起飞时间";
			this.GetButton_Clear_TakeOffTime().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_Clear_TakeOffTime().Location = new global::System.Drawing.Point(118, 14);
			this.GetButton_Clear_TakeOffTime().Name = "Button_Clear_TakeOffTime";
			this.GetButton_Clear_TakeOffTime().Size = new global::System.Drawing.Size(60, 22);
			this.GetButton_Clear_TakeOffTime().TabIndex = 44;
			this.GetButton_Clear_TakeOffTime().Text = "清空";
			this.GetButton_Clear_TakeOffTime().UseVisualStyleBackColor = true;
			this.GetDateTimePicker_TakeOffTime().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetDateTimePicker_TakeOffTime().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.GetDateTimePicker_TakeOffTime().Location = new global::System.Drawing.Point(39, 36);
			this.GetDateTimePicker_TakeOffTime().Name = "DateTimePicker_TakeOffTime";
			this.GetDateTimePicker_TakeOffTime().ShowUpDown = true;
			this.GetDateTimePicker_TakeOffTime().Size = new global::System.Drawing.Size(79, 20);
			this.GetDateTimePicker_TakeOffTime().TabIndex = 37;
			this.GetDateTimePicker_TakeOffDate().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetDateTimePicker_TakeOffDate().Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.GetDateTimePicker_TakeOffDate().Location = new global::System.Drawing.Point(39, 15);
			this.GetDateTimePicker_TakeOffDate().Name = "DateTimePicker_TakeOffDate";
			this.GetDateTimePicker_TakeOffDate().Size = new global::System.Drawing.Size(79, 20);
			this.GetDateTimePicker_TakeOffDate().TabIndex = 36;
			this.vmethod_64().AutoSize = true;
			this.vmethod_64().Location = new global::System.Drawing.Point(4, 19);
			this.vmethod_64().Name = "Label162";
			this.vmethod_64().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_64().TabIndex = 38;
			this.vmethod_64().Text = "日期:";
			this.vmethod_66().AutoSize = true;
			this.vmethod_66().Location = new global::System.Drawing.Point(4, 39);
			this.vmethod_66().Name = "Label169";
			this.vmethod_66().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_66().TabIndex = 38;
			this.vmethod_66().Text = "时间:";
			this.GetGroupBox_TimeOnTarget().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetGroupBox_TimeOnTarget().Controls.Add(this.GetButton_Clear_TimeOnTarget());
			this.GetGroupBox_TimeOnTarget().Controls.Add(this.vmethod_70());
			this.GetGroupBox_TimeOnTarget().Controls.Add(this.vmethod_72());
			this.GetGroupBox_TimeOnTarget().Controls.Add(this.vmethod_74());
			this.GetGroupBox_TimeOnTarget().Controls.Add(this.vmethod_76());
			this.GetGroupBox_TimeOnTarget().Location = new global::System.Drawing.Point(3, 262);
			this.GetGroupBox_TimeOnTarget().Name = "GroupBox_TimeOnTarget";
			this.GetGroupBox_TimeOnTarget().Size = new global::System.Drawing.Size(183, 61);
			this.GetGroupBox_TimeOnTarget().TabIndex = 47;
			this.GetGroupBox_TimeOnTarget().TabStop = false;
			this.GetGroupBox_TimeOnTarget().Text = "达到目标时间(ToT)";
			this.GetButton_Clear_TimeOnTarget().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetButton_Clear_TimeOnTarget().Location = new global::System.Drawing.Point(118, 14);
			this.GetButton_Clear_TimeOnTarget().Name = "Button_Clear_TimeOnTarget";
			this.GetButton_Clear_TimeOnTarget().Size = new global::System.Drawing.Size(60, 22);
			this.GetButton_Clear_TimeOnTarget().TabIndex = 44;
			this.GetButton_Clear_TimeOnTarget().Text = "清空";
			this.GetButton_Clear_TimeOnTarget().UseVisualStyleBackColor = true;
			this.vmethod_70().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_70().Format = global::System.Windows.Forms.DateTimePickerFormat.Time;
			this.vmethod_70().Location = new global::System.Drawing.Point(39, 36);
			this.vmethod_70().Name = "DateTimePicker_TimeOnTargetTime";
			this.vmethod_70().ShowUpDown = true;
			this.vmethod_70().Size = new global::System.Drawing.Size(79, 20);
			this.vmethod_70().TabIndex = 37;
			this.vmethod_72().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_72().Format = global::System.Windows.Forms.DateTimePickerFormat.Short;
			this.vmethod_72().Location = new global::System.Drawing.Point(39, 15);
			this.vmethod_72().Name = "DateTimePicker_TimeOnTargetDate";
			this.vmethod_72().Size = new global::System.Drawing.Size(79, 20);
			this.vmethod_72().TabIndex = 36;
			this.vmethod_74().AutoSize = true;
			this.vmethod_74().Location = new global::System.Drawing.Point(4, 19);
			this.vmethod_74().Name = "Label170";
			this.vmethod_74().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_74().TabIndex = 38;
			this.vmethod_74().Text = "日期:";
			this.vmethod_76().AutoSize = true;
			this.vmethod_76().Location = new global::System.Drawing.Point(4, 39);
			this.vmethod_76().Name = "Label171";
			this.vmethod_76().Size = new global::System.Drawing.Size(33, 13);
			this.vmethod_76().TabIndex = 38;
			this.vmethod_76().Text = "时间:";
			this.GetCB_ParentPool().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.GetCB_ParentPool().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_ParentPool().FormattingEnabled = true;
			this.GetCB_ParentPool().Items.AddRange(new object[]
			{
				"启用",
				"未启"
			});
			this.GetCB_ParentPool().Location = new global::System.Drawing.Point(64, 117);
			this.GetCB_ParentPool().Name = "CB_ParentPool";
			this.GetCB_ParentPool().Size = new global::System.Drawing.Size(280, 21);
			this.GetCB_ParentPool().TabIndex = 49;
			this.vmethod_84().Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.vmethod_84().AutoSize = true;
			this.vmethod_84().Location = new global::System.Drawing.Point(1, 122);
			this.vmethod_84().Name = "Label_ParentPool";
			this.vmethod_84().Size = new global::System.Drawing.Size(64, 13);
			this.vmethod_84().TabIndex = 48;
			this.vmethod_84().Text = "上级任务（Task）池:";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(541, 229);
			base.Controls.Add(this.GetCB_ParentPool());
			base.Controls.Add(this.vmethod_84());
			base.Controls.Add(this.GetFlowLayoutPanel1());
			base.Controls.Add(this.GetLabel_Category());
			base.Controls.Add(this.GetCB_Category());
			base.Controls.Add(this.GetCB_MissionStatus());
			base.Controls.Add(this.GetLabel_MissionStatus());
			base.Controls.Add(this.GetCB_OpenMissionEditor());
			base.Controls.Add(this.vmethod_14());
			base.Controls.Add(this.vmethod_12());
			base.Controls.Add(this.GetCB_MissionType());
			base.Controls.Add(this.vmethod_8());
			base.Controls.Add(this.vmethod_6());
			base.Controls.Add(this.GetCB_MissionClass());
			base.Controls.Add(this.GetTextBox_Name());
			base.Controls.Add(this.vmethod_0());
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "NewMission";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "创建任务/任务（Task）池/任务（Task）包";
			this.GetFlowLayoutPanel1().ResumeLayout(false);
			this.vmethod_28().ResumeLayout(false);
			this.vmethod_28().PerformLayout();
			this.vmethod_40().ResumeLayout(false);
			this.vmethod_40().PerformLayout();
			this.GetGroupBox_TakeOffTime().ResumeLayout(false);
			this.GetGroupBox_TakeOffTime().PerformLayout();
			this.GetGroupBox_TimeOnTarget().ResumeLayout(false);
			this.GetGroupBox_TimeOnTarget().PerformLayout();
			base.ResumeLayout(false);
			base.PerformLayout();
		}

		// Token: 0x040022EB RID: 8939
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
