namespace ns34
{
	// Token: 0x02000ABA RID: 2746
	
	public sealed partial class SpeedAlt : global::ns33.CommandForm
	{
		// Token: 0x060056F4 RID: 22260 RVA: 0x00259434 File Offset: 0x00257634
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060056F5 RID: 22261 RVA: 0x00259478 File Offset: 0x00257678
		private void InitializeComponent()
		{
			this.icontainer_0 = new global::System.ComponentModel.Container();
			this.vmethod_1(new global::System.Windows.Forms.TrackBar());
			this.vmethod_3(new global::System.Windows.Forms.Label());
			this.vmethod_5(new global::System.Windows.Forms.Label());
			this.vmethod_7(new global::System.Windows.Forms.Label());
			this.vmethod_9(new global::System.Windows.Forms.Label());
			this.vmethod_11(new global::System.Windows.Forms.Label());
			this.vmethod_13(new global::System.Windows.Forms.Label());
			this.vmethod_15(new global::System.Windows.Forms.Timer(this.icontainer_0));
			this.vmethod_17(new global::System.Windows.Forms.TrackBar());
			this.vmethod_19(new global::System.Windows.Forms.Label());
			this.vmethod_21(new global::System.Windows.Forms.Label());
			this.vmethod_23(new global::System.Windows.Forms.Label());
			this.vmethod_25(new global::System.Windows.Forms.Label());
			this.vmethod_27(new global::System.Windows.Forms.Label());
			this.vmethod_29(new global::System.Windows.Forms.Label());
			this.vmethod_31(new global::System.Windows.Forms.GroupBox());
			this.vmethod_71(new global::System.Windows.Forms.TextBox());
			this.vmethod_39(new global::System.Windows.Forms.CheckBox());
			this.vmethod_35(new global::System.Windows.Forms.GroupBox());
			this.vmethod_151(new global::System.Windows.Forms.RadioButton());
			this.vmethod_87(new global::System.Windows.Forms.RadioButton());
			this.vmethod_79(new global::System.Windows.Forms.RadioButton());
			this.vmethod_81(new global::System.Windows.Forms.RadioButton());
			this.vmethod_83(new global::System.Windows.Forms.RadioButton());
			this.vmethod_85(new global::System.Windows.Forms.RadioButton());
			this.vmethod_73(new global::System.Windows.Forms.Label());
			this.vmethod_141(new global::System.Windows.Forms.Label());
			this.vmethod_91(new global::System.Windows.Forms.Label());
			this.vmethod_33(new global::System.Windows.Forms.GroupBox());
			this.vmethod_143(new global::System.Windows.Forms.CheckBox());
			this.vmethod_137(new global::System.Windows.Forms.Label());
			this.vmethod_139(new global::System.Windows.Forms.Label());
			this.vmethod_133(new global::System.Windows.Forms.Label());
			this.vmethod_135(new global::System.Windows.Forms.Label());
			this.vmethod_127(new global::System.Windows.Forms.PictureBox());
			this.vmethod_129(new global::System.Windows.Forms.PictureBox());
			this.vmethod_131(new global::System.Windows.Forms.PictureBox());
			this.vmethod_119(new global::System.Windows.Forms.Label());
			this.vmethod_125(new global::System.Windows.Forms.Label());
			this.vmethod_123(new global::System.Windows.Forms.Label());
			this.vmethod_121(new global::System.Windows.Forms.Label());
			this.vmethod_117(new global::System.Windows.Forms.PictureBox());
			this.vmethod_115(new global::System.Windows.Forms.PictureBox());
			this.vmethod_113(new global::System.Windows.Forms.PictureBox());
			this.vmethod_111(new global::System.Windows.Forms.PictureBox());
			this.vmethod_109(new global::System.Windows.Forms.PictureBox());
			this.vmethod_89(new global::System.Windows.Forms.FlowLayoutPanel());
			this.vmethod_53(new global::System.Windows.Forms.GroupBox());
			this.vmethod_153(new global::System.Windows.Forms.RadioButton());
			this.vmethod_55(new global::System.Windows.Forms.RadioButton());
			this.vmethod_57(new global::System.Windows.Forms.RadioButton());
			this.vmethod_59(new global::System.Windows.Forms.RadioButton());
			this.vmethod_61(new global::System.Windows.Forms.RadioButton());
			this.vmethod_63(new global::System.Windows.Forms.RadioButton());
			this.vmethod_65(new global::System.Windows.Forms.RadioButton());
			this.vmethod_67(new global::System.Windows.Forms.RadioButton());
			this.vmethod_41(new global::System.Windows.Forms.GroupBox());
			this.vmethod_155(new global::System.Windows.Forms.RadioButton());
			this.vmethod_69(new global::System.Windows.Forms.RadioButton());
			this.vmethod_51(new global::System.Windows.Forms.RadioButton());
			this.vmethod_43(new global::System.Windows.Forms.RadioButton());
			this.vmethod_45(new global::System.Windows.Forms.RadioButton());
			this.vmethod_47(new global::System.Windows.Forms.RadioButton());
			this.vmethod_49(new global::System.Windows.Forms.RadioButton());
			this.vmethod_77(new global::System.Windows.Forms.Label());
			this.vmethod_75(new global::System.Windows.Forms.TextBox());
			this.vmethod_37(new global::System.Windows.Forms.CheckBox());
			this.vmethod_145(new global::Microsoft.VisualBasic.PowerPacks.ShapeContainer());
			this.vmethod_147(new global::Microsoft.VisualBasic.PowerPacks.LineShape());
			this.vmethod_149(new global::Microsoft.VisualBasic.PowerPacks.LineShape());
			this.vmethod_93(new global::System.Windows.Forms.GroupBox());
			this.vmethod_105(new global::System.Windows.Forms.Label());
			this.vmethod_107(new global::System.Windows.Forms.Label());
			this.vmethod_101(new global::System.Windows.Forms.TextBox());
			this.vmethod_103(new global::System.Windows.Forms.ComboBox());
			this.vmethod_99(new global::System.Windows.Forms.Label());
			this.vmethod_95(new global::System.Windows.Forms.Label());
			this.vmethod_97(new global::System.Windows.Forms.Label());
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_0()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_16()).BeginInit();
			this.vmethod_30().SuspendLayout();
			this.vmethod_34().SuspendLayout();
			this.vmethod_32().SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_126()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_128()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_130()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_116()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_114()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_112()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_110()).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_108()).BeginInit();
			this.vmethod_88().SuspendLayout();
			this.GetGroupBox_AltitudePresets().SuspendLayout();
			this.GetGroupBox_SubDepthPreset().SuspendLayout();
			this.vmethod_92().SuspendLayout();
			base.SuspendLayout();
			this.vmethod_0().AutoSize = false;
			this.vmethod_0().LargeChange = 10;
			this.vmethod_0().Location = new global::System.Drawing.Point(52, 79);
			this.vmethod_0().Name = "TrackBar_Throttle";
			this.vmethod_0().Size = new global::System.Drawing.Size(293, 31);
			this.vmethod_0().SmallChange = 5;
			this.vmethod_0().TabIndex = 0;
			this.vmethod_0().TickFrequency = 100;
			this.vmethod_2().AutoSize = true;
			this.vmethod_2().Location = new global::System.Drawing.Point(3, 83);
			this.vmethod_2().Name = "Label_MinSpeed";
			this.vmethod_2().RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.vmethod_2().Size = new global::System.Drawing.Size(55, 13);
			this.vmethod_2().TabIndex = 4;
			this.vmethod_2().Text = "MinSpeed";
			this.vmethod_2().TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.vmethod_4().AutoSize = true;
			this.vmethod_4().Location = new global::System.Drawing.Point(343, 83);
			this.vmethod_4().Name = "Label_MaxSpeed";
			this.vmethod_4().Size = new global::System.Drawing.Size(58, 13);
			this.vmethod_4().TabIndex = 3;
			this.vmethod_4().Text = "最大航速";
			this.vmethod_4().TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.vmethod_6().AutoSize = true;
			this.vmethod_6().Location = new global::System.Drawing.Point(5, 43);
			this.vmethod_6().Name = "Label2";
			this.vmethod_6().Size = new global::System.Drawing.Size(80, 13);
			this.vmethod_6().TabIndex = 4;
			this.vmethod_6().Text = "期望航速:";
			this.vmethod_8().AutoSize = true;
			this.vmethod_8().Location = new global::System.Drawing.Point(90, 42);
			this.vmethod_8().Name = "Label_DesiredSpeed";
			this.vmethod_8().Size = new global::System.Drawing.Size(74, 13);
			this.vmethod_8().TabIndex = 5;
			this.vmethod_8().Text = "DesiredSpeed";
			this.vmethod_10().AutoSize = true;
			this.vmethod_10().Location = new global::System.Drawing.Point(5, 61);
			this.vmethod_10().Name = "Label3";
			this.vmethod_10().Size = new global::System.Drawing.Size(78, 13);
			this.vmethod_10().TabIndex = 6;
			this.vmethod_10().Text = "当前航速:";
			this.vmethod_12().AutoSize = true;
			this.vmethod_12().Location = new global::System.Drawing.Point(90, 60);
			this.vmethod_12().Name = "Label_ActualSpeed";
			this.vmethod_12().Size = new global::System.Drawing.Size(72, 13);
			this.vmethod_12().TabIndex = 7;
			this.vmethod_12().Text = "CurrentSpeed";
			this.vmethod_14().Interval = 1000;
			this.vmethod_16().LargeChange = 10;
			this.vmethod_16().Location = new global::System.Drawing.Point(287, 9);
			this.vmethod_16().Name = "TrackBar_Altitude";
			this.vmethod_16().Orientation = global::System.Windows.Forms.Orientation.Vertical;
			this.vmethod_16().RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.vmethod_16().Size = new global::System.Drawing.Size(45, 290);
			this.vmethod_16().SmallChange = 5;
			this.vmethod_16().TabIndex = 9;
			this.vmethod_16().TickFrequency = 305;
			this.vmethod_18().AutoSize = true;
			this.vmethod_18().Location = new global::System.Drawing.Point(5, 61);
			this.vmethod_18().Name = "Label5";
			this.vmethod_18().Size = new global::System.Drawing.Size(82, 13);
			this.vmethod_18().TabIndex = 11;
			this.vmethod_18().Text = "当前高度:";
			this.vmethod_20().AutoSize = true;
			this.vmethod_20().Location = new global::System.Drawing.Point(5, 43);
			this.vmethod_20().Name = "Label6";
			this.vmethod_20().Size = new global::System.Drawing.Size(84, 13);
			this.vmethod_20().TabIndex = 10;
			this.vmethod_20().Text = "期望高度:";
			this.vmethod_22().AutoSize = true;
			this.vmethod_22().Location = new global::System.Drawing.Point(317, 16);
			this.vmethod_22().Name = "Label_MaxAlt";
			this.vmethod_22().RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.vmethod_22().Size = new global::System.Drawing.Size(39, 13);
			this.vmethod_22().TabIndex = 12;
			this.vmethod_22().Text = "最大高度";
			this.vmethod_22().TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.vmethod_24().AutoSize = true;
			this.vmethod_24().Location = new global::System.Drawing.Point(317, 247);
			this.vmethod_24().Name = "Label_MinAlt";
			this.vmethod_24().RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.vmethod_24().Size = new global::System.Drawing.Size(36, 13);
			this.vmethod_24().TabIndex = 13;
			this.vmethod_24().Text = "MinAlt";
			this.vmethod_24().TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.vmethod_26().AutoSize = true;
			this.vmethod_26().Location = new global::System.Drawing.Point(90, 43);
			this.vmethod_26().Name = "Label_DesiredAlt";
			this.vmethod_26().Size = new global::System.Drawing.Size(55, 13);
			this.vmethod_26().TabIndex = 14;
			this.vmethod_26().Text = "DesiredAlt";
			this.vmethod_28().AutoSize = true;
			this.vmethod_28().Location = new global::System.Drawing.Point(90, 61);
			this.vmethod_28().Name = "Label_CurrentAlt";
			this.vmethod_28().Size = new global::System.Drawing.Size(53, 13);
			this.vmethod_28().TabIndex = 15;
			this.vmethod_28().Text = "CurrentAlt";
			this.vmethod_30().Controls.Add(this.vmethod_70());
			this.vmethod_30().Controls.Add(this.vmethod_38());
			this.vmethod_30().Controls.Add(this.vmethod_34());
			this.vmethod_30().Controls.Add(this.vmethod_72());
			this.vmethod_30().Controls.Add(this.vmethod_2());
			this.vmethod_30().Controls.Add(this.vmethod_0());
			this.vmethod_30().Controls.Add(this.vmethod_4());
			this.vmethod_30().Controls.Add(this.vmethod_6());
			this.vmethod_30().Controls.Add(this.vmethod_8());
			this.vmethod_30().Controls.Add(this.vmethod_10());
			this.vmethod_30().Controls.Add(this.vmethod_12());
			this.vmethod_30().Controls.Add(this.vmethod_140());
			this.vmethod_30().Location = new global::System.Drawing.Point(5, 1);
			this.vmethod_30().Name = "GroupBox1";
			this.vmethod_30().Size = new global::System.Drawing.Size(409, 164);
			this.vmethod_30().TabIndex = 16;
			this.vmethod_30().TabStop = false;
			this.vmethod_30().Text = "油门";
			this.vmethod_70().Location = new global::System.Drawing.Point(119, 16);
			this.vmethod_70().Name = "TextBox_EnterSpeed";
			this.vmethod_70().Size = new global::System.Drawing.Size(60, 20);
			this.vmethod_70().TabIndex = 2;
			this.vmethod_38().AutoSize = true;
			this.vmethod_38().Location = new global::System.Drawing.Point(9, 20);
			this.vmethod_38().Name = "CB_SpeedOverride";
			this.vmethod_38().Size = new global::System.Drawing.Size(104, 17);
			this.vmethod_38().TabIndex = 1;
			this.vmethod_38().Text = "手动覆盖";
			this.vmethod_38().UseVisualStyleBackColor = true;
			this.vmethod_34().Controls.Add(this.vmethod_150());
			this.vmethod_34().Controls.Add(this.vmethod_86());
			this.vmethod_34().Controls.Add(this.vmethod_78());
			this.vmethod_34().Controls.Add(this.vmethod_80());
			this.vmethod_34().Controls.Add(this.vmethod_82());
			this.vmethod_34().Controls.Add(this.vmethod_84());
			this.vmethod_34().Location = new global::System.Drawing.Point(6, 113);
			this.vmethod_34().Name = "GroupBox_SpeedPresets";
			this.vmethod_34().Size = new global::System.Drawing.Size(397, 44);
			this.vmethod_34().TabIndex = 10;
			this.vmethod_34().TabStop = false;
			this.vmethod_34().Text = "预置油门";
			this.vmethod_150().AutoSize = true;
			this.vmethod_150().Location = new global::System.Drawing.Point(335, 19);
			this.vmethod_150().Name = "RB_NoThrottlePreset";
			this.vmethod_150().Size = new global::System.Drawing.Size(51, 17);
			this.vmethod_150().TabIndex = 5;
			this.vmethod_150().TabStop = true;
			this.vmethod_150().Text = "无";
			this.vmethod_150().UseVisualStyleBackColor = true;
			this.vmethod_86().AutoSize = true;
			this.vmethod_86().Location = new global::System.Drawing.Point(250, 20);
			this.vmethod_86().Name = "RB_Flank";
			this.vmethod_86().Size = new global::System.Drawing.Size(80, 17);
			this.vmethod_86().TabIndex = 0;
			this.vmethod_86().TabStop = true;
			this.vmethod_86().Text = "最大";
			this.vmethod_86().UseVisualStyleBackColor = true;
			this.vmethod_78().AutoSize = true;
			this.vmethod_78().Location = new global::System.Drawing.Point(190, 20);
			this.vmethod_78().Name = "RB_Full";
			this.vmethod_78().Size = new global::System.Drawing.Size(60, 17);
			this.vmethod_78().TabIndex = 4;
			this.vmethod_78().TabStop = true;
			this.vmethod_78().Text = "全速";
			this.vmethod_78().UseVisualStyleBackColor = true;
			this.vmethod_80().AutoSize = true;
			this.vmethod_80().Location = new global::System.Drawing.Point(130, 20);
			this.vmethod_80().Name = "RB_Cruise";
			this.vmethod_80().Size = new global::System.Drawing.Size(54, 17);
			this.vmethod_80().TabIndex = 3;
			this.vmethod_80().TabStop = true;
			this.vmethod_80().Text = "巡航";
			this.vmethod_80().UseVisualStyleBackColor = true;
			this.vmethod_82().AutoSize = true;
			this.vmethod_82().Location = new global::System.Drawing.Point(70, 20);
			this.vmethod_82().Name = "RB_Creep";
			this.vmethod_82().Size = new global::System.Drawing.Size(53, 17);
			this.vmethod_82().TabIndex = 2;
			this.vmethod_82().TabStop = true;
			this.vmethod_82().Text = "最小";
			this.vmethod_82().UseVisualStyleBackColor = true;
			this.vmethod_84().AutoSize = true;
			this.vmethod_84().Location = new global::System.Drawing.Point(10, 20);
			this.vmethod_84().Name = "RB_Stop";
			this.vmethod_84().Size = new global::System.Drawing.Size(47, 17);
			this.vmethod_84().TabIndex = 1;
			this.vmethod_84().TabStop = true;
			this.vmethod_84().Text = "停车";
			this.vmethod_84().UseVisualStyleBackColor = true;
			this.vmethod_72().AutoSize = true;
			this.vmethod_72().Location = new global::System.Drawing.Point(185, 19);
			this.vmethod_72().Name = "Label_Speed";
			this.vmethod_72().Size = new global::System.Drawing.Size(16, 13);
			this.vmethod_72().TabIndex = 3;
			this.vmethod_72().Text = "节";
			this.vmethod_140().AutoSize = true;
			this.vmethod_140().Location = new global::System.Drawing.Point(220, 42);
			this.vmethod_140().Name = "Label_Cavitation";
			this.vmethod_140().Size = new global::System.Drawing.Size(83, 13);
			this.vmethod_140().TabIndex = 11;
			this.vmethod_140().Text = "Label Cavitation";
			this.vmethod_90().AutoSize = true;
			this.vmethod_90().Location = new global::System.Drawing.Point(5, 20);
			this.vmethod_90().Name = "Label_WaypointName";
			this.vmethod_90().Size = new global::System.Drawing.Size(80, 13);
			this.vmethod_90().TabIndex = 11;
			this.vmethod_90().Text = "WaypointName";
			this.vmethod_32().Controls.Add(this.vmethod_142());
			this.vmethod_32().Controls.Add(this.vmethod_136());
			this.vmethod_32().Controls.Add(this.vmethod_138());
			this.vmethod_32().Controls.Add(this.vmethod_132());
			this.vmethod_32().Controls.Add(this.vmethod_134());
			this.vmethod_32().Controls.Add(this.vmethod_126());
			this.vmethod_32().Controls.Add(this.vmethod_128());
			this.vmethod_32().Controls.Add(this.vmethod_130());
			this.vmethod_32().Controls.Add(this.vmethod_118());
			this.vmethod_32().Controls.Add(this.vmethod_124());
			this.vmethod_32().Controls.Add(this.vmethod_122());
			this.vmethod_32().Controls.Add(this.vmethod_120());
			this.vmethod_32().Controls.Add(this.vmethod_116());
			this.vmethod_32().Controls.Add(this.vmethod_114());
			this.vmethod_32().Controls.Add(this.vmethod_112());
			this.vmethod_32().Controls.Add(this.vmethod_110());
			this.vmethod_32().Controls.Add(this.vmethod_108());
			this.vmethod_32().Controls.Add(this.vmethod_22());
			this.vmethod_32().Controls.Add(this.vmethod_24());
			this.vmethod_32().Controls.Add(this.vmethod_88());
			this.vmethod_32().Controls.Add(this.vmethod_76());
			this.vmethod_32().Controls.Add(this.vmethod_74());
			this.vmethod_32().Controls.Add(this.GetCB_AltOverride());
			this.vmethod_32().Controls.Add(this.vmethod_20());
			this.vmethod_32().Controls.Add(this.vmethod_16());
			this.vmethod_32().Controls.Add(this.vmethod_28());
			this.vmethod_32().Controls.Add(this.vmethod_18());
			this.vmethod_32().Controls.Add(this.vmethod_26());
			this.vmethod_32().Controls.Add(this.vmethod_144());
			this.vmethod_32().Location = new global::System.Drawing.Point(5, 175);
			this.vmethod_32().Name = "GroupBox2";
			this.vmethod_32().Size = new global::System.Drawing.Size(409, 303);
			this.vmethod_32().TabIndex = 17;
			this.vmethod_32().TabStop = false;
			this.vmethod_32().Text = "高度";
			this.vmethod_142().AutoSize = true;
			this.vmethod_142().Location = new global::System.Drawing.Point(9, 279);
			this.vmethod_142().Name = "CB_TerrainFollowing";
			this.vmethod_142().Size = new global::System.Drawing.Size(243, 17);
			this.vmethod_142().TabIndex = 44;
			this.vmethod_142().Text = "地形跟随(真高)";
			this.vmethod_142().UseVisualStyleBackColor = true;
			this.vmethod_136().AutoSize = true;
			this.vmethod_136().Location = new global::System.Drawing.Point(311, 61);
			this.vmethod_136().Name = "Label14";
			this.vmethod_136().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_136().TabIndex = 42;
			this.vmethod_136().Text = "Label14";
			this.vmethod_138().AutoSize = true;
			this.vmethod_138().Location = new global::System.Drawing.Point(311, 124);
			this.vmethod_138().Name = "Label13";
			this.vmethod_138().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_138().TabIndex = 41;
			this.vmethod_138().Text = "Label13";
			this.vmethod_132().AutoSize = true;
			this.vmethod_132().Location = new global::System.Drawing.Point(311, 216);
			this.vmethod_132().Name = "Label12";
			this.vmethod_132().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_132().TabIndex = 40;
			this.vmethod_132().Text = "Label12";
			this.vmethod_134().AutoSize = true;
			this.vmethod_134().Location = new global::System.Drawing.Point(311, 194);
			this.vmethod_134().Name = "Label11";
			this.vmethod_134().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_134().TabIndex = 39;
			this.vmethod_134().Text = "Label11";
            //ZSP ERR IMG this.vmethod_126().Image = global::ns32.Class2470.smethod_1();
            this.vmethod_126().Location = new global::System.Drawing.Point(256, 121);
			this.vmethod_126().Name = "CloudLowTopPictureBox";
			this.vmethod_126().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_126().TabIndex = 38;
			this.vmethod_126().TabStop = false;
            //ZSP ERR IMG this.vmethod_128().Image = global::ns32.Class2470.smethod_1();
            this.vmethod_128().Location = new global::System.Drawing.Point(256, 226);
			this.vmethod_128().Name = "CloudLowBottomPictureBox";
			this.vmethod_128().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_128().TabIndex = 37;
			this.vmethod_128().TabStop = false;
            //ZSP ERR IMG this.vmethod_130().Image = global::ns32.Class2470.smethod_1();
            this.vmethod_130().Location = new global::System.Drawing.Point(256, 208);
			this.vmethod_130().Name = "CloudHighBottomPictureBox";
			this.vmethod_130().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_130().TabIndex = 36;
			this.vmethod_130().TabStop = false;
			this.vmethod_118().AutoSize = true;
			this.vmethod_118().Location = new global::System.Drawing.Point(311, 81);
			this.vmethod_118().Name = "Label7";
			this.vmethod_118().Size = new global::System.Drawing.Size(39, 13);
			this.vmethod_118().TabIndex = 32;
			this.vmethod_118().Text = "Label7";
			this.vmethod_118().TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.vmethod_124().AutoSize = true;
			this.vmethod_124().Location = new global::System.Drawing.Point(311, 168);
			this.vmethod_124().Name = "Label10";
			this.vmethod_124().Size = new global::System.Drawing.Size(45, 13);
			this.vmethod_124().TabIndex = 35;
			this.vmethod_124().Text = "Label10";
			this.vmethod_122().AutoSize = true;
			this.vmethod_122().Location = new global::System.Drawing.Point(311, 146);
			this.vmethod_122().Name = "Label9";
			this.vmethod_122().Size = new global::System.Drawing.Size(39, 13);
			this.vmethod_122().TabIndex = 34;
			this.vmethod_122().Text = "Label9";
			this.vmethod_120().AutoSize = true;
			this.vmethod_120().Location = new global::System.Drawing.Point(311, 104);
			this.vmethod_120().Name = "Label8";
			this.vmethod_120().Size = new global::System.Drawing.Size(39, 13);
			this.vmethod_120().TabIndex = 33;
			this.vmethod_120().Text = "Label8";
            //ZSP ERR IMG this.vmethod_116().Image = global::ns32.Class2470.smethod_2();
            this.vmethod_116().Location = new global::System.Drawing.Point(256, 168);
			this.vmethod_116().Name = "GroundLevelPictureBox";
			this.vmethod_116().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_116().TabIndex = 30;
			this.vmethod_116().TabStop = false;
            //ZSP ERR IMG this.vmethod_114().Image = global::ns32.Class2470.smethod_1();
            this.vmethod_114().Location = new global::System.Drawing.Point(256, 190);
			this.vmethod_114().Name = "CloudHighTopPictureBox";
			this.vmethod_114().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_114().TabIndex = 28;
			this.vmethod_114().TabStop = false;
            //ZSP ERR IMG this.vmethod_112().Image = global::ns32.Class2470.smethod_6();
            this.vmethod_112().Location = new global::System.Drawing.Point(256, 146);
			this.vmethod_112().Name = "SeaFloorPictureBox";
			this.vmethod_112().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_112().TabIndex = 27;
			this.vmethod_112().TabStop = false;
            //ZSP ERR IMG this.vmethod_110().Image = global::ns32.Class2470.smethod_3();
            this.vmethod_110().Location = new global::System.Drawing.Point(256, 103);
			this.vmethod_110().Name = "LayerBottomPictureBox";
			this.vmethod_110().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_110().TabIndex = 26;
			this.vmethod_110().TabStop = false;
            //ZSP ERR IMG this.vmethod_108().Image = global::ns32.Class2470.Read();
            this.vmethod_108().Location = new global::System.Drawing.Point(256, 80);
			this.vmethod_108().Name = "LayerTopPictureBox";
			this.vmethod_108().Size = new global::System.Drawing.Size(28, 12);
			this.vmethod_108().TabIndex = 25;
			this.vmethod_108().TabStop = false;
			this.vmethod_88().Controls.Add(this.GetGroupBox_AltitudePresets());
			this.vmethod_88().Controls.Add(this.GetGroupBox_SubDepthPreset());
			this.vmethod_88().Location = new global::System.Drawing.Point(7, 78);
			this.vmethod_88().Name = "FlowLayoutPanel1";
			this.vmethod_88().Size = new global::System.Drawing.Size(214, 199);
			this.vmethod_88().TabIndex = 24;
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_NoAltitudePreset());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_MediumAltitude12000());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_LowAltitude2000());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_MinAltitude());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_LowAltitude1000());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_HighAltitude25000());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_HighAltitude36000());
			this.GetGroupBox_AltitudePresets().Controls.Add(this.GetRB_MaxAltitude());
			this.GetGroupBox_AltitudePresets().Location = new global::System.Drawing.Point(3, 3);
			this.GetGroupBox_AltitudePresets().Name = "GroupBox_AltitudePresets";
			this.GetGroupBox_AltitudePresets().Size = new global::System.Drawing.Size(158, 195);
			this.GetGroupBox_AltitudePresets().TabIndex = 21;
			this.GetGroupBox_AltitudePresets().TabStop = false;
			this.GetGroupBox_AltitudePresets().Text = "预置高度";
			this.GetRB_NoAltitudePreset().AutoSize = true;
			this.GetRB_NoAltitudePreset().Location = new global::System.Drawing.Point(6, 173);
			this.GetRB_NoAltitudePreset().Name = "RB_NoAltitudePreset";
			this.GetRB_NoAltitudePreset().Size = new global::System.Drawing.Size(51, 17);
			this.GetRB_NoAltitudePreset().TabIndex = 7;
			this.GetRB_NoAltitudePreset().TabStop = true;
			this.GetRB_NoAltitudePreset().Text = "无";
			this.GetRB_NoAltitudePreset().UseVisualStyleBackColor = true;
			this.GetRB_MediumAltitude12000().AutoSize = true;
			this.GetRB_MediumAltitude12000().Location = new global::System.Drawing.Point(6, 85);
			this.GetRB_MediumAltitude12000().Name = "RB_MediumAltitude12000";
			this.GetRB_MediumAltitude12000().Size = new global::System.Drawing.Size(148, 17);
			this.GetRB_MediumAltitude12000().TabIndex = 6;
			this.GetRB_MediumAltitude12000().TabStop = true;
			this.GetRB_MediumAltitude12000().Text = "中空(12000英尺)";
			this.GetRB_MediumAltitude12000().UseVisualStyleBackColor = true;
			this.GetRB_LowAltitude2000().AutoSize = true;
			this.GetRB_LowAltitude2000().Location = new global::System.Drawing.Point(6, 107);
			this.GetRB_LowAltitude2000().Name = "RB_LowAltitude2000";
			this.GetRB_LowAltitude2000().Size = new global::System.Drawing.Size(125, 17);
			this.GetRB_LowAltitude2000().TabIndex = 5;
			this.GetRB_LowAltitude2000().TabStop = true;
			this.GetRB_LowAltitude2000().Text = "低空(2000英尺)";
			this.GetRB_LowAltitude2000().UseVisualStyleBackColor = true;
			this.GetRB_MinAltitude().AutoSize = true;
			this.GetRB_MinAltitude().Location = new global::System.Drawing.Point(6, 151);
			this.GetRB_MinAltitude().Name = "RB_MinAltitude";
			this.GetRB_MinAltitude().Size = new global::System.Drawing.Size(80, 17);
			this.GetRB_MinAltitude().TabIndex = 4;
			this.GetRB_MinAltitude().TabStop = true;
			this.GetRB_MinAltitude().Text = "最小高度";
			this.GetRB_MinAltitude().UseVisualStyleBackColor = true;
			this.GetRB_LowAltitude1000().AutoSize = true;
			this.GetRB_LowAltitude1000().Location = new global::System.Drawing.Point(6, 129);
			this.GetRB_LowAltitude1000().Name = "RB_LowAltitude1000";
			this.GetRB_LowAltitude1000().Size = new global::System.Drawing.Size(125, 17);
			this.GetRB_LowAltitude1000().TabIndex = 3;
			this.GetRB_LowAltitude1000().TabStop = true;
			this.GetRB_LowAltitude1000().Text = "低空(1000英尺)";
			this.GetRB_LowAltitude1000().UseVisualStyleBackColor = true;
			this.GetRB_HighAltitude25000().AutoSize = true;
			this.GetRB_HighAltitude25000().Location = new global::System.Drawing.Point(6, 63);
			this.GetRB_HighAltitude25000().Name = "RB_HighAltitude25000";
			this.GetRB_HighAltitude25000().Size = new global::System.Drawing.Size(133, 17);
			this.GetRB_HighAltitude25000().TabIndex = 2;
			this.GetRB_HighAltitude25000().TabStop = true;
			this.GetRB_HighAltitude25000().Text = "高空(25000英尺)";
			this.GetRB_HighAltitude25000().UseVisualStyleBackColor = true;
			this.GetRB_HighAltitude36000().AutoSize = true;
			this.GetRB_HighAltitude36000().Location = new global::System.Drawing.Point(6, 41);
			this.GetRB_HighAltitude36000().Name = "RB_HighAltitude36000";
			this.GetRB_HighAltitude36000().Size = new global::System.Drawing.Size(133, 17);
			this.GetRB_HighAltitude36000().TabIndex = 1;
			this.GetRB_HighAltitude36000().TabStop = true;
			this.GetRB_HighAltitude36000().Text = "高空(36000英尺)";
			this.GetRB_HighAltitude36000().UseVisualStyleBackColor = true;
			this.GetRB_MaxAltitude().AutoSize = true;
			this.GetRB_MaxAltitude().Location = new global::System.Drawing.Point(6, 19);
			this.GetRB_MaxAltitude().Name = "RB_MaxAltitude";
			this.GetRB_MaxAltitude().Size = new global::System.Drawing.Size(83, 17);
			this.GetRB_MaxAltitude().TabIndex = 0;
			this.GetRB_MaxAltitude().TabStop = true;
			this.GetRB_MaxAltitude().Text = "最大高度";
			this.GetRB_MaxAltitude().UseVisualStyleBackColor = true;
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_NoDepthPreset());
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_Surface());
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_Shallow());
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_MaxDepth());
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_UnderLayer());
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_OverLayer());
			this.GetGroupBox_SubDepthPreset().Controls.Add(this.GetRB_Periscope());
			this.GetGroupBox_SubDepthPreset().Location = new global::System.Drawing.Point(3, 204);
			this.GetGroupBox_SubDepthPreset().Name = "GroupBox_SubDepthPreset";
			this.GetGroupBox_SubDepthPreset().Size = new global::System.Drawing.Size(158, 195);
			this.GetGroupBox_SubDepthPreset().TabIndex = 17;
			this.GetGroupBox_SubDepthPreset().TabStop = false;
			this.GetGroupBox_SubDepthPreset().Text = "预置深度";
			this.GetRB_NoDepthPreset().AutoSize = true;
			this.GetRB_NoDepthPreset().Location = new global::System.Drawing.Point(6, 151);
			this.GetRB_NoDepthPreset().Name = "RB_NoDepthPreset";
			this.GetRB_NoDepthPreset().Size = new global::System.Drawing.Size(51, 17);
			this.GetRB_NoDepthPreset().TabIndex = 7;
			this.GetRB_NoDepthPreset().TabStop = true;
			this.GetRB_NoDepthPreset().Text = "无";
			this.GetRB_NoDepthPreset().UseVisualStyleBackColor = true;
			this.GetRB_Surface().AutoSize = true;
			this.GetRB_Surface().Location = new global::System.Drawing.Point(6, 19);
			this.GetRB_Surface().Name = "RB_Surface";
			this.GetRB_Surface().Size = new global::System.Drawing.Size(62, 17);
			this.GetRB_Surface().TabIndex = 18;
			this.GetRB_Surface().TabStop = true;
			this.GetRB_Surface().Text = "水面";
			this.GetRB_Surface().UseVisualStyleBackColor = true;
			this.GetRB_Shallow().AutoSize = true;
			this.GetRB_Shallow().Location = new global::System.Drawing.Point(6, 63);
			this.GetRB_Shallow().Name = "RB_Shallow";
			this.GetRB_Shallow().Size = new global::System.Drawing.Size(62, 17);
			this.GetRB_Shallow().TabIndex = 4;
			this.GetRB_Shallow().TabStop = true;
			this.GetRB_Shallow().Text = "浅";
			this.GetRB_Shallow().UseVisualStyleBackColor = true;
			this.GetRB_MaxDepth().AutoSize = true;
			this.GetRB_MaxDepth().Location = new global::System.Drawing.Point(6, 129);
			this.GetRB_MaxDepth().Name = "RB_MaxDepth";
			this.GetRB_MaxDepth().Size = new global::System.Drawing.Size(119, 17);
			this.GetRB_MaxDepth().TabIndex = 3;
			this.GetRB_MaxDepth().TabStop = true;
			this.GetRB_MaxDepth().Text = "尽可能深";
			this.GetRB_MaxDepth().UseVisualStyleBackColor = true;
			this.GetRB_UnderLayer().AutoSize = true;
			this.GetRB_UnderLayer().Location = new global::System.Drawing.Point(6, 107);
			this.GetRB_UnderLayer().Name = "RB_UnderLayer";
			this.GetRB_UnderLayer().Size = new global::System.Drawing.Size(117, 17);
			this.GetRB_UnderLayer().TabIndex = 2;
			this.GetRB_UnderLayer().TabStop = true;
			this.GetRB_UnderLayer().Text = "刚好在温跃层下";
			this.GetRB_UnderLayer().UseVisualStyleBackColor = true;
			this.GetRB_OverLayer().AutoSize = true;
			this.GetRB_OverLayer().Location = new global::System.Drawing.Point(6, 85);
			this.GetRB_OverLayer().Name = "RB_OverLayer";
			this.GetRB_OverLayer().Size = new global::System.Drawing.Size(111, 17);
			this.GetRB_OverLayer().TabIndex = 1;
			this.GetRB_OverLayer().TabStop = true;
			this.GetRB_OverLayer().Text = "刚好在温跃层上";
			this.GetRB_OverLayer().UseVisualStyleBackColor = true;
			this.GetRB_Periscope().AutoSize = true;
			this.GetRB_Periscope().Location = new global::System.Drawing.Point(6, 41);
			this.GetRB_Periscope().Name = "RB_Periscope";
			this.GetRB_Periscope().Size = new global::System.Drawing.Size(102, 17);
			this.GetRB_Periscope().TabIndex = 0;
			this.GetRB_Periscope().TabStop = true;
			this.GetRB_Periscope().Text = "潜望镜深度";
			this.GetRB_Periscope().UseVisualStyleBackColor = true;
			this.vmethod_76().AutoSize = true;
			this.vmethod_76().Location = new global::System.Drawing.Point(188, 21);
			this.vmethod_76().Name = "Label_Altitude";
			this.vmethod_76().Size = new global::System.Drawing.Size(74, 13);
			this.vmethod_76().TabIndex = 23;
			this.vmethod_76().Text = "Label_Altitude";
			this.vmethod_74().Location = new global::System.Drawing.Point(119, 17);
			this.vmethod_74().Name = "TextBox_EnterAltitude";
			this.vmethod_74().Size = new global::System.Drawing.Size(60, 20);
			this.vmethod_74().TabIndex = 20;
			this.GetCB_AltOverride().AutoSize = true;
			this.GetCB_AltOverride().Location = new global::System.Drawing.Point(9, 20);
			this.GetCB_AltOverride().Name = "CB_AltOverride";
			this.GetCB_AltOverride().Size = new global::System.Drawing.Size(104, 17);
			this.GetCB_AltOverride().TabIndex = 16;
			this.GetCB_AltOverride().Text = "手动覆盖";
			this.GetCB_AltOverride().UseVisualStyleBackColor = true;
			this.vmethod_144().Location = new global::System.Drawing.Point(3, 16);
			this.vmethod_144().Margin = new global::System.Windows.Forms.Padding(0);
			this.vmethod_144().Name = "ShapeContainer1";
			this.vmethod_144().Shapes.AddRange(new global::Microsoft.VisualBasic.PowerPacks.Shape[]
			{
				this.vmethod_146(),
				this.vmethod_148()
			});
			this.vmethod_144().Size = new global::System.Drawing.Size(377, 284);
			this.vmethod_144().TabIndex = 43;
			this.vmethod_144().TabStop = false;
			this.vmethod_146().BorderColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.vmethod_146().BorderWidth = 3;
			this.vmethod_146().Name = "LineShape2";
			this.vmethod_146().X1 = 256;
			this.vmethod_146().X2 = 256;
			this.vmethod_146().Y1 = 33;
			this.vmethod_146().Y2 = 179;
			this.vmethod_148().BorderColor = global::System.Drawing.Color.FromArgb(64, 64, 64);
			this.vmethod_148().BorderWidth = 3;
			this.vmethod_148().Name = "LineShape1";
			this.vmethod_148().X1 = 256;
			this.vmethod_148().X2 = 256;
			this.vmethod_148().Y1 = 70;
			this.vmethod_148().Y2 = 216;
			this.vmethod_92().Controls.Add(this.vmethod_104());
			this.vmethod_92().Controls.Add(this.vmethod_106());
			this.vmethod_92().Controls.Add(this.vmethod_100());
			this.vmethod_92().Controls.Add(this.GetCB_WaypointType());
			this.vmethod_92().Controls.Add(this.vmethod_98());
			this.vmethod_92().Controls.Add(this.vmethod_94());
			this.vmethod_92().Controls.Add(this.vmethod_96());
			this.vmethod_92().Controls.Add(this.vmethod_90());
			this.vmethod_92().Location = new global::System.Drawing.Point(5, 487);
			this.vmethod_92().Name = "GroupBox3";
			this.vmethod_92().Size = new global::System.Drawing.Size(409, 131);
			this.vmethod_92().TabIndex = 18;
			this.vmethod_92().TabStop = false;
			this.vmethod_92().Text = "航路点";
			this.vmethod_104().AutoSize = true;
			this.vmethod_104().Location = new global::System.Drawing.Point(5, 102);
			this.vmethod_104().Name = "Label4";
			this.vmethod_104().Size = new global::System.Drawing.Size(34, 13);
			this.vmethod_104().TabIndex = 21;
			this.vmethod_104().Text = "类型:";
			this.vmethod_106().AutoSize = true;
			this.vmethod_106().Location = new global::System.Drawing.Point(5, 84);
			this.vmethod_106().Name = "Label1";
			this.vmethod_106().Size = new global::System.Drawing.Size(63, 13);
			this.vmethod_106().TabIndex = 20;
			this.vmethod_106().Text = "描述:";
			this.vmethod_100().Location = new global::System.Drawing.Point(69, 80);
			this.vmethod_100().Name = "TextBox_WaypointDescription";
			this.vmethod_100().Size = new global::System.Drawing.Size(306, 20);
			this.vmethod_100().TabIndex = 19;
			this.GetCB_WaypointType().DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.GetCB_WaypointType().FormattingEnabled = true;
			this.GetCB_WaypointType().Items.AddRange(new object[]
			{
				"加入编队 ",
				"计划航线/导航",
				"目标"
			});
			this.GetCB_WaypointType().Location = new global::System.Drawing.Point(69, 102);
			this.GetCB_WaypointType().Name = "CB_WaypointType";
			this.GetCB_WaypointType().Size = new global::System.Drawing.Size(306, 21);
			this.GetCB_WaypointType().TabIndex = 18;
			this.vmethod_98().AutoSize = true;
			this.vmethod_98().Location = new global::System.Drawing.Point(5, 61);
			this.vmethod_98().Name = "Label_Fuel";
			this.vmethod_98().Size = new global::System.Drawing.Size(59, 13);
			this.vmethod_98().TabIndex = 17;
			this.vmethod_98().Text = "Label_Fuel";
			this.vmethod_94().AutoSize = true;
			this.vmethod_94().Location = new global::System.Drawing.Point(88, 43);
			this.vmethod_94().Name = "Label_TTG";
			this.vmethod_94().Size = new global::System.Drawing.Size(61, 13);
			this.vmethod_94().TabIndex = 16;
			this.vmethod_94().Text = "Label_TTG";
			this.vmethod_96().AutoSize = true;
			this.vmethod_96().Location = new global::System.Drawing.Point(5, 43);
			this.vmethod_96().Name = "Label_DTG";
			this.vmethod_96().Size = new global::System.Drawing.Size(62, 13);
			this.vmethod_96().TabIndex = 15;
			this.vmethod_96().Text = "Label_DTG";
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			base.ClientSize = new global::System.Drawing.Size(419, 623);
			base.Controls.Add(this.vmethod_92());
			base.Controls.Add(this.vmethod_32());
			base.Controls.Add(this.vmethod_30());
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.KeyPreview = true;
			base.MaximizeBox = false;
			base.MinimizeBox = false;
			base.Name = "SpeedAlt";
			base.ShowIcon = false;
			base.ShowInTaskbar = false;
			base.SizeGripStyle = global::System.Windows.Forms.SizeGripStyle.Show;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "油门与高度设置:";
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_0()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_16()).EndInit();
			this.vmethod_30().ResumeLayout(false);
			this.vmethod_30().PerformLayout();
			this.vmethod_34().ResumeLayout(false);
			this.vmethod_34().PerformLayout();
			this.vmethod_32().ResumeLayout(false);
			this.vmethod_32().PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_126()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_128()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_130()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_116()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_114()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_112()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_110()).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.vmethod_108()).EndInit();
			this.vmethod_88().ResumeLayout(false);
			this.GetGroupBox_AltitudePresets().ResumeLayout(false);
			this.GetGroupBox_AltitudePresets().PerformLayout();
			this.GetGroupBox_SubDepthPreset().ResumeLayout(false);
			this.GetGroupBox_SubDepthPreset().PerformLayout();
			this.vmethod_92().ResumeLayout(false);
			this.vmethod_92().PerformLayout();
			base.ResumeLayout(false);
		}

		// Token: 0x04002ADB RID: 10971
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
